### ISSUE TITLE
Good Job!

### ISSUE THREAD

**Issue by Mored4u** [Ryujinx/Ryujinx-Games-List#1210]
#### Current on `master` : Build Version : 1.0.4573
Booting with freeze graphics and good sound.

#### Screenshots :
![image](https://user-images.githubusercontent.com/5413459/82128793-7e822a80-97c6-11ea-8a8d-fbfebd37be5a.png)

#### Video :
[bandicam 2020-05-16 22-58-04-677.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4639146/bandicam.2020-05-16.22-58-04-677.zip)

#### Log file :
[Ryujinx_2020-05-16_22-33-56.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4639125/Ryujinx_2020-05-16_22-33-56.zip)

**Comment by GoffyDude** [comment]
What stopped the emulation of this game? Crash or deadlock?

**Comment by GoffyDude** [comment]
Need more information before this can be accepted. What caused the end of emulation? It looks like Ryujinx was closed in just 15 seconds.

**Comment by Mored4u** [comment]
Tested for 12 Minutes (sound are good) then crush.

**Comment by GoffyDude** [comment]
Closing as it seems something is wrong with the testing platform from this user.
