### ISSUE TITLE
Animal Crossing New Horizons Crashes and bugs.

### ISSUE THREAD

**Issue by MasonBlood9696** [Ryujinx/Ryujinx-Games-List#1222]
Animal Crossing New Horizons 1.2.0
Ryujinx 1.0.4526
System Version 9.2.0

Crashes:
The game is not closing but I only get a message from the game something like: Close game and play again. 

Game crashes if I'm only standing for a few minutes in game. 
Game crashes if I play it on full screen mode. Happens in a few minutes. 

Unfortunately my Ryujinx console is not showing anything specific. Only black screen.

Bugs:
Game sound is weird or not playing the sound but only music. Happens very often. 

Overall the game is playable! Thank you!

**Comment by GoffyDude** [comment]
Please come to Ryujinx discord for help on this. https://discord.gg/VkQYXAZ
Closing in favor of https://github.com/Ryujinx/Ryujinx-Games-List/issues/250
