### ISSUE TITLE
Trials of Mana

### ISSUE THREAD

**Issue by Mored4u** [Ryujinx/Ryujinx-Games-List#1232]
#### Current on `master` : Build Version : 1.0.0-acnh2-win_x64
Not booting.
 
#### Current on `master` : Build Version : 1.0.4573
Booting with sound play once after 3-5 minutes.

#### Screenshots :
![image](https://user-images.githubusercontent.com/5413459/82114411-544c5080-9765-11ea-8191-791b890d2d74.png)

#### Log file :
[Ryujinx_2020-05-16_16-27-33.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4638451/Ryujinx_2020-05-16_16-27-33.log)

**Comment by GoffyDude** [comment]
Need more information before this can be accepted. Was there actual sound being played? What caused the end of emulation? It look liks Ryujinx was closed in under 2 minutes.

**Comment by Seker-0** [comment]
This game requires this pr to be able to boot https://github.com/Ryujinx/Ryujinx/pull/1216

**Comment by Mored4u** [comment]
Tested for 12 minutes (sound played once after 3-5 minutes)

**Comment by GoffyDude** [comment]
Closing as it seems something is wrong with the testing platform from this user.
