### ISSUE TITLE
The Complex

### ISSUE THREAD

**Issue by Mored4u** [Ryujinx/Ryujinx-Games-List#1233]
#### Current on `master` : Build Version : 1.0.4573
Booting, graphics are black, and sound are good.

#### Screenshots :
![image](https://user-images.githubusercontent.com/5413459/82115033-fd487a80-9768-11ea-9700-b375e678849f.png)

#### Log file :
[Ryujinx_2020-05-16_15-45-52.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4638417/Ryujinx_2020-05-16_15-45-52.zip)

**Comment by GoffyDude** [comment]
Need more information before this can be accepted. Was there actual sound being played? What caused the end of emulation? It look liks Ryujinx was closed in under 2 minutes.

**Comment by Mored4u** [comment]
Done for 12 Minutes (sound appear)

**Comment by GoffyDude** [comment]
Closing as it seems something is wrong with the testing platform from this user.
