### ISSUE TITLE
Just Dance 2019

### ISSUE THREAD

**Issue by Mored4u** [Ryujinx/Ryujinx-Games-List#1234]
#### Current on `master` : Build Version : 1.0.4573
Booting with sound only.

#### Screenshots :
![image](https://user-images.githubusercontent.com/5413459/82115314-b9567500-976a-11ea-8daf-3ba64cc5a68e.png)

#### Log file :
[Ryujinx_2020-05-16_15-16-15.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4638367/Ryujinx_2020-05-16_15-16-15.zip)

**Comment by GoffyDude** [comment]
Need more information before this can be accepted. Was there actual sound being played? What caused the end of emulation? It look liks Ryujinx was closed in under 3 minutes.

**Comment by Mored4u** [comment]
Done for 17 Minutes (Sound appear but with noise)

**Comment by GoffyDude** [comment]
Booted to menu on first try for me. Closing as it seems something is wrong with the testing platform from this user.
