### ISSUE TITLE
Games Upside Down and One color

### ISSUE THREAD

**Issue by alpdenizgures** [Ryujinx/Ryujinx-Games-List#1267]
Animal Crossing New Horizons and Super Mario Odyssey

Unplayable because of graphics glitches. 

I have only tried Ryujinx with two games, but both of them returned similar results. In Animal Crossing New Horizons, the game starts out upside down and everything is black and green. However, the dialogs are the proper color and proper orientation. In Super Mario Odyssey, the game menu starts up normal, but then when the game finally starts, everything is upside down and glitchy, the only colors being orange and black. I have seen a couple of people having the same problem and reporting that they have solved it, but no one told how they solved the problem. 

I am on a Macbook Pro 2018 with Windows 10 installed via Bootcamp. It has a 2.3 GhZ Core i5 processor with Intel Iris 655 graphics and 8 GB of RAM. 

Screenshots: 
![Animal Crossing Gameplay](https://user-images.githubusercontent.com/46475458/82312935-6251d980-99d0-11ea-9378-bb3af9668de9.PNG)
This is how it looks when the game actually loads. 
![Animal Crossing Loading](https://user-images.githubusercontent.com/46475458/82312943-63830680-99d0-11ea-8a17-2260128a814b.PNG)
And this is how the game looks when it is loading, giving me false hope every single time.

**Comment by GoffyDude** [comment]
Please come to discord for assistance on these. I suspect your Intel GPU is the source of your problems.
