### ISSUE TITLE
My Hero One's Justice 2

### ISSUE THREAD

**Issue by Mored4u** [Ryujinx/Ryujinx-Games-List#1288]
#### Current on `master` : Commit Id *or* Build Version : 1.0.4573
into game with (5-12) FPS, no graphics (black screen), sound good.

#### Screenshots :
![bandicam 2020-05-20 09-18-41-986](https://user-images.githubusercontent.com/5413459/82412547-810daa00-9a7c-11ea-8249-5ddf78b7185f.jpg)
![bandicam 2020-05-20 09-19-59-753](https://user-images.githubusercontent.com/5413459/82412551-82d76d80-9a7c-11ea-801e-c4a6678a12e1.jpg)
![bandicam 2020-05-20 09-25-22-600](https://user-images.githubusercontent.com/5413459/82412555-84089a80-9a7c-11ea-8be7-733d146d6ee4.jpg)
![bandicam 2020-05-20 09-25-36-947](https://user-images.githubusercontent.com/5413459/82412560-84a13100-9a7c-11ea-8ba2-0ea2a5251e6b.jpg)
![bandicam 2020-05-20 09-25-40-065](https://user-images.githubusercontent.com/5413459/82412565-85d25e00-9a7c-11ea-91eb-d942c1af7e47.jpg)
![bandicam 2020-05-20 09-25-42-938](https://user-images.githubusercontent.com/5413459/82412568-87038b00-9a7c-11ea-8e10-96b51e0067ee.jpg)
![bandicam 2020-05-20 09-26-20-420](https://user-images.githubusercontent.com/5413459/82412577-89fe7b80-9a7c-11ea-80a5-e490abb9fddb.jpg)

#### Log file :
[Ryujinx_2020-05-20_09-15-21.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4654996/Ryujinx_2020-05-20_09-15-21.log)

**Comment by GoffyDude** [comment]
Testing with Intel HD graphics isn't going to give reliable test results.
