### ISSUE TITLE
The Liar Princess and the Blind Prince

### ISSUE THREAD

**Issue by Seker-0** [Ryujinx/Ryujinx-Games-List#1307]
#### Current on `master` : 1.0.4593

This game can be played but the sound in the game will overlap. Sometimes the game looks slow. But everything looks good

#### Screenshots : 
![bandicam 2020-05-21 23-34-18-475](https://user-images.githubusercontent.com/35269098/82583946-fcc34000-9bbd-11ea-97ff-8b81a4b1dc59.jpg)
![bandicam 2020-05-21 23-36-09-870](https://user-images.githubusercontent.com/35269098/82584023-1795b480-9bbe-11ea-9f8b-e2a4a22b55f9.jpg)
![bandicam 2020-05-21 23-37-58-954](https://user-images.githubusercontent.com/35269098/82584088-2ed4a200-9bbe-11ea-91b8-2c5915460416.jpg)
![bandicam 2020-05-21 23-42-50-358](https://user-images.githubusercontent.com/35269098/82584161-4dd33400-9bbe-11ea-8735-d55514e8bd64.jpg)
![bandicam 2020-05-21 23-42-53-872](https://user-images.githubusercontent.com/35269098/82584179-5461ab80-9bbe-11ea-8ec4-799f4e6db31f.jpg)
![bandicam 2020-05-21 23-43-25-698](https://user-images.githubusercontent.com/35269098/82584219-63485e00-9bbe-11ea-85bb-52466cb4f62b.jpg)
![bandicam 2020-05-21 23-43-49-755](https://user-images.githubusercontent.com/35269098/82584238-69d6d580-9bbe-11ea-9404-7f9c4cdc61c4.jpg)

**Comment by EmulationFanatic** [comment]
Closing in favor of https://github.com/Ryujinx/Ryujinx-Games-List/issues/73
