### ISSUE TITLE
Gunloard X

### ISSUE THREAD

**Issue by Mored4u** [Ryujinx/Ryujinx-Games-List#1308]
#### Current on `master` : Commit Id *or* Build Version : 1.0.4573

Playable with 50 FPS, graphics and sound perfect.

```
00:11:23.895 | ServiceHid SendVibrationValues: Stubbed. appletResourceUserId: 0 - VibrationDeviceHandleBufferLength: 8 - VibrationValueBufferLength: 32
00:11:23.898 | GUI.WindowThread ServiceNv Close: Closing channel
00:11:23.900 | HLE.HostThread.5 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:11:23.900 | HLE.HostThread.7 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:11:23.901 | HLE.HostThread.2 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:11:23.901 | HLE.HostThread.4 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:11:23.901 | HLE.HostThread.6 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
```
#### Screenshots :
![bandicam 2020-05-21 22-53-02-858](https://user-images.githubusercontent.com/5413459/82601269-faf67e00-9bb7-11ea-9392-e25b9c3977c3.jpg)
![bandicam 2020-05-21 22-53-22-616](https://user-images.githubusercontent.com/5413459/82601274-fcc04180-9bb7-11ea-9f4b-c5f7dfbe6690.jpg)
![bandicam 2020-05-21 22-53-55-265](https://user-images.githubusercontent.com/5413459/82601289-00ec5f00-9bb8-11ea-90e3-dc14c75b5b2a.jpg)
![bandicam 2020-05-21 22-53-59-169](https://user-images.githubusercontent.com/5413459/82601295-034eb900-9bb8-11ea-8d00-64dbe5d8a041.jpg)
![bandicam 2020-05-21 22-54-35-432](https://user-images.githubusercontent.com/5413459/82601300-0649a980-9bb8-11ea-89af-541d719c56c1.jpg)
![bandicam 2020-05-21 22-54-47-369](https://user-images.githubusercontent.com/5413459/82601308-0a75c700-9bb8-11ea-9eba-6764f0e45d2f.jpg)
![bandicam 2020-05-21 22-55-54-622](https://user-images.githubusercontent.com/5413459/82601323-0ea1e480-9bb8-11ea-9eab-d18843990abf.jpg)
![bandicam 2020-05-21 22-56-11-161](https://user-images.githubusercontent.com/5413459/82601332-11043e80-9bb8-11ea-89c3-8d711b183b3e.jpg)
![bandicam 2020-05-21 22-56-51-904](https://user-images.githubusercontent.com/5413459/82601336-13669880-9bb8-11ea-8418-62c604f2be91.jpg)
![bandicam 2020-05-21 22-57-35-797](https://user-images.githubusercontent.com/5413459/82601342-15c8f280-9bb8-11ea-8a2c-29af3f69a92b.jpg)
![bandicam 2020-05-21 22-58-53-101](https://user-images.githubusercontent.com/5413459/82601347-18c3e300-9bb8-11ea-8452-db044fefd5bf.jpg)
![bandicam 2020-05-21 23-01-14-525](https://user-images.githubusercontent.com/5413459/82601359-1cf00080-9bb8-11ea-9857-f30e4b9feb6a.jpg)
![bandicam 2020-05-21 23-01-23-191](https://user-images.githubusercontent.com/5413459/82601367-1feaf100-9bb8-11ea-8181-827d496c46fd.jpg)

#### Log file :
[Ryujinx_2020-05-21_22-50-03.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4664486/Ryujinx_2020-05-21_22-50-03.zip)

**Comment by GoffyDude** [comment]
Closing in favor of https://github.com/Ryujinx/Ryujinx-Games-List/issues/755
