### ISSUE TITLE
Hundred flower garden where flowers bloom in love - 010052300F612000

### ISSUE THREAD

**Issue by SeraUQ** [Ryujinx/Ryujinx-Games-List#1342]
#### Current on `master` : 1.0.6119

Game now loads and plays nicely, but the intro cutscene has messed up colours.

#### Screenshots :

![23:20:52-12_17_20](https://user-images.githubusercontent.com/62521228/102551560-fd727500-40bf-11eb-8a8f-8eee127a2a16.png)
![23:21:28-12_17_20](https://user-images.githubusercontent.com/62521228/102551562-fea3a200-40bf-11eb-89fb-7e2d0ba235f2.png)
![23:21:37-12_17_20](https://user-images.githubusercontent.com/62521228/102551567-0105fc00-40c0-11eb-98d9-2b9ba4e88882.png)
![23:22:41-12_17_20](https://user-images.githubusercontent.com/62521228/102551570-02cfbf80-40c0-11eb-9fde-252ca02ee3e5.png)
![23:22:55-12_17_20](https://user-images.githubusercontent.com/62521228/102551577-05321980-40c0-11eb-84a7-67c514a2a753.png)
![23:23:06-12_17_20](https://user-images.githubusercontent.com/62521228/102551580-07947380-40c0-11eb-9fc6-0a4e49fa7219.png)
![23:23:16-12_17_20](https://user-images.githubusercontent.com/62521228/102551588-0bc09100-40c0-11eb-9dff-f7a79d12cc3a.png)
![23:23:34-12_17_20](https://user-images.githubusercontent.com/62521228/102551595-0d8a5480-40c0-11eb-81cf-e674cf8c21da.png)
![23:24:09-12_17_20](https://user-images.githubusercontent.com/62521228/102551603-0fecae80-40c0-11eb-84ab-0b80338ad6f2.png)
![23:25:03-12_17_20](https://user-images.githubusercontent.com/62521228/102551609-11b67200-40c0-11eb-870d-8bfc6ae2bab6.png)
![23:28:36-12_17_20](https://user-images.githubusercontent.com/62521228/102551615-1549f900-40c0-11eb-9296-6751109fda4b.png)

#### Log file :

[HFGWFBiL.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5712492/HFGWFBiL.log)

**Comment by EmulationFanatic** [comment]
Needs update

**Comment by SeraUQ** [comment]
Updated

**Comment by SeraUQ** [comment]
closing as duplicate
