### ISSUE TITLE
Animal Corssing: New Horizons Doesnot Want To Work For Me

### ISSUE THREAD

**Issue by MaroHD** [Ryujinx/Ryujinx-Games-List#1360]
#### Current on `master` : 

Verison 1.0.1

#### Log file:
00:00:00.060 | Application Main: Ryujinx Version: 1.0.4613
00:00:00.942 | Application LoadApplication: Using Firmware Version: 9.2.0
00:00:00.943 | Application LoadApplication: Loading as XCI.
00:00:01.182 | Loader LoadExeFs: Loading rtld...
00:00:01.187 | Loader LoadExeFs: Loading main...
00:00:02.043 | Loader LoadExeFs: Loading subsdk0...
00:00:02.228 | Loader LoadExeFs: Loading sdk...
00:00:02.962 | Loader LoadNsos: Loading image 0 at 0x0000000008000000...
00:00:02.963 | Loader LoadNsos: Loading image 1 at 0x0000000008004000...
00:00:03.120 | Loader LoadNsos: Loading image 2 at 0x000000000bc39000...
00:00:03.134 | Loader LoadNsos: Loading image 3 at 0x000000000c346000...
00:00:03.191 | Application EnsureSaveData: Ensuring required savedata exists.
00:00:03.499 | Loader LoadNca: Application Loaded: Animal Crossing: New Horizons v1.1.0 [01006f8002326000] [64-bit]
00:00:03.509 | GUI.WindowThread Hid InitController: Connected ControllerType JoyconPair to PlayerIndex Player1
00:00:04.172 | GUI.RenderLoop Gpu PrintGpuInformation: Microsoft Corporation GDI Generic (1.1.0)

**Comment by GoffyDude** [comment]
Looks like you're trying to use Ryujinx in an RDP session or without proper drivers, which will never work. In any case, come to Discord if you need assistance. This is only for gamedb test entries.

**Comment by MaroHD** [comment]
Is There a Way To Fix It?, I Tried To Download Another .NSP File And It Kept Crashing When I Open The .NSP File From Other Folder Not From The Games Folder I Added In Ryujinx It Says Stuff Like Stubbed And Other Things
