### ISSUE TITLE
Animal Crossing: New Horizons game gets stuck before title screen

### ISSUE THREAD

**Issue by maylina1** [Ryujinx/Ryujinx-Games-List#1366]
#### Current on `master` : build version 1.0.7015

The game was playable until the island got 3 star rating and there should be K.K. concert, which is also supposed to be a title screen. The game gets stuck right before the concert+titles begins. All the characters are still moving, but nothing else happens. And there is no way to skip this. So it's impossible to play further.

#### Screenshots :

Stuck on this moment:

![image](https://user-images.githubusercontent.com/65953717/82894447-42d02900-9f5b-11ea-9a18-9d4a795f8858.png)

And this is what supposed to happen afterward:

![image](https://user-images.githubusercontent.com/65953717/82894636-8dea3c00-9f5b-11ea-968b-97e9e71020ca.png)

#### Log file : (keeps doing this over and over again)

00:36:08.909 | ServiceNv Create: Created map 1787 with size 0x00007000!
00:36:08.920 | ServiceNv Create: Created map 1972 with size 0x00045000!
00:36:08.933 | ServiceNv Create: Created map 2388 with size 0x00004000!
00:36:08.968 | ServiceNv DecrementMapRefCount: Deleted map 2478!
00:36:08.969 | ServiceNv Create: Created map 2395 with size 0x00004000!
00:36:08.970 | ServiceNv DecrementMapRefCount: Deleted map 2473!
00:36:08.970 | ServiceNv DecrementMapRefCount: Deleted map 2454!
00:36:08.971 | ServiceNv DecrementMapRefCount: Deleted map 2477!
00:36:10.831 | ServiceNv DecrementMapRefCount: Deleted map 2455!
00:36:14.475 | ServiceNv Create: Created map 2396 with size 0x00004000!
00:36:14.524 | ServiceNv DecrementMapRefCount: Deleted map 2468!
00:36:14.528 | ServiceNv DecrementMapRefCount: Deleted map 2460!
00:36:14.528 | ServiceNv DecrementMapRefCount: Deleted map 2456!
00:36:14.529 | ServiceNv DecrementMapRefCount: Deleted map 2462!

**Comment by GoffyDude** [comment]
Please come to Discord for support; this is for gamedb test entries. Also, you are using a custom build which will not be supported there. Be sure to download the latest version from the Ryujinx website.

**Comment by PythonMaChi** [comment]
目前使用 1.0.5837 後, 會跳出訊息! 如圖, 
![Ry_Bug01](https://user-images.githubusercontent.com/73590132/100604905-206ffb80-3342-11eb-9ebf-c2f9199dc9c5.jpg)
謝謝!
