### ISSUE TITLE
Animal crossing

### ISSUE THREAD

**Issue by UhThatsConfusing** [Ryujinx/Ryujinx-Games-List#1455]
Animal crossing

I'm using ryunjinx 1.0.463
I'm not sure whats the problem maybe I don't know how to even put the game files correctly
So I downloaded animal crossing 1.0.0 and I did all the steps but it doesn't load up in the browse games .
00:00:00.424 | Loader LoadExeFs: NPDM file not found, using default values!
00:00:00.652 | Loader LoadNsos: Process initialization returned error "InvalidMemRange".
00:00:00.653 | Application EnsureSaveData: Ensuring required savedata exists.
00:00:00.653 | Application EnsureSaveData: No control file was found for this game. Using a dummy one instead. This may cause inaccuracies in some games.
I'm not sure what to do

**Comment by GoffyDude** [comment]
Please come to Discord for support and be sure to read the rules. This is for game compatibility database entries only
