### ISSUE TITLE
Animal Crossing New Horizons: Audio breaks while changing Town Tune.

### ISSUE THREAD

**Issue by realguest3920** [Ryujinx/Ryujinx-Games-List#1590]
#### Description :
I just got the town hall built and it seems the audio breaks while trying to change the town tune. When I'm changing notes or just previewing it, I can't hear any audio of the notes or Isabelle talking. Of course it's corrected after I restart the game or exit the town hall. Some other audio issues include, audio playing when it isn't supposed to, Villagers have very quiet voices, and the voices crackle all the time even with 30 fps. Although I doubt anybody would go far enough to build the town hall, I would appreciate it if this was corrected.

**Comment by EmulationFanatic** [comment]
These are known issues and there is already a gamedb entry for this game.
Closing as duplicate in favor of https://github.com/Ryujinx/Ryujinx-Games-List/issues/250
