### ISSUE TITLE
Jump Rope Challenge

### ISSUE THREAD

**Issue by teszNU** [Ryujinx/Ryujinx-Games-List#1804]
Game name: Jump Rope Challenge

Master version: 1.0.4740

Firmware version: 10.0.4

Known Problem: this game is freeware, crash by to boot with memdump label.

Last Fatal error:
00:01:00.627 | Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Am.AppletOE.ApplicationProxyService.ApplicationProxy.IApplicationFunctions: 123

Guest Stack Trace:
Process: Application, PID: 81
   sdk:0x000788dc nn::sf::cmif::client::CmifDomainProxyClientCoreProcessor<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> >, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 0l> >, 0ul, 4ul, false>, std::__1::tuple<nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 0l> > >::Process(nn::sf::cmif::client::CmifDomainClientMessage<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >::ProxyBaseObject*, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, unsigned int)
   sdk:0x001377a4 nn::sf::cmif::client::detail::CmifProxyImpl<nn::am::service::IApplicationFunctions, nn::sf::cmif::client::CmifDomainProxyKind<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >, nn::sf::MemoryResourceAllocationPolicy, nn::am::service::IApplicationFunctions, nn::sf::cmif::client::detail::ProcessModifierImpl<nn::sf::cmif::client::DefaultProxyFilterTag> >::_nn_sf_sync_GetPreviousProgramIndex(nn::sf::Out<int, void>)
   sdk:0x00142eb0 nn::applet::GetPreviousProgramIndex()
   main:0x006c0338 Sub00000000086c4338
   main:0x0022e738 Sub0000000008232738
   main:0x0022e5f4 Sub00000000082325f4
   main:0x0004f6a4 Sub00000000080536a4
   main:0x0069d970 Sub00000000086a1970
   main:0x006fee74 Sub0000000008702e74
   main:0x006ecc70 Sub00000000086f0c70
   main:0x00d88e7c Sub0000000008d8ce7c
   main:0x00d890a4 Sub0000000008d8d0a4
   main:0x00d87ab8 Sub0000000008d8bab8
   main:0x008e6e50 Sub00000000088eae50
   main:0x0079cc98 Sub00000000087a0c98
   main:0x0079cccc Sub00000000087a0ccc
   main:0x0079cff4 Sub00000000087a0ff4
   main:0x006eabbc nnMain
   sdk:0x000a1d9c nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)())
   rtld:0x000000c0 Sub00000000080000c0

Raw Request Data:
00000000   01 00 10 00 03 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 01 00 00 00  7B 00 00 00 00 00 00 00   SFCI····{·······
00000020   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ················

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

Hardware Spec:
CPU: INTEL core i5 5200u
GPU: NVIDIA geforce gt920m
RAM SIZE: 8gb

note: known this games must connection joycon to computer.

Log file: 
[Ryujinx_2020-06-22_12-02-52.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4811124/Ryujinx_2020-06-22_12-02-52.log)

**Comment by EmulationFanatic** [comment]
We appreciate the attempt, but please submit all gamedb entries in the proper formatting. The new issue template includes all the formatting needed; please do not remove it. Be sure to fill out all fields including game update version.
