### ISSUE TITLE
Rune Factory 4 Special

### ISSUE THREAD

**Issue by BigGayLucy** [Ryujinx/Ryujinx-Games-List#1816]
#243 Rune Factory 4 Special (1.0.1)

#### This was on Ryujinx 1.0.4709 (System version 10.0.4)

I've not experienced anything game breaking. 0 crashes during my time
Besides a few minor, and one not so minor, issues, the game is entirely & comfortably playable now with Docked mode & Profiled Persistent Translation Cache on.

Previous performance issues with regards to audio stuttering & unrelated FPS lag have entirely disappeared with the exception of audio stutters returning on Rune Harvest days (Where all the crops with happy faces are flying), probably as a result of a performance drop (not reflected in my FPS atleast), like a larger use of a memory cache? Very minor audio stutters/popping I've found when entering an entirely new area for the first time. Probably a normal byproduct of the PPTC setting.

There is still an occasional double press bug making you press the A button twice rapidly on only one press. And the worst issue right now is the game is played completely sped up. This is a non-issue for non-reaction time based gameplay. I've found that using Cheat engine's speedhack and setting it to 0.67-0.7 speed is a good fix in the meantime. FPS limiting through other methods did not yield beneficial results. The game is also not exactly twice as fast as its regular counterpart.

All-in-all, very comfortable to play, already have 25 hours in it and most of the story finished.

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx-Games-List/issues/243#issuecomment-646925689_

https://github.com/Ryujinx/Ryujinx-Games-List/issues/243#issue-573840212

As mentioned above the sped up gameplay issue persists. Only a real issue with in-game traps and the fishing mini-game, speedhacking is a temporary fix.

One very possible issue is insane consecutive hit registration. Where one attack hits me and it registers a total of 8-16 times in half a second, nearly killing me instantly on occasion. I have not been able to confirm whether this is regular gameplay. I couldn't find regular gameplay recorded from a device that showcases this experience, so I am thinking it might be an emulator issue and possibly a byproduct of the generally sped up gameplay. As we know faster or slower emulated gameplay can potentially mess up a games' hit registration.

#### Screenshots :

Black screen during opening cutscene
![opening scene doesn't load](https://user-images.githubusercontent.com/67293857/85339990-86c83680-b4e5-11ea-9ebb-87dc6fe5da54.png)

Attempt to showcase hit registration issue
![Hitregissue](https://user-images.githubusercontent.com/67293857/85340458-6ea4e700-b4e6-11ea-858f-29486ca4162e.png)

Regular gameplay
![Screenshot_4](https://user-images.githubusercontent.com/67293857/85340550-9a27d180-b4e6-11ea-9125-bd5f5cc58faa.png)
![Screenshot_5](https://user-images.githubusercontent.com/67293857/85340552-9ac06800-b4e6-11ea-9462-9e1fec5bfbb6.png)
![Screenshot_6](https://user-images.githubusercontent.com/67293857/85340554-9b58fe80-b4e6-11ea-843a-447bb40f04d7.png)
![Screenshot_7](https://user-images.githubusercontent.com/67293857/85340555-9bf19500-b4e6-11ea-9fe9-47c0c5a4888e.png)

These are my settings with which I've achieved fruitful results.
![Screenshot_3](https://user-images.githubusercontent.com/67293857/85338445-998d3c00-b4e2-11ea-9d07-19f9b8ecb03b.png)
![Screenshot_1](https://user-images.githubusercontent.com/67293857/85338447-9a25d280-b4e2-11ea-9900-aad98c064791.png)
![Screenshot_2](https://user-images.githubusercontent.com/67293857/85338448-9a25d280-b4e2-11ea-8a0b-168f3667fa56.png)

**Comment by EmulationFanatic** [comment]
Please re-submit this test with Ignore Missing Services UNCHECKED. Then add it as a reply to https://github.com/Ryujinx/Ryujinx-Games-List/issues/243
