### ISSUE TITLE
Animal crossing new horizons 1.3.0 crash

### ISSUE THREAD

**Issue by Superpaul209** [Ryujinx/Ryujinx-Games-List#1929]
#### Current on `master` : 1.0.4796

When I launch my game with any firmware (mine is 10.0.4), it crashes when loading the save file. The only solution to fix the error is to check Ignore Missing Services and then the game will runs well again. The game update 1.3.0 is new so maybe its only my computer who doesnt run it without ignoring missing services.

#### Log file :
[Ryujinx_2020-07-03_10-08-33.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4868593/Ryujinx_2020-07-03_10-08-33.log)

Error given : 
Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Prepo.IPrepoService: 10105

**Comment by EmulationFanatic** [comment]
Please resubmit this as a reply to the original Animal Crossing gamedb entry. https://github.com/Ryujinx/Ryujinx-Games-List/issues/250
