### ISSUE TITLE
Animal Crossing New Horizons Segmentation fault 

### ISSUE THREAD

**Issue by AthenaCN** [Ryujinx/Ryujinx-Games-List#1975]
## Game Name

Animal Crossing New Horizons [NSP]

#### Current on `master` : 1.0.4864

Emulate aborts when created map 701
Segmentation fault (core dumped)

ServiceNv Create: Created map 701 with size 0x00004000!

#### Hardware Specs : 

Application Main: Ryujinx Version: 1.0.4864
00:00:00.065 | Application Main: Operating System: Linux 5.7.7-200.fc32.x86_64 #1 SMP Wed Jul 1 19:53:01 UTC 2020 (X64)
00:00:00.065 | Application Main: CPU: Intel(R) Core(TM) i7-3970X CPU @ 3.50GHz
00:00:00.065 | Application Main: Total RAM: 15948 MB
GPU: NVIDIA GTX TITAN 6GD5

#### Screenshots :

![Screenshot from 2020-07-08 23-08-55](https://user-images.githubusercontent.com/18543480/86936011-09045c00-c170-11ea-86f4-5319c8dc00be.png)

#### Log file :

[Ryujinx_2020-07-08_23-00-06.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4891470/Ryujinx_2020-07-08_23-00-06.log)

**Comment by EmulationFanatic** [comment]
Please post this instead as a reply on the [original animal crossing entry](https://github.com/Ryujinx/Ryujinx-Games-List/issues/250)
