### ISSUE TITLE
DORAEMON STORY OF SEASON CRASHED!

### ISSUE THREAD

**Issue by Sans907** [Ryujinx/Ryujinx-Games-List#2055]
#### Current on `master` : Commit Id *or* Build Version :  1.0.4921

Emulator crashed after animation cutscene (after the cutscene where Noby find the strange seed on the ground)
```
Last error returned.
e.g.: Unhandled Exception: System.NotImplementedException: /dev/nvhost-nvdec 40044801
```

#### Pull requests needed :

*Add needed PR links here.*

*(Optional section, remove it if unneeded)*

#### Outstanding Issues:

*Add issue links here.*

*Example: https://github.com/Ryujinx/Ryujinx/issues/xxx (xxx = number issue)*

*(Optional section, remove it if unneeded)*

#### Screenshots :

*Add screenshots here if the game rendering something.*

*(Optional section, remove it if unneeded)*

#### Log file :

*Add a link to the log file here.*
[logfile.txt](https://github.com/Ryujinx/Ryujinx-Games-List/files/4914704/logfile.txt)

*(Optional section, remove it if unneeded)*

**Comment by EmulationFanatic** [comment]
Please follow existing gamedb templates, and paste it as a reply in a game's entry if it already exists.

**Comment by Sans907** [comment]
> Please follow existing gamedb templates, and paste it as a reply in a game's entry if it already exists.

What do you mean? I'm really sorry if I'm not following this since this is my first time posting here. And I thought I already followed the template.

**Comment by EmulationFanatic** [comment]
Doraemon already exists in this list and was tested just 8 days ago . Submitting a newer test should be done as a reply to that entry, not a brand new one. Look at the formatting from other tests to see what they should look like and delete any sections that are unused. Make sure you have a solid test bed before submitting results i.e. a somewhat current generation CPU, at least 8GB RAM, an NVIDIA GPU, etc.

**Comment by Sans907** [comment]
Oh okay fine. Sorry it's my first time here, and I encountered the issue so I think I should have let you know that something is wrong. I don't know what you do since it seems you can make it work properly in this emulator while mine always crashed after that cutscene also I didn't modified anything inside the emulator.
