### ISSUE TITLE
Pokemon Sword Blue Screen Only but with sound

### ISSUE THREAD

**Issue by ToChoPals** [Ryujinx/Ryujinx-Games-List#212]
#### Current on `master` : What is this?

* Commit Id *or* Build Version : *(e.g. 0a41a3ff or 1.0.1952)* Can't find

*Describe the current game state here.*
Blue Screen Only but with sound and possibly working in background because I was hearding sound

#### Log file :

*Add a link to the log file here.*
[Ryujinx.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/3963938/Ryujinx.log)

**Comment by AcK77** [comment]
Thanks for the report but you sadly don’t know how to follow an issue template and the state you reported isn’t the right one. In that case I close this issue. 
Feel free to ask for help in our support channel on our Discord server.
Thanks.
