### ISSUE TITLE
Phantom Breaker: Battle Grounds Over Drive

### ISSUE THREAD

**Issue by Trevor-Z** [Ryujinx/Ryujinx-Games-List#2147]
### Phantom Breaker: Battle Grounds Over Drive

**Game Update Version:** 1.0.0

**Current on `master`:** 1.0.5034

Until recently, the game crashed on load. I believe it started booting at some point after version 1.0.4952. Now, it goes ingame. Sound and controls work.

All graphics are flipped in both x and y axis. 
The stage select screen is corrupted. 
During actual play, the backgrounds seem to be missing, and the graphics are very dark until you pause the game once, when the brightness return to normal from then on.
Several sprites on the UI and animation frames for the characters are corrupted.

**Hardware Specs :** 

**CPU:** i5 8500

**GPU:** NVIDIA RTX 2060

**RAM:** 16GB

![Annotation 2020-07-25 210108](https://user-images.githubusercontent.com/13950948/88468618-a4116b80-cebc-11ea-9067-dac826a14b74.png)

![Annotation 2020-07-25 210120](https://user-images.githubusercontent.com/13950948/88468619-aa9fe300-cebc-11ea-9130-afc4191ac384.png)

![Annotation 2020-07-25 210048](https://user-images.githubusercontent.com/13950948/88468622-af649700-cebc-11ea-9056-a77b88ae95cc.png)

**Comment by EmulationFanatic** [comment]
Please resubmit this game test (edit > copy/paste) as a reply to the existing Phantom Breaker: Battle Grounds Over Drive entry. Thanks!

**Comment by Trevor-Z** [comment]
Oops, sorry. I could swear I had done a search with no results before posting. Must have misspelled the title or something.
