### ISSUE TITLE
animal crossing new horizons(GPU)

### ISSUE THREAD

**Issue by jeong-jong-il** [Ryujinx/Ryujinx-Games-List#2153]
##### RAM: 16GB

================================
It's a problem playing the game.

The water color is black.  ㅠ.ㅠ
=================================

#### Screenshots :
![black](https://user-images.githubusercontent.com/68798018/88470165-078ab000-cf34-11ea-8265-33f59ca5298b.jpg)

**Comment by EmulationFanatic** [comment]
Please come to Discord for support. This is a game compatibility list.
