### ISSUE TITLE
Super Mario Odyssey Level Crach

### ISSUE THREAD

**Issue by arudamartineti** [Ryujinx/Ryujinx-Games-List#2246]
#### Current on `master` :  Ryujinx Version: 1.0.5126

Hi. My son is playing Super Mario Odyssey but at the level **Direct to the Cauldron** (Directo al Caldero) when the meat falls into the pot Mario dies without being able to do anything else. Attached log and capture. I would appreciate any help.

```
No error returned. The game only allows you to move the camera. 
```

#### Screenshots :

![Mario Odissey](https://user-images.githubusercontent.com/12159728/89416031-b2505a80-d6fa-11ea-8a1c-93308a8a6848.png)

#### Log file :

[LogFile.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/5028556/LogFile.zip)

**Comment by EmulationFanatic** [comment]
Please come to Discord for support as this compatibility list is for game testing only.
