### ISSUE TITLE
Luigi's Mansion 3 When going to the B2 floor, in the elevator, the ryujinx simulator crashes

### ISSUE THREAD

**Issue by hefang0918** [Ryujinx/Ryujinx-Games-List#2307]
Luigi's Mansion 3
Game Update Version : . 1.0.0

ryujinx   Version : 1.0.5000~1.0.5155

When going to the B2 floor, in the elevator, the ryujinx Emulator crash

Last error returned.
The console code is also at rest

CPU: I7-4790
GPU: NVIDIA GTX 1060  6G
RAM:  16GB

![001](https://user-images.githubusercontent.com/69452926/89762943-0c4e8700-db24-11ea-861d-61e5e54c2fd8.jpg)

**Comment by EmulationFanatic** [comment]
Please follow the template format, and add this information to the existing Luigi's Mansion 3 entry.
