### ISSUE TITLE
Animal crossing Crash

### ISSUE THREAD

**Issue by sadako007** [Ryujinx/Ryujinx-Games-List#2310]
animal crossing new horizons

(1.4.1)
[Ryujinx_2020-08-10_16-56-28.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5051198/Ryujinx_2020-08-10_16-56-28.log)

**Comment by EmulationFanatic** [comment]
Please come to Discord for support. This is a game compatibility database.
