### ISSUE TITLE
Xenoblade Chronicles 2: Torna - The Golden Country

### ISSUE THREAD

**Issue by JobLeite** [Ryujinx/Ryujinx-Games-List#2330]
#### Build Version : *(1.0.5155)*

*game closes when clicking New Game*

```
Last error returned.
e.g.: Unhandled Exception: System.NotImplementedException: /dev/nvhost-nvdec 40044801
```

##### RAM: [*(24GB)*]([url](url
[Ryujinx_2020-08-12_00-39-08.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5060471/Ryujinx_2020-08-12_00-39-08.log)
))

#### Pull requests needed :

*Add needed PR links here.*

*(Optional section, remove it if unneeded)*

#### Outstanding Issues:

*Add issue links here.*

*Example: https://github.com/Ryujinx/Ryujinx/issues/xxx (xxx = number issue)*

*(Optional section, remove it if unneeded)*

#### Screenshots :

*Add screenshots here if the game rendering something.*

*(Optional section, remove it if unneeded)*

#### Log file :

*Add a link to the log file here.*

*(Optional section, remove it if unneeded)*

**Comment by EmulationFanatic** [comment]
Please follow the full template format and submit this as a reply on the original entry for this game.
