### ISSUE TITLE
Mega39s crash when start in to game

### ISSUE THREAD

**Issue by Mega39s** [Ryujinx/Ryujinx-Games-List#236]
#### Current on `master` :

* Commit Id *or* Build Version : *(e.g. 0a41a3ff or 1.0.1952)*
 V.ryujinx-1.0.3756-win_x64
*Describe the current game state here.*

```
Last error returned.
e.g.: Unhandled Exception: System.NotImplementedException: /dev/nvhost-nvdec 40044801
```

#### Pull requests needed :

*Add needed PR links here.*

*(Optional section, remove it if unneeded)*

#### Screenshots :

*Add screenshots here if the game rendering something.*

*(Optional section, remove it if unneeded)*

#### Outstanding Issues:

*Add issue links here.*

*Example: https://github.com/Ryujinx/Ryujinx/issues/184-185

*(Optional section, remove it if unneeded)*

#### Log file 

*Add a link to the log file here.*
https://drive.google.com/open?id=1fxHBaGrtrlMEOaA30h192L4zgFuNxIeN
*(Optional section, remove it if unneeded)*

**Comment by Thog** [comment]
close in favor of #237
