### ISSUE TITLE
Feature request Add possiblity to load games from Windows Network share

### ISSUE THREAD

**Issue by ruthan** [Ryujinx/Ryujinx-Games-List#238]
Hello,
i tried present build, but when i try to load game, in left menu, i dont need possiblity to load games form network patch.
  I like it for share my images across more computers, most of emulators supports, it nice space safer.. especially on notebooks.

**Comment by Thog** [comment]
This is the game list tracker, can you open this issue on the main repository https://github.com/Ryujinx/Ryujinx please?
