### ISSUE TITLE
Fire Emblem: Three Houses

### ISSUE THREAD

**Issue by zerorise** [Ryujinx/Ryujinx-Games-List#2526]
## Game Name
Fire Emblem Three Houses
#### Game Update Version : *(e.g. 1.0.0 or 1.1.3)*
v1.2.0
#### Current on `master` : Commit Id *or* Build Version : *(e.g. 0a41a3ff or 1.0.1952)*
v1.0.5327
*Describe the current game state here.*
Runs 9/10 times.
Audio works correctly 9/10 times with a little shudder sometimes.
when in Monastery it fps is around 10-20 most of the time, 30 fps game. Mostly lower in higher intense renderings and big field of vision. 
Songstress class, skill sing seems to cause instant crash 100% of the times it seems. possible shader issue. 
Some artifact in actual game play, but still playable.
I managed to finish the game start to finish with small crashes randomly. 
also full cutsence support
```
Last error returned.
e.g.: Unhandled Exception: System.NotImplementedException: /dev/nvhost-nvdec 40044801
```
00:01:43.427 |W| GUI.RenderLoop Gpu Log: Shader translator: Invalid instruction at 0x002030 (0xEFA010000A07060B).
00:01:43.427 |W| GUI.RenderLoop Gpu Log: Shader translator: Invalid instruction at 0x002038 (0xEFA020000A47060C).
00:01:43.427 |W| GUI.RenderLoop Gpu Log: Shader translator: Invalid instruction at 0x002048 (0xEFA030000A87060D).
00:01:43.844 |W| GUI.RenderLoop Gpu Log: Shader translator: Invalid instruction at 0x002088 (0xEFA010000A07060B).
00:01:43.844 |W| GUI.RenderLoop Gpu Log: Shader translator: Invalid instruction at 0x002090 (0xEFA020000A47060D).
00:01:43.844 |W| GUI.RenderLoop Gpu Log: Shader translator: Invalid instruction at 0x002098 (0xEFA030000A87060E).

##### RAM: *(e.g. 16GB)*
00:00:00.018 |N| Application PrintSystemInfo: Ryujinx Version: 1.0.5327
00:00:01.361 |N| Application PrintSystemInfo: Operating System: Microsoft Windows 10.0.19041 (X64)
00:00:01.361 |N| Application PrintSystemInfo: CPU: AMD Ryzen 5 3600 6-Core Processor
00:00:01.361 |N| Application PrintSystemInfo: Total RAM: 32718 MB
00:00:01.363 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.439 |I| Hid Configure: Configured Controller ProController to Player1
00:00:00.524 |N| Application LoadApplication: Using Firmware Version: 10.0.3

#### Pull requests needed :

*Add needed PR links here.*

*(Optional section, remove it if unneeded)*

#### Outstanding Issues:

*Add issue links here.*

*Example: https://github.com/Ryujinx/Ryujinx/issues/xxx (xxx = number issue)*

*(Optional section, remove it if unneeded)*

#### Screenshots :

*Add screenshots here if the game rendering something.*

*(Optional section, remove it if unneeded)*

#### Log file :

*Add a link to the log file here.*

*(Optional section, remove it if unneeded)*

**Comment by gdkchan** [comment]
Thanks for the report, but we already have a issue for this game (#230), please post it there.

**Comment by EmulationFanatic** [comment]
Please add screenshots, as well as any pertinent log files from any crashes. Add the as a reply to the [existing entry](https://github.com/Ryujinx/Ryujinx-Games-List/issues/230) for this game.
