### ISSUE TITLE
Tetris99 - Rendering problems

### ISSUE THREAD

**Issue by JonmuxuPvP** [Ryujinx/Ryujinx-Games-List#2527]
Game: Tetris 99

Game Update Version : v2.1.0 (DLCs included)

Current on `master` : 1.0.5346

The game functions properly in the menu, but trying to play a single game is impossible due to missing textures and rendering errors (Happens in any game mode: Marathon, CPU Battle, 2P Share Battle...). The background, targeting lines, preview pieces, hold piece, enemy's pieces, incoming garbage and badges aren't rendered properly.

Last error returned:

The console doesn't seem to display any errors, even after placing pieces or switching target modes. I'll provide the log below just in case I missed something.

Hardware Specs : 

CPU: AMD Ryzen 5 1600 Six-Core Processor
GPU: NVIDIA GeForce GTX 1060 6GB
RAM: 16GB

Screenshots :

This is how the game looks like while playing on Ryujinx:

https://cdn.discordapp.com/attachments/285139998091640833/755768137340944484/unknown.png

And this is how it should look like:

https://cdn.discordapp.com/attachments/285139998091640833/755769328887922748/unknown.png

Log file :

https://drive.google.com/file/d/1W9jBvq3hJPb9ANjv_LjjKjlY6FJtLOpG/view?usp=sharing

**Comment by SeraUX** [comment]
Thanks for the report, but we already have an issue open for that game #150
please submit the report there
