### ISSUE TITLE
audio desync

### ISSUE THREAD

**Issue by xxmoon** [Ryujinx/Ryujinx-Games-List#2528]
## Game Name
Monster Hunter Generations Ultimate
#### Game Update Version : *(e.g. 1.0.0 or 1.1.3)*
1.4.0
#### Current on `master` : Commit Id *or* Build Version : *(e.g. 0a41a3ff or 1.0.1952)*
1.0.0-ldn1
*Describe the current game state here.*
The game runs at fullspeed but the audio gradually falls behind the video, eventually becoming like 3-4 full seconds delayed.
```
Last error returned.
e.g.: Unhandled Exception: System.NotImplementedException: /dev/nvhost-nvdec 40044801
```

##### CPU: *(e.g. i7-6700)*
R7 2700x
##### GPU: *(e.g. NVIDIA RTX 2070)*
NVIDIA RTX 2070
##### RAM: *(e.g. 16GB)*
32GB DDR4

**Comment by GamerzHell9137** [comment]
https://github.com/Ryujinx/Ryujinx-Games-List/issues/511

**Comment by AcK77** [comment]
Superseded by #511
