### ISSUE TITLE
BU$TAFELLOWS

### ISSUE THREAD

**Issue by Kaizen-mini** [Ryujinx/Ryujinx-Games-List#2532]
**Game Name :** BU$TAFELLOWS

**Game Update Version :** 1.1.1

**Current on `master` : Commit Id *or* Build Version :** 1.0.5391

Game loads, plays the prologue then crashes right after showing the Opening video (the OP itself plays fine).

**Hardware Specs :** 

CPU: i5-6600K
GPU: NVIDIA GeForce GT 730
RAM: 16GB

**Screenshots :**
![01](https://user-images.githubusercontent.com/71459954/93708742-da890100-fb62-11ea-954a-f8b88f5244e7.jpg)
![02](https://user-images.githubusercontent.com/71459954/93708743-de1c8800-fb62-11ea-9a3d-c8ca131229da.jpg)
![04](https://user-images.githubusercontent.com/71459954/93708745-e2e13c00-fb62-11ea-9ca0-4ff201c70378.jpg)
![03](https://user-images.githubusercontent.com/71459954/93708748-e83e8680-fb62-11ea-8b30-8400b80a3467.jpg)

**Log file :**
[Ryujinx_2020-09-20_16-41-20.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5251428/Ryujinx_2020-09-20_16-41-20.log)

**Comment by SeraUX** [comment]
thanks for the report, but there is alredy an issue open for the game(#2018)
