### ISSUE TITLE
graphic bug

### ISSUE THREAD

**Issue by Lulbit8** [Ryujinx/Ryujinx-Games-List#2820]
#### Game Update Version : 1:00

my current emulator version 1.0.5584

*Describe the current game state here.*
since i downloaded the game the game has a graphic bug 
fruits glitch and i see that textures become black
![Cattura](https://user-images.githubusercontent.com/73791936/97809614-3b315080-1c6e-11eb-86c2-6f77f2c8e2d6.PNG)
![Cattura2](https://user-images.githubusercontent.com/73791936/97809617-3ec4d780-1c6e-11eb-87a4-45f153530029.PNG)

```
Last error returned.
e.g.: Unhandled Exception: System.NotImplementedException: /dev/nvhost-nvdec 40044801
```

#### Pull requests needed :

*Add needed PR links here.*

PS sound are like ocvhjifghidxcvjitfcvbhuydxc

**Comment by EmulationFanatic** [comment]
This is a game compatibility database and there is already an entry for Animal Crossing: New Horizons. Your laptop is not going to do the job based on the 4GB of RAM alone (8GB is the minimum recommended amount).

**Comment by Lulbit8** [comment]
oh thank you i should buy a switch but OK im going to create mi animal crossing game bc yes im a devleplover (a visual scripting dev but) NEVER MIND

**Comment by Lulbit8** [comment]
PS im not eng sorry for bad eng
