### ISSUE TITLE
Clipnote Studio(running under Undertale) - 1.0.9

### ISSUE THREAD

**Issue by Hypno7767** [Ryujinx/Ryujinx-Games-List#2831]
#### Current on `master` : 1.0.5639

The game crashes when the game.win patch is made. Undertale works fine without the game patch but Clipnote Studio crashes with no signs of life.

```
00:03:33.397 |E| GUI.RenderLoop Application : Unhandled exception caught: System.IndexOutOfRangeException: Index was outside the bounds of the array.
```

#### Log file :
[Ryujinx_2020-10-22_19-44-15.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5505846/Ryujinx_2020-10-22_19-44-15.log)

**Comment by EmulationFanatic** [comment]
Cleaned up and labeled. In the future please remove any unused text/unused sections. Thanks for the test!

**Comment by EmulationFanatic** [comment]
Cannot verify existence of this software for Switch. Closing.
