### ISSUE TITLE
Hyrule Warriors: Age of Calamity

### ISSUE THREAD

**Issue by EliasM108** [Ryujinx/Ryujinx-Games-List#2861]
#### Current on `master` :  Build Version : 1.0.5755

The game plays poorly untill it caches all the necessary shaders. All cutscenes begin out of sync with the audio but later it catches up. There are missing textures (for example the chasing guardian) and other texture glitches like when getting into some ponds. Audio, sometimes, becomes distorted during gameplay and cutscenes.

#### Screenshots :

![0](https://user-images.githubusercontent.com/51413997/99582359-aeff8700-29ea-11eb-8e46-87e4ea66c102.png)

![1](https://user-images.githubusercontent.com/51413997/99582377-b2930e00-29ea-11eb-8602-8d7b50cd60c8.png)

![2](https://user-images.githubusercontent.com/51413997/99582380-b32ba480-29ea-11eb-90c2-3126e8f421f4.png)

#### Log file :

[Ryujinx_2020-11-18_21-13-09.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5562471/Ryujinx_2020-11-18_21-13-09.log)

**Comment by EmulationFanatic** [comment]
You're two days early. We do not allow pirated games in the compatibility list. If you received this game early as a reviewer, feel free to reach out with proof and I'll reopen the issue.

**Comment by zarroyo753** [comment]
Tested it out on a dump of a legal copy. I'm assuming you guys don't want a duplicate issue, so I'll just reply to this one. 

#### Game Update Version : *1.0.1*

#### Current on `master` : Build Version : *1.0.5783*

*Game seems playable from the few hours that I've put into it. Regardless of rendering resolution, it seems to stay in the 20-30fps range when stable, though there are some hitches that occur occasionally. Loading times feel longer than on my Switch, even with an SSD. When caching new shaders, the game drops greatly in performance, which occurs during both gameplay and at the beginning of some rendered cutscenes. Audio distortion is common during shader caching, slowly goes away as performance stabilizes. There are some texture glitches that I've noticed, usually small, though noticeable. The cutscene for the first Mipha level has broken lighting, for some reason. *

#### Hardware Specs : 

##### CPU: *i7-8700K @ 5GHz*
##### GPU: *RTX 2070 Super*
##### RAM: *32GB @ 3600MHz*

#### Screenshots :
![1](https://user-images.githubusercontent.com/34071477/99870213-ee6ad680-2b96-11eb-955d-951b069da559.png)
![2](https://user-images.githubusercontent.com/34071477/99870214-f0349a00-2b96-11eb-8732-05893abbbb3c.png)

**Comment by EmulationFanatic** [comment]
@zarroyo753 please post it as a new issue. I will make sure it is labeled appropriately. Thanks!
