### ISSUE TITLE
Paper Mario The Origami King

### ISSUE THREAD

**Issue by exoduscl** [Ryujinx/Ryujinx-Games-List#2863]
Paper Mario The Origami King

Game Update Version :  1.0.0

Current on `master` : 1.0.5816

Game runs at 30FPS with good sound, but close to the ending I encountered a game breaking bug.

#### Hardware Specs : 
CPU: i7-10700 (non K ver.)
GPU: NVIDIA RTX 2060
RAM: 16GB

**Outstanding Issues:**

I just found a game breaking bug where an action does not activate and you cannot advance in the game. You can see in the following video how nothing happens when entering the spring (it should regenerate your energy and activate a conversation that allows you to keep on advancing):

https://youtu.be/tI0HFdU2Xdw

I transfered the save to YUZU in order to see if the same happened and as I thought, the spring regenerated Mario's energy and I was able to advance:

https://youtu.be/xsGSdTTdvcY

**I attach the save that leaves you right before the problem occurs**
[Origami king save with game breaking bug in Riujinx.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/5599430/Origami.king.save.with.game.breaking.bug.in.Riujinx.zip)

PS: sorry for any mistake, first time posting a bug in here and English is not my first language, please let me know if you need anything else.

**Comment by SeraUQ** [comment]
hey, thx for the report, but there is already an issue open for the game(#2138)
please add the report as a comment in that issue
