### ISSUE TITLE
Animal Crossing：使用 1.0.5837 在 ryujinx 執行遊戲畫面時及跳出

### ISSUE THREAD

**Issue by PythonMaChi** [Ryujinx/Ryujinx-Games-List#2891]
![Ry_Bug01](https://user-images.githubusercontent.com/73590132/100605491-f539dc00-3342-11eb-826c-639e5232420a.jpg)
#### Current on `master` : Commit Id *or* Build Version : *(e.g. 0a41a3ff or 1.0.1952)*

*Describe the current game state here.*

```
Last error returned.
e.g.: Unhandled Exception: System.NotImplementedException: /dev/nvhost-nvdec 40044801
```

#### Pull requests needed :

*Add needed PR links here.*

*(Optional section, remove it if unneeded)*

#### Outstanding Issues:

*Add issue links here.*

*Example: https://github.com/Ryujinx/Ryujinx/issues/xxx (xxx = number issue)*

*(Optional section, remove it if unneeded)*

#### Screenshots :

*Add screenshots here if the game rendering something.*

*(Optional section, remove it if unneeded)*

#### Log file :

*Add a link to the log file here.*

*(Optional section, remove it if unneeded)*

**Comment by SeraUQ** [comment]
please come to the discord for support(https://discord.gg/ryujinx), this is the compatibility database
