### ISSUE TITLE
Ring Fit Adventure - No option menu

### ISSUE THREAD

**Issue by lphzac** [Ryujinx/Ryujinx-Games-List#2919]
#### Current on `master` : Commit Id *or* Build Version : master 1.0.5960

Noticed that Ryujinx has motion control implemented, wanted to test out the game. 
The game was successfully loaded. After passing the first joycon intro, there is no menu/option coming up while the game keeps running. 

![image](https://user-images.githubusercontent.com/75613364/101339433-60daf680-38b9-11eb-9917-11407fa3c18e.png)

```

#### Hardware Specs : 

##### CPU: i7-7700k
##### GPU: NVIDIA GTX1060 6GB
##### RAM: 16GB


#### Outstanding Issues:

Found similar issue. At at that time, there is no motion control.
https://github.com/Ryujinx/Ryujinx-Games-List/issues/261

**Comment by SeraUQ** [comment]
there is already an issue open for this game(#261)
please add your report as a comment on that issue
