### ISSUE TITLE
Corrupted items Animal Crossing New Horizons

### ISSUE THREAD

**Issue by Sbrockat** [Ryujinx/Ryujinx-Games-List#2920]
In the home wardrobe and in the Able Sisters shop a lot of images are corrupted (picture below).

![ACNH_screen](https://user-images.githubusercontent.com/70136156/101344195-661e4e00-3885-11eb-9754-1c2c10c591dd.PNG)

Environment:

Ryujinx version: 1.0.5942
Game version: ACNH 1.6.0

System Specs:
OS: Windows 10
CPU: ryzen5 3600
GPU: ATI rx570
RAM: 16GB

Thanks in advance for any help!

**Comment by SeraUQ** [comment]
there is already an issue open for this game(#250)
please add this report as an comment on that issue

**Comment by Sbrockat** [comment]
Thanks. Apologies
