### ISSUE TITLE
Animal Crossing: New Horizons Island Transfer Tool 

### ISSUE THREAD

**Issue by SnowtheVulpix** [Ryujinx/Ryujinx-Games-List#2922]
#### Build Version : 1.0.0-ldn1

The Game is perfect no issue running it at all. Currently unknown if works to transfer. It currently can't connect to a real Nintendo Switch as ldn cannot do that yet.

##### RAM: 8 GB

**Comment by EmulationFanatic** [comment]
This is not a discrete game. Please add this comment to the original game entry if you wish.
