### ISSUE TITLE
moon

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2937]
#### Current on `master` : 1.0.6006

Game loads and plays perfectly.

#### Screenshots :

![2020-12-10 12_02_22-Ryujinx 1 0 6006 - moon v1 1 1 (0100E1800EFCE000) (64-bit)](https://user-images.githubusercontent.com/62343878/101819070-feb10a00-3ae1-11eb-9bae-cfcb658cb72c.png)
![2020-12-10 12_02_26-Ryujinx 1 0 6006 - moon v1 1 1 (0100E1800EFCE000) (64-bit)](https://user-images.githubusercontent.com/62343878/101819075-007acd80-3ae2-11eb-8aa4-611eb608e492.png)
![2020-12-10 12_02_33-Ryujinx 1 0 6006 - moon v1 1 1 (0100E1800EFCE000) (64-bit)](https://user-images.githubusercontent.com/62343878/101819078-007acd80-3ae2-11eb-8830-3164d5049af8.png)
![2020-12-10 12_03_12-Ryujinx 1 0 6006 - moon v1 1 1 (0100E1800EFCE000) (64-bit)](https://user-images.githubusercontent.com/62343878/101819086-0375be00-3ae2-11eb-9fc1-f1517ffb18c3.png)
![2020-12-10 12_03_22-Ryujinx 1 0 6006 - moon v1 1 1 (0100E1800EFCE000) (64-bit)](https://user-images.githubusercontent.com/62343878/101819090-040e5480-3ae2-11eb-85b6-04666015c700.png)
![2020-12-10 12_03_59-Ryujinx 1 0 6006 - moon v1 1 1 (0100E1800EFCE000) (64-bit)](https://user-images.githubusercontent.com/62343878/101819094-05d81800-3ae2-11eb-97ab-07d9a111d8c5.png)
![2020-12-10 12_04_44-Ryujinx 1 0 6006 - moon v1 1 1 (0100E1800EFCE000) (64-bit)](https://user-images.githubusercontent.com/62343878/101819101-07094500-3ae2-11eb-99c2-801fb8899dc1.png)
![2020-12-10 12_04_50-Ryujinx 1 0 6006 - moon v1 1 1 (0100E1800EFCE000) (64-bit)](https://user-images.githubusercontent.com/62343878/101819111-0a043580-3ae2-11eb-964f-23d50a7d6dd3.png)
![2020-12-10 12_05_18-Ryujinx 1 0 6006 - moon v1 1 1 (0100E1800EFCE000) (64-bit)](https://user-images.githubusercontent.com/62343878/101819114-0b356280-3ae2-11eb-8e11-f79f9fa351a2.png)
![2020-12-10 12_08_23-Ryujinx 1 0 6006 - moon v1 1 1 (0100E1800EFCE000) (64-bit)](https://user-images.githubusercontent.com/62343878/101819121-0c668f80-3ae2-11eb-917b-40c496304e30.png)
![2020-12-10 12_08_53-Ryujinx 1 0 6006 - moon v1 1 1 (0100E1800EFCE000) (64-bit)](https://user-images.githubusercontent.com/62343878/101819129-0e305300-3ae2-11eb-9a55-69c87cf22a5b.png)
![2020-12-10 12_09_02-Ryujinx 1 0 6006 - moon v1 1 1 (0100E1800EFCE000) (64-bit)](https://user-images.githubusercontent.com/62343878/101819143-11c3da00-3ae2-11eb-9fec-6706a9e8798a.png)
![2020-12-10 12_18_30-Ryujinx 1 0 6006 - moon v1 1 1 (0100E1800EFCE000) (64-bit)](https://user-images.githubusercontent.com/62343878/101819155-138d9d80-3ae2-11eb-80f1-0e42d9ff3a5e.png)
![2020-12-10 12_18_46-Ryujinx 1 0 6006 - moon v1 1 1 (0100E1800EFCE000) (64-bit)](https://user-images.githubusercontent.com/62343878/101819170-17212480-3ae2-11eb-8fe2-193f97f35cd9.png)

#### Log file :

[moon.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5675131/moon.log)

**Comment by Cronos-0** [comment]
This issue is open : https://github.com/Ryujinx/Ryujinx-Games-List/issues/2462

**Comment by EmulationFanatic** [comment]
Thanks! I added in the new test data to the existing entry.
