### ISSUE TITLE
BATTOJUTSU

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#3175]
#### Current on `master` : 1.0.6119

Game loads and plays at a high FPS.

#### Screenshots :

![2020-12-17 09_22_51-Ryujinx 1 0 6119 - BATTOJUTSU v1 0 0 (01006EE00E67C000) (64-bit)](https://user-images.githubusercontent.com/62343878/102514869-44be1e80-404a-11eb-8258-cb9be23f248a.png)
![2020-12-17 09_22_56-Ryujinx 1 0 6119 - BATTOJUTSU v1 0 0 (01006EE00E67C000) (64-bit)](https://user-images.githubusercontent.com/62343878/102514874-4556b500-404a-11eb-8cce-cebedd3cd43e.png)
![2020-12-17 09_23_07-Ryujinx 1 0 6119 - BATTOJUTSU v1 0 0 (01006EE00E67C000) (64-bit)](https://user-images.githubusercontent.com/62343878/102514877-45ef4b80-404a-11eb-826a-3cc8980c03af.png)
![2020-12-17 09_23_16-Ryujinx 1 0 6119 - BATTOJUTSU v1 0 0 (01006EE00E67C000) (64-bit)](https://user-images.githubusercontent.com/62343878/102514883-4851a580-404a-11eb-8504-8e0eac4be2e5.png)
![2020-12-17 09_24_47-Ryujinx 1 0 6119 - BATTOJUTSU v1 0 0 (01006EE00E67C000) (64-bit)](https://user-images.githubusercontent.com/62343878/102514891-4ab3ff80-404a-11eb-9723-65fc8732815e.png)
![2020-12-17 09_24_51-Ryujinx 1 0 6119 - BATTOJUTSU v1 0 0 (01006EE00E67C000) (64-bit)](https://user-images.githubusercontent.com/62343878/102514897-4c7dc300-404a-11eb-956c-e4f7598a5ad1.png)
![2020-12-17 09_24_55-Ryujinx 1 0 6119 - BATTOJUTSU v1 0 0 (01006EE00E67C000) (64-bit)](https://user-images.githubusercontent.com/62343878/102514905-4ee01d00-404a-11eb-8189-561ce1234ce7.png)
![2020-12-17 09_26_04-Ryujinx 1 0 6119 - BATTOJUTSU v1 0 0 (01006EE00E67C000) (64-bit)](https://user-images.githubusercontent.com/62343878/102514910-50a9e080-404a-11eb-973d-18618ee1b660.png)
![2020-12-17 09_27_25-Ryujinx 1 0 6119 - BATTOJUTSU v1 0 0 (01006EE00E67C000) (64-bit)](https://user-images.githubusercontent.com/62343878/102514918-530c3a80-404a-11eb-8349-d5fd7a20ed96.png)
![2020-12-17 09_27_30-Ryujinx 1 0 6119 - BATTOJUTSU v1 0 0 (01006EE00E67C000) (64-bit)](https://user-images.githubusercontent.com/62343878/102514936-57385800-404a-11eb-9d9d-ad1b9eba4640.png)
![2020-12-17 09_27_40-Ryujinx 1 0 6119 - BATTOJUTSU v1 0 0 (01006EE00E67C000) (64-bit)](https://user-images.githubusercontent.com/62343878/102514946-5acbdf00-404a-11eb-85e9-0657ef95b273.png)

#### Log file :

[BATTOJUTSU.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/5710798/BATTOJUTSU.zip)

**Comment by Cronos-0** [comment]
duplicate of https://github.com/Ryujinx/Ryujinx-Games-List/issues/2516

**Comment by EmulationFanatic** [comment]
Closing as duplicate.
