### ISSUE TITLE
Ryuuou no Oshigoto! - 010033100EE12000

### ISSUE THREAD

**Issue by ekfacile** [Ryujinx/Ryujinx-Games-List#3198]
#### Current on `master` : **1.0.6127**

Boot success(?) However, fatal error and crash immediately (keep black screen).

**Last error :** Was not logged.

![fatal_error](https://user-images.githubusercontent.com/62389564/102580574-28051200-4142-11eb-8bce-9eb52f902a28.png)

#### Log file :

[ryuuou_no_oshigoto_Ryujinx_1.0.6127.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5713969/ryuuou_no_oshigoto_Ryujinx_1.0.6127.log)

**Comment by MutantAura** [comment]
Closing in favour of #3870 as while it is newer it's more detailed and up to date.
