### ISSUE TITLE
Luigi's Mansion 3 Crash no load

### ISSUE THREAD

**Issue by zerr10** [Ryujinx/Ryujinx-Games-List#3230]
Luigi's Mansion 3

Luigis Mansion 3[0100DCA0064A6000]+[v1.2.0][v131072]

ryujinx-1.0.6200-win_x64

emulator just closed nothing error . 

the emulator closes immediately after opening the game

i7 6700 4x3.4 Ghz 

8GB RAM 2133Mhz Dual

GTX 1070 8GB

Windows 10 Pro version 20H2 19042.508

**Comment by zerr10** [comment]
it seems that the problem is the enable shader cache option when it is disabled the game starts normally but when enabled the emulator will close.

**Comment by EmulationFanatic** [comment]
This is a game database, and Luigi's Mansion 3 already has an existing entry. Closing as duplicate.

P.S. @zerr10 purge your shader cache and then you can enable it again.
