### ISSUE TITLE
Animal Crossing Page Stuck

### ISSUE THREAD

**Issue by Dreamer77777** [Ryujinx/Ryujinx-Games-List#3240]
## Game Name
Animal Crossing New Horizons
#### Game Update Version : *(e.g. 1.0.0 or 1.1.3)*
1.1.0
#### Current on `master` : Commit Id *or* Build Version : *(e.g. 0a41a3ff or 1.0.1952)*

*Describe the current game state here.*

```
Last error returned.
e.g.: Unhandled Exception: System.NotImplementedException: /dev/nvhost-nvdec 40044801
```

#### Pull requests needed :

*Add needed PR links here.*

*(Optional section, remove it if unneeded)*

#### Outstanding Issues:

*Add issue links here.*

*Example: https://github.com/Ryujinx/Ryujinx/issues/xxx (xxx = number issue)*

*(Optional section, remove it if unneeded)*

#### Screenshots :

*Add screensho
![Screenshot (165)](https://user-images.githubusercontent.com/77149102/104004637-edd9de00-51de-11eb-98ec-1726e412e27f.png)
ts here if the game rendering something.*

*(Optional section, remove it if unneeded)*

#### Log file :

*Add a link to the log file here.*

*(Optional section, remove it if unneeded)*

**Comment by Dreamer77777** [comment]
I tried to start my game and it got stuck on this page. I couldnt press the ok button. I dont even know what it means

**Comment by Dreamer77777** [comment]
Can someone help or explain what is happening???

**Comment by EmulationFanatic** [comment]
Please come to Discord for support. This is a game compatibility list, not a support forum.
