### ISSUE TITLE
Animal Crossing 1.0.0 - Ryujinx crashes on load the game

### ISSUE THREAD

**Issue by Callm3Star** [Ryujinx/Ryujinx-Games-List#3241]
RYUJJINX HAS STOPPED WORKING - Windows say and close, even running as ADMIN.

#### Pull requests needed :
Now I tried to use the multiplayer but even the normal Ryujinx DOESN´T WORK even with my save or an empty save and I try to put a DLC and says that this DLC it´s not from ACNH but it is!!! But the Ryujinx doesn´t recognise any DLC only the updates. 

#### Outstanding Issues:

Ryujinx ALWAYS  crashes on my pc when I load any game, even with a save. I tried different games and versions, nothing works!
Says: Ryujinx has stopped working. And the Windows close the program even when I run as ADMIN!
I just want to play in Ryujinx but I can´t, please anyone know what I´m doing wrong? I have a windows 10 64x updated and OpenAL, everything and doesn´t work any game I can´t start or play.

#### Log file :

[https://file.io/482rLXb4rQp2](url)

**Comment by SeraUQ** [comment]
this is not a place for support, come to the [discord](https://discord.gg/ryujinx) channel for that
