### ISSUE TITLE
Hyrule Warriors Age of Calamity

### ISSUE THREAD

**Issue by readco** [Ryujinx/Ryujinx-Games-List#3266]
## Game Name
Hyrule Warriors Age of Calamity
#### Game Update Version : 
VER 1.0.1

Collects 1355 cache and keeps almost 30fps
In some maps or in certain situations (FiFo: 90 over), the game freezes and the program(Ryujinx) ends with a severe frame drop (5fps)

The error message is
|W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...

#### Hardware Specs : 

 Operating System: Microsoft Windows 10.0.19042 (X64)
 CPU : AMD Ryzen 5 5600X 6-Core Processor             
 RAM: 32GB
 VGA : NVIDIA Corporation GeForce GTX 1060 6GB/PCIe/SSE2 (4.6.0 NVIDIA 441.87)

[Ryujinx_1.0.6389_2021-01-23_16-34-01.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5859889/Ryujinx_1.0.6389_2021-01-23_16-34-01.log)

**Comment by EmulationFanatic** [comment]
There is already an entry for this game. https://github.com/Ryujinx/Ryujinx-Games-List/issues/2862
