### ISSUE TITLE
SUPER MARIO MAKER 2

### ISSUE THREAD

**Issue by YidaozhanYa** [Ryujinx/Ryujinx-Games-List#3267]
#### Current on ldn2.1

Many graphics errors occurred in the game, but the game can be played normally without any errors that affect the game play process. Multiplayer versus works in LDN mode.

#### Screenshots :
![1](https://user-images.githubusercontent.com/73830635/105573747-b18bad80-5d9a-11eb-8f5e-fa26637f897a.jpg)
![2](https://user-images.githubusercontent.com/73830635/105573748-b5b7cb00-5d9a-11eb-8dc3-d7eb37ee3047.jpg)
![Untitled](https://user-images.githubusercontent.com/73830635/105573749-b81a2500-5d9a-11eb-9a06-37634853773e.jpg)

**Comment by YidaozhanYa** [comment]
If i turn on "ignore missing service" option, all menus can be loaded correctly, except for some menus in the course world. Story mode, course bot and other singleplayer function works.

**Comment by EmulationFanatic** [comment]
There is already an entry for this game. https://github.com/Ryujinx/Ryujinx-Games-List/issues/180
Please reply to the existing post with any information you'd like to add.

**Comment by l32l0z** [comment]
how tf could yall get this link, i wanna play this game so bad but i couldnt afford switch price
