### ISSUE TITLE
List of outdated games that can be retested/updated

### ISSUE THREAD

**Issue by zephyren25** [Ryujinx/Ryujinx-Games-List#34]
- [ ] 3D Minigolf
- [ ] Dragon Ball Xenoverse 2
- [ ] Human Fall Flat
- [ ] I Am Setsuna
- [ ] Ittle Dew 2+
- [ ] Mega Man Legacy Collection
- [ ] Overcooked: Special Edition
- [ ] Poi: Explorer Edition
- [ ] Pokkén Tournament™ DX
- [ ] Pokémon Quest
- [ ] Rocket League®
- [ ] Soldam: Drop, Connect, Erase
- [ ] Super Bomberman R
- [ ] Tales of the Tiny Planet

**Comment by AcK77** [comment]
I don’t think this list is necessary since all games need to be retested/updated at each new version of Ryujinx... So your list right here will need to be cleared and gonna be totally false if we apply some PR in few minutes/hours!

**Comment by AcK77** [comment]
@firewolfgames Should you continue your updates? Or should I close this issue? If you don't answer, I will close it. Thanks.

**Comment by maikpla** [comment]
I think we should continue this

**Comment by firewolfgames** [comment]
Updated list, adding new games in a bit

**Comment by AcK77** [comment]
I close this issues since it's not used.
