### ISSUE TITLE
the "keys" archive is missing

### ISSUE THREAD

**Issue by jurosa80** [Ryujinx/Ryujinx-Games-List#3407]
hello!

i downloaded the emulator and run. Then i received a message that the archive refer to "keys" is missing. So, i followed the tutorial steps on https://github.com/Ryujinx/Ryujinx/wiki/Ryujinx-Setup-&-Configuration-Guide#initial-setup---placement-of-prodkeys but there's no archive at all. The folder is empty. How can i fix it?

**Comment by EmulationFanatic** [comment]
This is a game compatibility list. For emulator support, please come to our Discord.
