### ISSUE TITLE
Pokémon Sw/Sh LAN issue

### ISSUE THREAD

**Issue by Zophirel** [Ryujinx/Ryujinx-Games-List#3421]
#### Ryujinx Version: 1.0.0-ldn2.1

*it dose not connect / found my switch even if they are conncected on the same network and has the same version, the only differences i could found is that on ryujinx when i look for a link trade or a battle through the ycomm functions the sticker that appear on the bottom left it happears many times but on the switch it happear just one time. (i do not have any porblem connecting to Mario Kart 8)*

#### Screenshots :
My multiplayer settings
*https://i.imgur.com/of9vC6V.png*

Ryujinx looking for a trade after awhile 
*https://i.imgur.com/eNu65x7.png*

Switch looking for a trade after awhile
*https://i.imgur.com/APQXfiJ.jpg*

**Comment by EmulationFanatic** [comment]
Thanks for the detailed info. Please post this issue on the main repo instead! https://github.com/Ryujinx/Ryujinx/issues
