### ISSUE TITLE
Just Dance 2018 - 0100A0500348A00

### ISSUE THREAD

**Issue by ReaperOQ** [Ryujinx/Ryujinx-Games-List#3422]
#### Current on `master` : 1.0.0-ldn2.1

Runs badly, at 10-15 fps at in-game. I think that problem that my PC is too weak. Tested using UDP with phone.
Local multiplayer wasn't tested. World Dance Floor not working in cause of need internet connection.

#### Screenshots :

![image](https://user-images.githubusercontent.com/43516775/109871928-c6523f80-7c7c-11eb-9b54-a6ed528aa2f1.png)

**Comment by EmulationFanatic** [comment]
Please re-test this on a current master build; the LDN build is not suitable for gamedb entries. As a sidenote: I will probably end up testing this anyway on current hardware.
