### ISSUE TITLE
ryujinx has stpoped working

### ISSUE THREAD

**Issue by brandon-jesus** [Ryujinx/Ryujinx-Games-List#3428]
#### Game Update Version : 1.0.0 

The emulator is working very well, when I tried to run the game the software is closed few seconds after to show me an error message.

#### Screenshots :
![image](https://user-images.githubusercontent.com/12802541/110259120-1890aa80-7f74-11eb-8eba-2fca24013ab9.png)

![image](https://user-images.githubusercontent.com/12802541/110258716-06ae0800-7f72-11eb-9518-a364a0340b95.png)

#### Log file :

[Ryujinx_1.0.6776_2021-03-07_18-06-28.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6098186/Ryujinx_1.0.6776_2021-03-07_18-06-28.log)
[Ryujinx_1.0.6776_2021-03-07_18-12-46.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6098187/Ryujinx_1.0.6776_2021-03-07_18-12-46.log)
[Ryujinx_1.0.6776_2021-03-07_18-33-46.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6098188/Ryujinx_1.0.6776_2021-03-07_18-33-46.log)

**Comment by EmulationFanatic** [comment]
This is a game compatibility list and is the wrong place for support. That said, your hardware simply does not meet the minimum requirements for using the emulator, sorry.
