### ISSUE TITLE
Resolution Scaler not working 

### ISSUE THREAD

**Issue by KiNGKiMO** [Ryujinx/Ryujinx-Games-List#3441]
Crash Team Racing Nitro-Fueled

Game Update Version : 1.0.0

Current on `master` : 1.0.6794.0

Looks like the game is forcing original internal resolution somehow, and Ryujinx doesn't deal with it.

Switching from/to Handled/Docked modes can fix the issue but once the current match ends, the game forces it's internal resolution again and this workaround won't work anymore.

Hardware Specs : 
CPU: i7-4790K
GPU: NVIDIA GTX 1080ti
RAM: 32GB

**Comment by EmulationFanatic** [comment]
This is a game compatibility database. As such this issue does not belong here. See this Github issue for resolution scaling issues on Crash Team Racing opened in August of last year. https://github.com/Ryujinx/Ryujinx/issues/1488

**Comment by KiNGKiMO** [comment]
Aha, sorry and thank you.
