### ISSUE TITLE
Monster Hunter Rise crash

### ISSUE THREAD

**Issue by asd44454445** [Ryujinx/Ryujinx-Games-List#3467]
Monster Hunter Rise 1.0.0

Ryujinx ldn2.1

Continue game on crash[](url)

[Ryujinx_1.0.0-ldn2.1_2021-03-29_19-21-24.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6221374/Ryujinx_1.0.0-ldn2.1_2021-03-29_19-21-24.log)

**Comment by EmulationFanatic** [comment]
Please come to Discord for support. There is already an entry for this game in the compatibility list.
