### ISSUE TITLE
Hyrule Warriors: Age of Calamity

### ISSUE THREAD

**Issue by chaolouis** [Ryujinx/Ryujinx-Games-List#3474]
##### RAM: 32GB
 
[Ryujinx_1.0.6819_2021-04-05_09-18-10.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6255921/Ryujinx_1.0.6819_2021-04-05_09-18-10.log)

**Comment by Cronos-0** [comment]
Duplicate https://github.com/Ryujinx/Ryujinx-Games-List/issues/2862
