### ISSUE TITLE
Monster Hunter Rise on Nvidia GeForce Gtx 1050 Ti

### ISSUE THREAD

**Issue by Raz5562** [Ryujinx/Ryujinx-Games-List#3505]
#### Hardware Specs : 

Processor : Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz   2.21 GHz
Installed RAM	: 8.00 GB (7.85 GB usable)
GPU : Nvidia GeForce Gtx 1050 Ti

#### Issues: 6-10fps when in the game and cutscenes, when in making character,palamute,cat the fps is 30fps (stable)
![Screenshot (14)](https://user-images.githubusercontent.com/82114556/113913430-e8f0ee80-980e-11eb-9042-f51072dbd33f.png)
 
#### Screenshots : 
![Screenshot (15)](https://user-images.githubusercontent.com/82114556/113913274-b515c900-980e-11eb-90b0-5379d6229e81.png)

**Comment by EmulationFanatic** [comment]
Thank you for the report, but this issue already exists here: https://github.com/Ryujinx/Ryujinx-Games-List/issues/3465
