### ISSUE TITLE
MONSTER HUNTER RISE - 0100B04011742000

### ISSUE THREAD

**Issue by GamerVI** [Ryujinx/Ryujinx-Games-List#3508]
Monster Hunter Rise

Game Update Version: 1.0.0

Current on master : 1.0.6823

Game does not start, i get a blackscreen.
more infos in the log

#### Hardware Specs : 

CPU: i7-4710HQ
GPU: Nvidia GeForce 860m
RAM: 16GB

#### Log file :

https://textuploader.com/tsklr

**Comment by AcK77** [comment]
A issue for report already exists here : https://github.com/Ryujinx/Ryujinx-Games-List/issues/3465.
I suggest you to come on our discord at https://discord.gg/ryujinx for support.
Thanks.

**Comment by gdkchan** [comment]
Just wait, the game takes a long time to start the first time.
