### ISSUE TITLE
Animal Crossing: New Horizons Bug

### ISSUE THREAD

**Issue by noahra101** [Ryujinx/Ryujinx-Games-List#353]
Animal Crossing: New Horizons

Version 1.0.3987

Game does not appear on initial screen, as if I have no games in my selected file, and upon trying to open the game directly, the screen goes dark.

Console read this error:

System.NotImplementedException: android.gui.IGraphicBufferProducer 2 

![Capture](https://user-images.githubusercontent.com/62623730/77477729-2a288300-6df3-11ea-811d-3efaa55dc933.PNG)

![Capture](https://user-images.githubusercontent.com/62623730/77477640-09f8c400-6df3-11ea-9794-50c206b9e5e5.PNG)

**Comment by B3astTech** [comment]
Closing since https://github.com/Ryujinx/Ryujinx-Games-List/issues/250 exist

**Comment by noahra101** [comment]
Yeah, but that didn't have an answer.

**Comment by AcK77** [comment]
Go to our discord server for support! Thanks!

**Comment by noahra101** [comment]
I did, and there wasn't anywhere I was able to ask for help.

**Comment by AcK77** [comment]
There is, just read everything carefully.
