### ISSUE TITLE
Black Screen with sound

### ISSUE THREAD

**Issue by MikaCookies** [Ryujinx/Ryujinx-Games-List#3594]
When I try to load a game nothing but a black screen appears. The game is heard and if I press buttons I can move forward but without seeing anything. 

## Game Name
Yo-Kai watch 4

#### Game Update Version : *(e.g. 1.0.0 or 1.1.3)*
2.1.1

#### Hardware Specs : 

Intel i7-6700K 4.0Ghz
Sapphire Radeon Nitro Plus RX 480 OC 8GB GDDR5
G.Skill Ripjaws V Red DDR4 2133 PC4-17000 16GB 2x8GB CL15
Gigabyte GA-Z270-HD3P

#### Log file :

00:00:00.001 |I| Configuration LogValueChange: EnableFileLog set to: True
00:00:00.011 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.012 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.012 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.012 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.015 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.025 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.025 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.025 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.025 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.025 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.026 |I| Configuration LogValueChange: AudioBackend set to: OpenAl
00:00:00.026 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.026 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.028 |N| Application PrintSystemInfo: Ryujinx Version: 1.0.6878
00:00:00.033 |N| Application Print: Operating System: Microsoft Windows 10.0.19042 (X64)
00:00:00.033 |N| Application Print: CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz ; 8 logical
00:00:00.033 |N| Application Print: RAM: Total 16337 MB ; Available 9294 MB
00:00:00.035 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.035 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.345 |N| Application LoadApplication: Using Firmware Version: 12.0.2
00:00:00.345 |I| Application LoadApplication: Loading as NSP.
00:00:00.378 |I| Application AddAocItem: Found AddOnContent with TitleId 010086C00AF7D064
00:00:00.407 |I| ModLoader QueryContentsDir: Searching mods for Title 010086C00AF7C000
00:00:00.407 |I| ModLoader QueryContentsDir: Searching mods for DLC 010086C00AF7D064
00:00:00.417 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:00.514 |I| Loader LoadExeFs: Loading rtld...
00:00:00.535 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.535 |I| Loader LoadExeFs: Loading main...
00:00:00.766 |I| Loader PrintRoSectionInfo: main:
    Module: G:\yw4\program\main\program\Release\NX64_Rom\yw_nx.nss
    SDK Libraries: SDK MW+Nintendo+NEX_MM-4_6_2
                   SDK MW+Nintendo+NEX-4_6_2-
                   SDK MW+Nintendo+PiaCommon-5_17_0
                   SDK MW+Nintendo+Pia-5_17_0
                   SDK MW+Nintendo+PiaLocal-5_17_0
                   SDK MW+Nintendo+PiaNex-5_17_0-forNEX-4_6_2
                   SDK MW+Nintendo+PiaSession-5_17_0
                   SDK MW+Nintendo+PiaTransport-5_17_0
                   SDK MW+Nintendo+NintendoSDK_libcurl-7_3_2-Release
                   SDK MW+Nintendo+NintendoSDK_libz-7_3_2-Release
                   SDK MW+NVIDIA+PhysX-3_4_0-release
00:00:00.766 |I| Loader LoadExeFs: Loading sdk...
00:00:00.896 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 7.3.2
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-7_3_2-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-7_3_2-Release
                   SDK MW+Nintendo+NintendoSDK_NVN-7_3_2-Release
00:00:00.948 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:01.504 |I| Ptc Load: Loaded Translation Cache (size: 38533669 bytes, translated functions: 13228).
00:00:01.514 |I| Ptc Load: Loaded Profiling Info (size: 50606 bytes, profiled functions: 15995).
00:00:01.633 |I| Loader LoadNsos: Loading image 0 at 0x0000000008000000...
00:00:01.637 |I| Loader LoadNsos: Loading image 1 at 0x0000000008004000...
00:00:01.694 |I| Loader LoadNsos: Loading image 2 at 0x000000000eae1000...
00:00:01.705 |I| ModLoader LoadCheats: Build ids found for title 010086C00AF7C000:
    39E10C07096696C9C4E228496C4BC44D6B9E0041000000000000000000000000
    DCFCCD795D18F3F9EC1FC8E83D892FD1BDFF6E39000000000000000000000000
    FCF93A41B08C5193A1410D262602DC621617C56F000000000000000000000000
00:00:01.705 |I| Loader LoadNca: Application Loaded: ??????4 ?????????????? v2.1.1 [010086c00af7c000] [64-bit]
00:00:01.717 |I| GUI.WindowThread Hid Configure: Configured Controller ProController to Player1
00:00:01.990 |I| GUI.WindowThread Hid SetupNpad: Connected Controller ProController to Player1
00:00:02.020 |N| GUI.RenderLoop Gpu PrintGpuInformation: ATI Technologies Inc. Radeon (TM) RX 480 Graphics (3.3.14831 Compatibility Profile Context 21.5.2 27.20.21003.8013)
00:00:02.062 |I| GUI.RenderLoop Gpu EnsureArchiveUpToDate: Updating cache collection archive C:\Users\Mika\AppData\Roaming\Ryujinx\games\010086c00af7c000\cache\shader\guest\program\cache.zip...
00:00:02.065 |I| GUI.RenderLoop Gpu EnsureArchiveUpToDate: Updated cache collection archive C:\Users\Mika\AppData\Roaming\Ryujinx\games\010086c00af7c000\cache\shader\guest\program\cache.zip.
00:00:02.074 |I| GUI.RenderLoop Gpu EnsureArchiveUpToDate: Updating cache collection archive C:\Users\Mika\AppData\Roaming\Ryujinx\games\010086c00af7c000\cache\shader\opengl\glsl\host\cache.zip...
00:00:02.076 |I| GUI.RenderLoop Gpu EnsureArchiveUpToDate: Updated cache collection archive C:\Users\Mika\AppData\Roaming\Ryujinx\games\010086c00af7c000\cache\shader\opengl\glsl\host\cache.zip.
00:00:02.144 |I| CacheCollection.Worker.program Gpu EnsureArchiveUpToDate: Updating cache collection archive C:\Users\Mika\AppData\Roaming\Ryujinx\games\010086c00af7c000\cache\shader\guest\program\cache.zip...
00:00:02.144 |I| CacheCollection.Worker.host Gpu EnsureArchiveUpToDate: Updating cache collection archive C:\Users\Mika\AppData\Roaming\Ryujinx\games\010086c00af7c000\cache\shader\opengl\glsl\host\cache.zip...
00:00:02.146 |I| CacheCollection.Worker.program Gpu EnsureArchiveUpToDate: Updated cache collection archive C:\Users\Mika\AppData\Roaming\Ryujinx\games\010086c00af7c000\cache\shader\guest\program\cache.zip.
00:00:02.146 |I| CacheCollection.Worker.host Gpu EnsureArchiveUpToDate: Updated cache collection archive C:\Users\Mika\AppData\Roaming\Ryujinx\games\010086c00af7c000\cache\shader\opengl\glsl\host\cache.zip.
00:00:02.153 |I| GUI.RenderLoop Gpu Initialize: Shader cache loaded 32 entries.
00:00:02.439 |I| HLE.GuestThread.15 Ptc LoadTranslations: 12226 translated functions loaded
00:00:02.446 |I| HLE.GuestThread.15 Ptc MakeAndSaveTranslations: 0 of 3769 functions translated | Thread count: 9
00:00:42.475 |I| HLE.GuestThread.15 Ptc MakeAndSaveTranslations: 3769 of 3769 functions translated | Thread count: 9
00:00:42.937 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:42.949 |S| HLE.OsThread.16 ServiceAm GetAppletResourceUserId: Stubbed.
00:00:42.956 |S| HLE.OsThread.16 ServiceAm AcquireForegroundRights: Stubbed.
00:00:42.957 |S| HLE.OsThread.16 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:42.958 |S| HLE.OsThread.16 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:42.963 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:42.964 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:42.967 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:42.968 |S| HLE.OsThread.16 ServicePctl Initialize: Stubbed.
00:00:42.977 |G| HLE.OsThread.16 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 42s
    Line: 301
    Filename: 'G:/yw4/program/lives/program/10_lib_platform/src/nx/device/device_nx.cpp'
    Function: 'Startup'
    Module: ''
    Thread: 'MainThread'
    ProgramName: 'yw_nx'
    Message: 'Remain Memory Size 192MiB (201326592byte)'

00:00:44.407 |I| Ptc Save: Saved Translation Cache (size: 55987106 bytes, translated functions: 16997).
00:00:51.737 |S| HLE.OsThread.10 ServiceNv FinishInitialize: Stubbed.
00:00:51.750 |S| HLE.OsThread.10 ServiceNv InitializeEx: Stubbed.
00:00:51.750 |S| HLE.OsThread.10 ServiceNv GetVaRegions: Stubbed.
00:00:51.751 |S| HLE.OsThread.10 ServiceNv GetVaRegions: Stubbed.
00:00:51.765 |I| HLE.OsThread.10 ServiceNv Create: Created map 1 with size 0x00001000!
00:00:51.776 |I| HLE.OsThread.10 ServiceNv Create: Created map 2 with size 0x00010000!
00:00:51.778 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed.
00:00:51.780 |S| HLE.OsThread.10 ServiceNv ZbcSetTable: Stubbed.
00:00:51.780 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed.
00:00:51.780 |I| HLE.OsThread.10 ServiceNv Create: Created map 3 with size 0x04000000!
00:00:51.781 |I| HLE.OsThread.10 ServiceNv Create: Created map 4 with size 0x02000000!
00:00:51.782 |I| HLE.OsThread.10 ServiceNv Create: Created map 5 with size 0x12a00000!
00:00:51.795 |I| HLE.OsThread.10 ServiceNv Create: Created map 6 with size 0x35c00000!
00:00:51.829 |I| HLE.OsThread.10 ServiceNv Create: Created map 7 with size 0x04000000!
00:00:51.830 |I| HLE.OsThread.10 ServiceNv Create: Created map 8 with size 0x02000000!
00:00:51.834 |S| HLE.OsThread.16 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:51.834 |S| HLE.OsThread.16 ServiceAm SetRestartMessageEnabled: Stubbed. {restartMessageEnabled: True}
00:00:51.834 |S| HLE.OsThread.16 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:51.834 |S| HLE.OsThread.16 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:51.837 |S| HLE.OsThread.16 ServiceAcc InitializeApplicationInfo: Stubbed. {TitleId: 72205753413779456}
00:00:51.840 |S| HLE.OsThread.16 ServiceAcc IsUserAccountSwitchLocked: Stubbed.
00:00:51.840 |I| HLE.OsThread.10 ServiceNv Create: Created map 9 with size 0x00001000!
00:00:51.842 |S| HLE.OsThread.10 ServiceNv BindChannel: Stubbed.
00:00:51.844 |S| HLE.OsThread.10 ServiceNv SetNvMapFd: Stubbed.
00:00:51.844 |S| HLE.OsThread.10 ServiceNv AllocGpfifoEx2: Stubbed.
00:00:51.845 |S| HLE.OsThread.10 ServiceNv AllocObjCtx: Stubbed.
00:00:51.846 |S| HLE.OsThread.10 ServiceNv SetTimeout: Stubbed.
00:00:51.847 |S| HLE.OsThread.10 ServiceNv SetErrorNotifier: Stubbed.
00:00:51.847 |S| HLE.OsThread.10 ServiceNv SetUserData: Stubbed.
00:00:51.847 |S| HLE.OsThread.10 ServiceNv SetTimeslice: Stubbed.
00:00:51.848 |I| HLE.OsThread.10 ServiceNv Create: Created map 10 with size 0x00010000!
00:00:51.848 |I| HLE.OsThread.10 ServiceNv Create: Created map 11 with size 0x0004a000!
00:00:51.849 |S| HLE.OsThread.10 ServiceNv ZcullBind: Stubbed.
00:00:51.853 |I| HLE.OsThread.10 ServiceNv Create: Created map 12 with size 0x00001000!
00:00:51.853 |S| HLE.OsThread.10 ServiceNv BindChannel: Stubbed.
00:00:51.853 |S| HLE.OsThread.10 ServiceNv SetNvMapFd: Stubbed.
00:00:51.853 |S| HLE.OsThread.10 ServiceNv AllocGpfifoEx2: Stubbed.
00:00:51.853 |S| HLE.OsThread.10 ServiceNv AllocObjCtx: Stubbed.
00:00:51.853 |S| HLE.OsThread.10 ServiceNv SetTimeout: Stubbed.
00:00:51.853 |S| HLE.OsThread.10 ServiceNv SetErrorNotifier: Stubbed.
00:00:51.854 |S| HLE.OsThread.10 ServiceNv SetUserData: Stubbed.
00:00:51.854 |S| HLE.OsThread.10 ServiceNv SetTimeslice: Stubbed.
00:00:51.854 |I| HLE.OsThread.10 ServiceNv Create: Created map 13 with size 0x00010000!
00:00:51.854 |I| HLE.OsThread.10 ServiceNv Create: Created map 14 with size 0x00048000!
00:00:51.863 |I| HLE.OsThread.16 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:51.912 |I| HLE.OsThread.16 ServiceAm GetDesiredLanguage: Application doesn't support configured language. Using Japanese
00:00:51.915 |S| HLE.OsThread.9 ServiceHid ActivateNpadWithRevision: Stubbed. {appletResourceUserId: 4294967296 ; revision: 2}
00:00:51.916 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {appletResourceUserId: 4294967296 ; type: ProController, Handheld, JoyconPair}
00:00:51.918 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadIdType: Stubbed. 2 Player1,Handheld
00:00:51.920 |S| HLE.OsThread.9 ServiceHid GetVibrationDeviceInfo: Stubbed. {vibrationDeviceHandle: 3 ; DeviceType: None ; Position: None}
00:00:51.920 |S| HLE.OsThread.9 ServiceHid GetVibrationDeviceInfo: Stubbed. {vibrationDeviceHandle: 65539 ; DeviceType: None ; Position: None}
00:00:51.920 |S| HLE.OsThread.9 ServiceHid GetVibrationDeviceInfo: Stubbed. {vibrationDeviceHandle: 8195 ; DeviceType: None ; Position: None}
00:00:51.920 |S| HLE.OsThread.9 ServiceHid GetVibrationDeviceInfo: Stubbed. {vibrationDeviceHandle: 73731 ; DeviceType: None ; Position: None}
00:00:52.796 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:52.797 |S| HLE.OsThread.7 ServiceAudio QueryAudioDeviceOutputEvent: Stubbed.
00:00:52.797 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:52.801 |I| HLE.OsThread.8 AudioRenderer AcquireSessionId: Registered new output (0)
00:00:52.805 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:54.023 |S| HLE.OsThread.16 ServiceNs ListAddOnContent: Stubbed. {bufferSize: 33 ; startIndex: 0 ; aocCount: 1}
00:00:54.236 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:01:10.268 |S| HLE.OsThread.16 ServiceNs PrepareAddOnContent: Stubbed. {aocIndex: 100}
00:01:10.269 |S| HLE.OsThread.16 ServiceNs GetAddonContentBaseId: Stubbed. aocBaseId=010086C00AF7D000
00:01:10.274 |I| HLE.OsThread.16 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=010086C00AF7D064
00:01:10.276 |S| HLE.OsThread.16 ServiceNs PrepareAddOnContent: Stubbed. {aocIndex: 100}
00:01:10.276 |S| HLE.OsThread.16 ServiceNs GetAddonContentBaseId: Stubbed. aocBaseId=010086C00AF7D000
00:01:10.276 |I| HLE.OsThread.16 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=010086C00AF7D064
00:01:12.499 |I| Ptc Save: Saved Profiling Info (size: 50614 bytes, profiled functions: 15997).
00:01:42.492 |I| Ptc Save: Saved Profiling Info (size: 50625 bytes, profiled functions: 15998).
00:02:12.485 |I| Ptc Save: Saved Profiling Info (size: 50651 bytes, profiled functions: 16000).

**Comment by Niwu34** [comment]
Currently the openGl - Amd Drivers are broken and therefore Ryujinx renders black - either Roll back to the latest working one(21.3.2), use Linux or wait for the Vulkan Api Pr

**Comment by AcK77** [comment]
This is for games report, not Ryujinx support. If you needs support, goes to our discord, thanks.
