### ISSUE TITLE
Animal Crossing New Horizons Time Problem

### ISSUE THREAD

**Issue by tense11** [Ryujinx/Ryujinx-Games-List#3628]
#### Current on `master` : Commit Id *or* Build Version : 1.0.0-ldn2.3

The in-game time is 8 hours earlier than the Windows 10 time, and the time zone cannot be changed to UTC+8.

**Comment by EmulationFanatic** [comment]
Set your time zone in the emulator options (start typing UTC in the field and select your time zone). Closing this issue as this is a game compatibility database and there is already a proper entry for ACNH.
