### ISSUE TITLE
Final Fantasy XII Zodiac Age - 0100EB100AB42000

### ISSUE THREAD

**Issue by Djipi71** [Ryujinx/Ryujinx-Games-List#3630]
Final Fantasy XII The Zodiac Age

Game Update Version : 1.0.0

Build : 6915

The game work well but with some graphicals issues : Shirt is missing and some polygons on characters or building are missing

##### RAM: 32GB

![Sans titre-1](https://user-images.githubusercontent.com/35375131/122688134-ccaffb80-d21a-11eb-8c66-33b4e095316b.png)

**Comment by AcK77** [comment]
Duplicate of #822
