### ISSUE TITLE
Pokemon sword 4th gym mission

### ISSUE THREAD

**Issue by SugarCubeOfSalt** [Ryujinx/Ryujinx-Games-List#3636]
Pokemon sword

v1.0.0

1.0.6939

almost impossible to beat

**Comment by AcK77** [comment]
Duplicate of #232

**Comment by SugarCubeOfSalt** [comment]
> Duplicate of #232

its not though theyre completely different im asking for advice on how to beat the 4th gym mission on keyboard

**Comment by AcK77** [comment]
This is for game report, not user support, if you needs support I suggest you to come on our discord server.
Thanks!
