### ISSUE TITLE
why do i not have motion controls

### ISSUE THREAD

**Issue by SugarCubeOfSalt** [Ryujinx/Ryujinx-Games-List#3637]
![image](https://user-images.githubusercontent.com/86576732/123647897-c7f5d380-d828-11eb-8498-9c19e6f2a323.png)

**Comment by EmulationFanatic** [comment]
This is a game compatibility database. Please come to Discord for support.

**Comment by SugarCubeOfSalt** [comment]
> This is a game compatibility database. Please come to Discord for support.

can i have the discord link?
