### ISSUE TITLE
Audio Desync & Occasional BGM Stutter

### ISSUE THREAD

**Issue by Amy7007** [Ryujinx/Ryujinx-Games-List#3642]
## Game Name

Famicom Detective Club The Girl Who Stands Behind & The Missing Heir Bundle

#### Game Update Version : *(e.g. 1.0.0 or 1.1.3)*

1.0

#### Current on `master` : Commit Id *or* Build Version : *(e.g. 0a41a3ff or 1.0.1952)*

1.0.6946

*Describe the current game state here.*

The Game runs at 50-60 fps with occasional 30-40 fps but the audio between character dialog starting from Chapter 1 till finish seems to fall behind really far and the dialog voice played in the beginning repeated for the second time after the MC answered the phone. Afterward...no audio from the character's dialog and after several seconds, the dialog voice finally start despite the dialog and graphic already went ahead of the audio. Also, the BGM upon starting a chapter suddenly stutter and stop stuttering once the narration start.
```
Last error returned.
e.g.: Unhandled Exception: System.NotImplementedException: /dev/nvhost-nvdec 40044801
```

#### Pull requests needed :

*Add needed PR links here.*

*(Optional section, remove it if unneeded)*

#### Outstanding Issues:

*Add issue links here.*

*Example: https://github.com/Ryujinx/Ryujinx/issues/xxx (xxx = number issue)*

*(Optional section, remove it if unneeded)*

#### Screenshots :

*Add screenshots here if the game rendering something.*

*(Optional section, remove it if unneeded)*

#### Log file :

*Add a link to the log file here.*

*(Optional section, remove it if unneeded)*

**Comment by AcK77** [comment]
Report the issue in the game dedicated, thanks.

**Comment by Amy7007** [comment]
> Report the issue in the game dedicated, thanks.

Tell me where I can report the issue. It's my first time doing this reporting the issue in Github here
