### ISSUE TITLE
Skyward Sword HD Audio Quality Issue

### ISSUE THREAD

**Issue by nashlaga** [Ryujinx/Ryujinx-Games-List#3658]
The Legend of Zelda: Skyward Sword

Game Update Version : 1.0.0

Ryujinx Version 1.0.6973

Majority of the audio including music seems to be playing at a lowered bit depth or sample rate, 

Hardware Specs : 

CPU: Ryzen 5600x
GPU: NVIDIA RTX 3070
RAM: 32GB DDR4

**Comment by AcK77** [comment]
Duplicate of #3657, comment your feedback there if needed. Thanks.
