### ISSUE TITLE
fire emblem warriors 15.0 clashes again in build 1.0.6974  (in game, after ~3-5 minutes in battlefield)

### ISSUE THREAD

**Issue by joseph1106** [Ryujinx/Ryujinx-Games-List#3661]
## Game Name: 
fire emblem warriors 

#### Game Update Version : *(e.g. 1.0.0 or 1.1.3)* 
15.0

#### Current on `master` : Commit Id *or* Build Version : *(e.g. 0a41a3ff or 1.0.1952)*

*Describe the current game state here.* 
in game, after ~3-5 minutes in battlefield
```
Last error returned.
e.g.: Unhandled Exception: System.NotImplementedException: /dev/nvhost-nvdec 40044801
```

#### Pull requests needed :

*Add needed PR links here.*

*(Optional section, remove it if unneeded)*

#### Outstanding Issues:

*Add issue links here.*

*Example: https://github.com/Ryujinx/Ryujinx/issues/xxx (xxx = number issue)*

*(Optional section, remove it if unneeded)*

#### Screenshots :

*Add screenshots here if the game rendering something.*

*(Optional section, remove it if unneeded)*

#### Log file :

*Add a link to the log file here.*

*(Optional section, remove it if unneeded)*

**Comment by AcK77** [comment]
Please report the issue in the game corresponding one. Thanks.
