### ISSUE TITLE
Monster Hunter Stories 2: Wings of Ruin don't work in  Ryujinx (1.0.6974)

### ISSUE THREAD

**Issue by momoids** [Ryujinx/Ryujinx-Games-List#3664]
Monster Hunter Stories 2: Wings of Ruin

Game Update Version : 1.0.1

Ryujinx (1.0.6974)

The game worked in the previous version, but in the current version it doesn't work anymore!

Hardware Specs : 
CPU: RYZEN 1600x
GPU: NVIDIA GTX 1060 6GB
RAM: 32GB DDR4

 Log file :

![Ryujinx](https://user-images.githubusercontent.com/70231770/126570735-3f56a5a5-6a97-4b69-9718-581df6548289.jpg)
[Ryujinx_1.0.6974_2021-07-21_19-48-47.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6859204/Ryujinx_1.0.6974_2021-07-21_19-48-47.log)

**Comment by Niwu34** [comment]
You moved the dlc files to a different location
Delete the dlc.json file in AppData > Roaming > Ryujinx > games > 0100e21011446000
(You have to reaadd them later again)
Pls join the discord and ask in #support next time

**Comment by momoids** [comment]
Ok! Thank You!

**Comment by gdkchan** [comment]
Closing as this is not a game issue.
