### ISSUE TITLE
Game crashes at certain points

### ISSUE THREAD

**Issue by gh34777** [Ryujinx/Ryujinx-Games-List#3675]
#### Hi, I'd like to report that when entering this specific section, where a cut scene played, the game will crash. This is the error I got, and the full log

Full log
[Ryujinx_1.0.6982_2021-08-11_18-35-49.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6968143/Ryujinx_1.0.6982_2021-08-11_18-35-49.log)

Actual error
[actual error.txt](https://github.com/Ryujinx/Ryujinx-Games-List/files/6968168/actual.error.txt)

#### Screenshot of the location of where I got the error

![ryujinx_capture_2021-08-11_18-37-05_LI](https://user-images.githubusercontent.com/88777521/129025087-34feacce-db71-4625-b81e-860b61c2e8ab.jpg)

**Comment by gdkchan** [comment]
Post on the existing entry for this game #3644.
