### ISSUE TITLE
Error 2002 - 0007 super smash

### ISSUE THREAD

**Issue by Gaarain** [Ryujinx/Ryujinx-Games-List#3678]
#### Current on `master` : Commit Id *or* Build Version : 1.0.7000

*I've been playing normally on the Ryujinx, today it updated and the Super Smash just stoped working and sent me that error. Other games are running normally.*

```
Last error returned.
Error code: 2002 - 0007
```

#### Pull requests needed :

*Add needed PR links here.*

#### Outstanding Issues:

*Add issue links here.*

*Example: https://github.com/Ryujinx/Ryujinx/issues/xxx (xxx = number issue)*

#### Screenshots :

*Add screenshots here if the game rendering something.*

![image](https://user-images.githubusercontent.com/89158945/129955038-259542e8-ecbb-4e75-9976-13818939747a.png)

#### Log file :

*Add a link to the log file here.*

**Comment by Niwu34** [comment]
should be fixed by https://github.com/Ryujinx/Ryujinx/pull/2564

**Comment by Gaarain** [comment]
> should be fixed with [Ryujinx/Ryujinx#2564](https://github.com/Ryujinx/Ryujinx/pull/2564)
> (you can manually delete r sd card folder for now)

Omg thank you so much, it did work and was easier than I thought!

**Comment by tico911** [comment]
hi, I've got the right same problem, but when i delete the sdcard folder, the error message come again, what can i do
