### ISSUE TITLE
mh rise crashed after update 

### ISSUE THREAD

**Issue by zuloc09** [Ryujinx/Ryujinx-Games-List#3735]
[##](url) Game Name Mh rise

#### Current on `master` : Commit Id *or* Build Version : *(e.g. 0a41a3ff or 1.0.1952)*

*Describe the current game state here.*

```
Last error returned.
e.g.: Unhandled Exception: System.NotImplementedException: /dev/nvhost-nvdec 40044801
```

#### Pull requests needed :

*Add needed PR links here.*

*(Optional section, remove it if unneeded)*

#### Outstanding Issues:

*Add issue links here.*

*Example: https://github.com/Ryujinx/Ryujinx/issues/xxx (xxx = number issue)*

*(Optional section, remove it if unneeded)*

#### Screenshots :

*Add screenshots here if the game rendering something.*
![hình ảnh_2021-10-16_222634](https://user-images.githubusercontent.com/92640294/137593151-785e5d1d-bbcd-4024-a3e3-3470f47a2aeb.png)

*(Optional section, remove it if unneeded)*

#### Log file :

*Add a link to the log file here.*

*(Optional section, remove it if unneeded)*

**Comment by gdkchan** [comment]
The template was not properly filled. Also this looks like a shader cache issue, try purging the shader cache.
