### ISSUE TITLE
Mario Party Superstars - 01006fe013472000

### ISSUE THREAD

**Issue by r3ntonboy** [Ryujinx/Ryujinx-Games-List#3755]
#### Current on master : 1.0.7094

*Selecting another profile for player 2, ryujinx crashes.*

#### Log file :

[Ryujinx_1.0.7094_2021-10-30_10-31-23.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/7446649/Ryujinx_1.0.7094_2021-10-30_10-31-23.log)

**Comment by GamerzHell9137** [comment]
https://github.com/Ryujinx/Ryujinx-Games-List/issues/3752

**Comment by MutantAura** [comment]
duplicate please close
