### ISSUE TITLE
System Time Changes Don't Affect Games, While They're Running

### ISSUE THREAD

**Issue by Begueiro** [Ryujinx/Ryujinx-Games-List#3779]
## Game Name
Pokémon Shield

#### Game Update Version : *(e.g. 1.0.0 or 1.1.3)*
1.3.2

#### Current on `master` : Commit Id *or* Build Version : *(e.g. 0a41a3ff or 1.0.1952)*
1.0.7107

*Describe the current game state here.*
The game runs fine enough.

```
Last error returned.
e.g.: Unhandled Exception: System.NotImplementedException: /dev/nvhost-nvdec 40044801
```
No errors

##### CPU: *(e.g. i7-6700)*
i5-7600K

##### GPU: *(e.g. NVIDIA RTX 2070)*
NVIDIA GTX 1660 Ti

##### RAM: *(e.g. 16GB)*
32GB

#### Pull requests needed :

*Add needed PR links here.*
I'm not sure what this means... 🤔

Well, I'm not sure where I should describe the issue, so I'll do it here.
I've just started using Switch emulators and first tried Yuzu. In that emulator, if I change the system time, it immediately has an effect on the game, which is the same as the Nintendo Switch itself. Meaning, if there's a specific weather, on a set date, then I'll see the weather changing, as soon as I apply the new date.

Ryujinx has a system date, but it only changes, when the game isn't running. So, in order for the weather (from my example above) to change, I need to stop the emulation and restart it.

There are certain glitches in this game that require the date to change, while the game is running, for a player to take advantage of them, but Ryujinx doesn't allow that to happen.

**Comment by gdkchan** [comment]
Which game is being talked about here?

**Comment by Begueiro** [comment]
Pokémon Shield. It's at the top of the ticket.
But I would assume it probably works that way for any game, but I don't know other games that I could test it with.

**Comment by gdkchan** [comment]
That doesn;t sound like a emulation bug. Feature requests should go in the main repo: https://github.com/Ryujinx/Ryujinx/issues
There's also a issue open for time related issues on this game: https://github.com/Ryujinx/Ryujinx/issues/2430 But I guess that's not your issue.

**Comment by Begueiro** [comment]
Ah, cool, you linked this to ticket 2430. It does seem related to it, but the weather doesn't change and they say it does. I haven't tried to do what they describe on their issue, yet, as I just started using Ryujinx, so I haven't gotten into it.

It's not a feature request, though. The feature is already in Ryujinx: it's the System Time and the option to "Save"/"Apply". Both are there.
The changes only take effect, when the emulator is restarted. Is that intended behavior?

**Comment by gdkchan** [comment]
It seems that what you want is changing the way how something that is already supported then. So, allowing the date to change with the game running. It is sort of a feature request, it should go on the main repo.

**Comment by Begueiro** [comment]
That depends on whether the system time is supposed to require the emulation to restart or not, that's why I reported it and asked if that's intended, previously.

Is that how it is intended? Because, if so, you are correct, it would fall under a request and it should have a warning, next to the System Time stating it, as to not mislead people and I wouldn't have reported it.

Is it an oversight? If it wasn't planed that way and that's not how you guys wanted it to work, then, it is, in fact, a bug.

And I don't know which one it is, so I reported it and, then, asked if it's an intended feature.

**Comment by gdkchan** [comment]
Right now the time offset is only applied when the emulation starts, so changing it while the game is running indeed is not going to have any effect, until you restart the emulation. I don't think there's any technical issue preventing it from being changed with the game running though, it's just a shortcoming of the implementation, so its fine to open an issue asking for it to be supported.

**Comment by Begueiro** [comment]
Ah, cool. Thanks for the info.

**Comment by Marlle** [comment]
For as great as this emulator is, this shouldn't be an issue. Wonder if it is fixable
