### ISSUE TITLE
Crash after Loading Game

### ISSUE THREAD

**Issue by Schuhlgas** [Ryujinx/Ryujinx-Games-List#3780]
#### Current on `master` : 1.0.7107

```
```
00:00:00.494 |I| Configuration LogValueChange: BackendThreading set to: Off
00:00:00.497 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.499 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.499 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.500 |I| Configuration LogValueChange: AspectRatio set to: Fixed4x3
00:00:00.505 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.506 |I| Configuration LogValueChange: EnableVsync set to: False
00:00:00.506 |I| Configuration LogValueChange: EnableShaderCache set to: False
00:00:00.506 |I| Configuration LogValueChange: EnablePtc set to: False
00:00:00.507 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: False
00:00:00.507 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.509 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.511 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.511 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.512 |I| Configuration LogValueChange: IgnoreMissingServices set to: True
00:00:00.520 |N| Application PrintSystemInfo: Ryujinx Version: 1.0.7107
00:00:00.529 |N| Application Print: Operating System: Microsoft Windows 10.0.22000 (X64)
00:00:00.529 |N| Application Print: CPU: Virtual CPU @ 3.20GHz ; 6 logical
00:00:00.530 |N| Application Print: RAM: Total 4090 MB ; Available 1575 MB
00:00:00.533 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.533 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:01:09.699 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:01:09.701 |I| Configuration LogValueChange: EnablePtc set to: True
00:01:09.702 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:01:09.703 |I| Configuration LogValueChange: ExpandRam set to: True
00:01:09.709 |I| Configuration LogValueChange: MaxAnisotropy set to: 2
00:00:00.135 |I| Gpu : Backend Threading (Off): False
00:00:00.431 |N| Application LoadApplication: Using Firmware Version: 12.0.2
00:00:00.431 |I| Application LoadApplication: Loading as XCI.
00:00:00.537 |I| ModLoader QueryContentsDir: Searching mods for Title 0100000011D90000
00:00:00.554 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:00.569 |I| Loader LoadExeFs: Loading rtld...
00:00:00.684 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.684 |I| Loader LoadExeFs: Loading main...
00:00:02.046 |I| Loader PrintRoSectionInfo: main:
    Module: F:\JenkinsWorkSpace\workspace\BuildRom_Launch\unity_project\Dpr\SwitchIL2CPPCache\il2cpp_cache\linkresult_22F671898E59E8B9B3F93C78532B1E40\SwitchPlayer.nss
    SDK Libraries: SDK MW+UnityTechnologies+Unity-2019_4_27_f1
                   SDK MW+Nintendo+NintendoSDK_libcurl-11_4_3-Release
                   SDK MW+Nintendo+NintendoSDK_libz-11_4_3-Release
                   SDK MW+Nintendo+NEX-4_6_11-appdl
                   SDK MW+Nintendo+PIA_UNITY-0.33.0
                   SDK MW+Nintendo+PiaSession-5_37_0
                   SDK MW+Nintendo+PiaTransport-5_37_0
                   SDK MW+Nintendo+NEX_DS-4_6_11
                   SDK MW+Nintendo+NEX_R2-4_6_11
                   SDK MW+Nintendo+NEX_RK-4_6_11
                   SDK MW+Nintendo+NEX_CO-4_6_11
                   SDK MW+Nintendo+NEX_SS-4_6_11
                   SDK MW+Nintendo+NEX_UT-4_6_11
                   SDK MW+Nintendo+PiaCommon-5_37_0
                   SDK MW+Nintendo+Pia-5_37_0_58082
                   SDK MW+Nintendo+PiaFramework-5_37_0
                   SDK MW+Nintendo+PiaLan-5_37_0
                   SDK MW+Nintendo+PiaLocal-5_37_0
                   SDK MW+Nintendo+PiaNex-5_37_0-forNEX-4_6_5
                   SDK MW+Nintendo+PiaReckoning-5_37_0
                   SDK MW+Nintendo+PiaSync-5_37_0
                   SDK MW+Nintendo+NEX_MM-4_6_11
                   SDK MW+Nintendo+PiaClone-5_37_0
00:00:02.046 |I| Loader LoadExeFs: Loading subsdk0...
00:00:02.148 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: multimedia
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-11_4_3-Release
00:00:02.148 |I| Loader LoadExeFs: Loading sdk...
00:00:02.342 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 11.4.3
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-11_4_3-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-11_4_3-Release
                   SDK MW+Nintendo+NintendoSDK_NVN-11_4_3-Release
00:00:02.408 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:02.804 |I| Loader LoadNsos: Loading image 0 at 0x0000000008000000...
00:00:02.809 |I| Loader LoadNsos: Loading image 1 at 0x0000000008004000...
00:00:02.854 |I| Loader LoadNsos: Loading image 2 at 0x000000000cdbd000...
00:00:02.867 |I| Loader LoadNsos: Loading image 3 at 0x000000000d463000...
00:00:02.897 |I| ModLoader LoadCheats: Build ids found for title 0100000011D90000:
    6F8B1226CC8CD958021D6BFD226EBF23F892AB9B000000000000000000000000
    F87FC6075104EC4D9642A4AA6BB2221600000000000000000000000000000000
    507F19D1240D09D00992248E8A0FD77EBD784EB4000000000000000000000000
    2D369D9999E3E10E665106F840FFFF9BDAA0BB8E000000000000000000000000
00:00:02.897 |I| Loader LoadNca: Application Loaded: Pokémon Strahlender Diamant v1.0.0 [0100000011d90000] [64-bit]
00:00:02.920 |I| GUI.WindowThread Hid Configure: Configured Controller JoyconPair to Player1
00:00:03.107 |E| Application : Unhandled exception caught: SPB.Platform.Exceptions.PlatformException: WGL.CreateContext failed for dummy context: 2000
   at SPB.Platform.WGL.WGLHelper.EnsureInit()
   at SPB.Platform.WGL.WGLHelper.CreateContext(IntPtr& windowHandle, FramebufferFormat framebufferFormat, Int32 major, Int32 minor, OpenGLContextFlags flags, Boolean directRendering, IntPtr shareContext)
   at SPB.Platform.WGL.WGLOpenGLContext.Initialize(NativeWindowBase window)
   at Ryujinx.Ui.GlRenderer.IntializeOpenGL()
   at Ryujinx.Ui.GlRenderer.OnDrawn(Context cr)
   at Gtk.Widget.Drawn_cb(IntPtr inst, IntPtr cr)

```
```

**Comment by gdkchan** [comment]
This is not going to work on a VM and the GPU does not meet the minimum requirements.
If you wish to request Mac M1 support feel free to open a separate issue at https://github.com/Ryujinx/Ryujinx/issues
