### ISSUE TITLE
Shin Megami Tensei: Nocturne V 1.0.1 crashes ryujinx

### ISSUE THREAD

**Issue by lmaomax** [Ryujinx/Ryujinx-Games-List#3809]
Shin Megami Tensei: Nocturne

1.0.1

Build 1.0.7176

Starting the game leads to a black screen after which ryujinx crashes immediately.

Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.

Hardware Specs : 
CPU: intel i7-4790k
GPU: NVIDIA GTX 1060 6GB
RAM: 16GB

[Ryujinx_1.0.7176_2022-01-19_23-24-30.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/7898326/Ryujinx_1.0.7176_2022-01-19_23-24-30.log)

**Comment by gdkchan** [comment]
Please use the existing entry for this game #2830.
Also, the error on the log seems to indicate your ROM is corrupted. Consider re-dumping it.
