### ISSUE TITLE
Pokémon Legends: Arceus - 01001F5010DFA000

### ISSUE THREAD

**Issue by armornick** [Ryujinx/Ryujinx-Games-List#3811]
#### Current on `master` :  1.0.7178

The title screen and character creation work perfectly. In-Game, none of the character models are rendered initially. Later, when the capturing tutorial starts, what I assume are the models show up but with incredible distortions. In terms of speed, everything seems to run perfectly and I couldn't hear any audio problems.

#### Screenshots :

![ryujinx_capture_2022-01-20_13-57-29](https://user-images.githubusercontent.com/776169/150344696-3f0fb142-3a1a-453f-a823-d175df610939.png)

![ryujinx_capture_2022-01-20_13-58-24](https://user-images.githubusercontent.com/776169/150344717-5f7466fc-7cbf-4589-98bc-603e7fd07b8d.png)

![ryujinx_capture_2022-01-20_13-59-45](https://user-images.githubusercontent.com/776169/150344739-3bb07765-ea8d-42b8-9b56-fd080f44f70e.png)

![ryujinx_capture_2022-01-20_14-00-34](https://user-images.githubusercontent.com/776169/150344759-12d5265b-5903-4bed-a7fa-5aac63451726.png)

#### Log file :

[Ryujinx_1.0.7178_2022-01-20_13-56-36.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/7905331/Ryujinx_1.0.7178_2022-01-20_13-56-36.log)

**Comment by SylveonBottle** [comment]
Model distortions fixed after purging shader and PPTC caches.

**Comment by SylveonBottle** [comment]
Ground textures becomes excessively reflective when Ghastly is on screen.

https://user-images.githubusercontent.com/17802843/151102469-a5dcc74e-648e-4efe-9fab-9f1f3f897420.mp4

**Comment by MetrosexualGarbodor** [comment]
Please do not open issues for unreleased games.
