### ISSUE TITLE
legende pokemon :arceus

### ISSUE THREAD

**Issue by petil** [Ryujinx/Ryujinx-Games-List#3813]
#### Current on `master` : 1.1.8

lunch / start ; animated 3d object glitched on lnd-2.3 version, didn't go after the introduction.
lunch ryujinx 1.1.8:
HUD: ok
animated 3d: ok
3d: ok
gameplay loop: playable? just started.

```
Last error returned.

```

#### Screenshots :

![ryujinx_capture_2022-01-24_22-22-42](https://user-images.githubusercontent.com/93088523/150867267-fcde37b7-bc28-44cc-bab9-4cf4c58cd7eb.png)

#### Log file :

*Add a link to the log file here.*

*(Optional section, remove it if unneeded)*

**Comment by MetrosexualGarbodor** [comment]
Please do not open issues for unreleased games.
