### ISSUE TITLE
can someone help me please 

### ISSUE THREAD

**Issue by FCT6701** [Ryujinx/Ryujinx-Games-List#3824]
00:00:00.004 |I| Configuration LogValueChange: EnableFileLog set to: True
00:00:00.092 |I| Configuration LogValueChange: BackendThreading set to: On
00:00:00.096 |I| Configuration LogValueChange: ResScale set to: 2
00:00:00.105 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.105 |I| Configuration LogValueChange: MaxAnisotropy set to: 8
00:00:00.108 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.112 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.113 |I| Configuration LogValueChange: EnableVsync set to: False
00:00:00.113 |I| Configuration LogValueChange: EnableShaderCache set to: False
00:00:00.113 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.114 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.114 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.114 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.116 |I| Configuration LogValueChange: AudioBackend set to: OpenAl
00:00:00.116 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.119 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.119 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.119 |I| Configuration LogValueChange: IgnoreMissingServices set to: True
00:00:00.127 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.16
00:00:00.144 |N| Application Print: Operating System: Microsoft Windows 10.0.19044 (X64)
00:00:00.144 |N| Application Print: CPU: AMD Ryzen 5 2600 Six-Core Processor ; 12 logical
00:00:00.146 |N| Application Print: RAM: Total 16335 MB ; Available 13145 MB
00:00:00.150 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.150 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.128 |I| Gpu : Backend Threading (On): True
00:00:00.432 |N| Application LoadApplication: Using Firmware Version: 13.2.1
00:00:00.432 |I| Application LoadApplication: Loading as NSP.
00:00:00.530 |I| ModLoader QueryContentsDir: Searching mods for Title 0100726014352000
00:00:00.559 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:00.605 |I| Loader LoadExeFs: Loading rtld...
00:00:00.745 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.745 |I| Loader LoadExeFs: Loading main...
00:00:00.888 |I| Loader PrintRoSectionInfo: main:
    Module: D:\jenkins\workspace\diablo2_pipeline\build\release_2_3_0\bin\Release\NX64\Game.nss
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libcurl-11_4_3-Release
00:00:00.888 |I| Loader LoadExeFs: Loading subsdk0...
00:00:00.917 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: multimedia
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-11_4_3-Release
00:00:00.917 |I| Loader LoadExeFs: Loading sdk...
00:00:00.979 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 11.4.3
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-11_4_3-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-11_4_3-Release
                   SDK MW+Nintendo+NintendoSDK_NVN-11_4_3-Release
00:00:01.110 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:01.352 |I| Ptc Load: Loaded Translation Cache (size: 15010062 bytes, translated functions: 12348).
00:00:01.367 |I| Ptc Load: Loaded Profiling Info (size: 38491 bytes, profiled functions: 12348).
00:00:01.704 |I| Loader LoadNsos: Loading image 0 at 0x0000000008000000...
00:00:01.707 |I| Loader LoadNsos: Loading image 1 at 0x0000000008004000...
00:00:01.725 |I| Loader LoadNsos: Loading image 2 at 0x000000000af49000...
00:00:01.727 |I| Loader LoadNsos: Loading image 3 at 0x000000000b5ef000...
00:00:01.744 |I| ModLoader LoadCheats: Build ids found for title 0100726014352000:
    6F8B1226CC8CD958021D6BFD226EBF23F892AB9B000000000000000000000000
    DCEDBABB85CB423777F7D044BAEC91D5672A5BA8000000000000000000000000
    507F19D1240D09D00992248E8A0FD77EBD784EB4000000000000000000000000
    2D369D9999E3E10E665106F840FFFF9BDAA0BB8E000000000000000000000000
00:00:01.744 |I| Loader LoadNca: Application Loaded: Diablo® II: ResurrectedT v1.0.0.10 [0100726014352000] [64-bit]
00:00:01.771 |I| GUI.WindowThread Hid Configure: Configured Controller ProController to Player1
00:00:01.947 |I| GUI.WindowThread Hid SetupNpad: Connected Controller ProController to Player1
00:00:02.039 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA Corporation NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2 (4.6.0 NVIDIA 511.65)
00:00:02.315 |I| HLE.GuestThread.14 Ptc LoadTranslations: 12348 translated functions loaded
00:00:02.544 |S| HLE.OsThread.15 ServiceAm GetAppletResourceUserId: Stubbed.
00:00:02.560 |S| HLE.OsThread.15 ServiceAm AcquireForegroundRights: Stubbed.
00:00:02.566 |S| HLE.OsThread.15 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:02.566 |S| HLE.OsThread.15 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:02.578 |S| HLE.OsThread.15 ServicePctl Initialize: Stubbed.
00:00:02.580 |W| HLE.GuestThread.14 KernelSvc PrintResult: SetHeapSize64 returned error ResLimitExceeded.
00:00:02.580 |W| HLE.GuestThread.14 KernelSvc PrintResult: SetHeapSize64 returned error ResLimitExceeded.
00:00:02.580 |W| HLE.GuestThread.14 KernelSvc PrintResult: SetHeapSize64 returned error ResLimitExceeded.
00:00:02.580 |W| HLE.GuestThread.14 KernelSvc PrintResult: SetHeapSize64 returned error ResLimitExceeded.
00:00:02.580 |W| HLE.GuestThread.14 KernelSvc PrintResult: SetHeapSize64 returned error ResLimitExceeded.
00:00:02.580 |W| HLE.GuestThread.14 KernelSvc PrintResult: SetHeapSize64 returned error ResLimitExceeded.
00:00:02.580 |W| HLE.GuestThread.14 KernelSvc PrintResult: SetHeapSize64 returned error ResLimitExceeded.
00:00:02.580 |W| HLE.GuestThread.14 KernelSvc PrintResult: SetHeapSize64 returned error ResLimitExceeded.
00:00:02.580 |W| HLE.GuestThread.14 KernelSvc PrintResult: SetHeapSize64 returned error ResLimitExceeded.
00:00:02.580 |W| HLE.GuestThread.14 KernelSvc PrintResult: SetHeapSize64 returned error ResLimitExceeded.
00:00:02.580 |W| HLE.GuestThread.14 KernelSvc PrintResult: SetHeapSize64 returned error ResLimitExceeded.
00:00:02.580 |W| HLE.GuestThread.14 KernelSvc PrintResult: SetHeapSize64 returned error ResLimitExceeded.
00:00:02.580 |W| HLE.GuestThread.14 KernelSvc PrintResult: SetHeapSize64 returned error ResLimitExceeded.
00:00:02.580 |W| HLE.GuestThread.14 KernelSvc PrintResult: SetHeapSize64 returned error ResLimitExceeded.
00:00:02.580 |W| HLE.GuestThread.14 KernelSvc PrintResult: SetHeapSize64 returned error ResLimitExceeded.
00:00:02.580 |W| HLE.GuestThread.14 KernelSvc PrintResult: SetHeapSize64 returned error ResLimitExceeded.
00:00:02.580 |W| HLE.GuestThread.14 KernelSvc PrintResult: SetHeapSize64 returned error ResLimitExceeded.
00:00:02.580 |W| HLE.GuestThread.14 KernelSvc PrintResult: SetHeapSize64 returned error ResLimitExceeded.
00:00:02.580 |W| HLE.GuestThread.14 KernelSvc PrintResult: SetHeapSize64 returned error ResLimitExceeded.
00:00:02.580 |W| HLE.GuestThread.14 KernelSvc PrintResult: SetHeapSize64 returned error ResLimitExceeded.
00:00:02.580 |W| HLE.GuestThread.14 KernelSvc PrintResult: SetHeapSize64 returned error ResLimitExceeded.
00:00:02.580 |W| HLE.GuestThread.14 KernelSvc PrintResult: SetHeapSize64 returned error ResLimitExceeded.
00:00:02.580 |W| HLE.GuestThread.14 KernelSvc PrintResult: SetHeapSize64 returned error ResLimitExceeded.
00:00:02.580 |W| HLE.GuestThread.14 KernelSvc PrintResult: SetHeapSize64 returned error ResLimitExceeded.
00:00:02.580 |W| HLE.GuestThread.14 KernelSvc PrintResult: SetHeapSize64 returned error ResLimitExceeded.
00:00:02.580 |W| HLE.GuestThread.14 KernelSvc PrintResult: SetHeapSize64 returned error ResLimitExceeded.
00:00:02.580 |W| HLE.GuestThread.14 KernelSvc PrintResult: SetHeapSize64 returned error ResLimitExceeded.
00:00:02.580 |W| HLE.GuestThread.14 KernelSvc PrintResult: SetHeapSize64 returned error ResLimitExceeded.
00:00:02.580 |W| HLE.GuestThread.14 KernelSvc PrintResult: SetHeapSize64 returned error ResLimitExceeded.
00:00:02.580 |W| HLE.GuestThread.14 KernelSvc PrintResult: SetHeapSize64 returned error ResLimitExceeded.
00:00:02.580 |W| HLE.GuestThread.14 KernelSvc PrintResult: SetHeapSize64 returned error ResLimitExceeded.
00:00:02.580 |W| HLE.GuestThread.14 KernelSvc PrintResult: SetHeapSize64 returned error ResLimitExceeded.
00:00:02.580 |W| HLE.GuestThread.14 KernelSvc PrintResult: SetHeapSize64 returned error ResLimitExceeded.
00:00:02.580 |W| HLE.GuestThread.14 KernelSvc PrintResult: SetHeapSize64 returned error ResLimitExceeded.
00:00:04.316 |S| HLE.OsThread.5 ServiceBsd RegisterClient: Stubbed.
00:00:04.319 |S| HLE.OsThread.5 ServiceBsd StartMonitoring: Stubbed. {unknown0: 0}
00:00:04.458 |I| HLE.OsThread.15 ServiceNifm GetCurrentIpAddress: Console's local IP is "192.168.0.230".
00:00:04.465 |I| HLE.OsThread.15 ServiceSfdnsres GetAddrInfoRequestImpl: Guest network access disabled, DNS Blocked: 192.168.0.230
00:00:04.488 |S| HLE.OsThread.15 ServiceSsl SetInterfaceVersion: Stubbed. {interfaceVersion: 3}
00:00:04.499 |G| HLE.OsThread.15 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 4s
    Line: 0
    Filename: ''
    Function: ''
    Module: ''
    Thread: 'Main'
    ProgramName: 'Game'
    Message: 'tact root directory: $:/'

00:00:04.661 |G| HLE.OsThread.15 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 4s
    Line: 0
    Filename: ''
    Function: ''
    Module: ''
    Thread: 'Main'
    ProgramName: 'Game'
    Message: 'locale overlay directory: locales/data/deDE/data/local'

00:00:04.662 |G| HLE.OsThread.15 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 4s
    Line: 0
    Filename: ''
    Function: ''
    Module: ''
    Thread: 'Main'
    ProgramName: 'Game'
    Message: 'locale audio overlay directory: locales/audio/deDE/data/local'

00:00:04.662 |G| HLE.OsThread.15 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 4s
    Line: 0
    Filename: ''
    Function: ''
    Module: ''
    Thread: 'Main'
    ProgramName: 'Game'
    Message: 'locale overlay directory: locales/data/deDE/data/hd/local'

00:00:04.662 |G| HLE.OsThread.15 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 4s
    Line: 0
    Filename: ''
    Function: ''
    Module: ''
    Thread: 'Main'
    ProgramName: 'Game'
    Message: 'locale overlay directory: locales/data/deDE/data/hd/global/video'

00:00:04.662 |G| HLE.OsThread.15 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 4s
    Line: 0
    Filename: ''
    Function: ''
    Module: ''
    Thread: 'Main'
    ProgramName: 'Game'
    Message: 'locale audio overlay directory: locales/audio/deDE/data/hd/local'

00:00:04.662 |G| HLE.OsThread.15 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 4s
    Line: 0
    Filename: ''
    Function: ''
    Module: ''
    Thread: 'Main'
    ProgramName: 'Game'
    Message: '<BUILD>67581</BUILD>'

00:00:04.662 |G| HLE.OsThread.15 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 4s
    Line: 0
    Filename: ''
    Function: ''
    Module: ''
    Thread: 'Main'
    ProgramName: 'Game'
    Message: '<CONFIG>Release</CONFIG>'

00:00:04.662 |G| HLE.OsThread.15 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 4s
    Line: 0
    Filename: ''
    Function: ''
    Module: ''
    Thread: 'Main'
    ProgramName: 'Game'
    Message: '<REGION>Global</REGION>'

00:00:04.665 |S| HLE.OsThread.8 ServiceHid ActivateTouchScreen: Stubbed. {appletResourceUserId: 1}
00:00:04.677 |I| HLE.OsThread.15 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:04.680 |I| HLE.OsThread.15 SurfaceFlinger CreateLayerFromId: Creating layer 2
00:00:04.692 |S| HLE.OsThread.15 ServiceAcc InitializeApplicationInfo: Stubbed. {TitleId: 72183351019380736}
00:00:04.695 |S| HLE.OsThread.15 ServiceAcc IsUserAccountSwitchLocked: Stubbed.
00:00:04.698 |S| HLE.OsThread.15 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:04.698 |S| HLE.OsThread.15 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:04.698 |S| HLE.OsThread.15 ServiceAm SetRestartMessageEnabled: Stubbed. {restartMessageEnabled: True}
00:00:04.698 |S| HLE.OsThread.15 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: True ; unknownFlag2: True ; unknownFlag3: False}
00:00:04.698 |S| HLE.OsThread.15 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:04.704 |S| HLE.OsThread.15 ServiceAcc CheckAvailability: Stubbed.
00:00:04.704 |S| HLE.OsThread.15 ServiceAcc GetAccountId: Stubbed. {NetworkServiceAccountId: 51966}
00:00:04.705 |S| HLE.OsThread.9 ServiceNv FinishInitialize: Stubbed.
00:00:04.726 |G| HLE.OsThread.15 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 4s
    Line: 0
    Filename: ''
    Function: ''
    Module: ''
    Thread: 'Thread_0x00000000098CB340'
    ProgramName: 'Game'
    Message: '[SaveSystem]: Mounting Settings at save:/Settings in mode 2'

00:00:04.727 |G| HLE.OsThread.15 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 4s
    Line: 0
    Filename: ''
    Function: ''
    Module: ''
    Thread: 'Thread_0x00000000098CB340'
    ProgramName: 'Game'
    Message: '[SaveSystem]: Created save file Settings.json in container Settings'

00:00:04.732 |G| HLE.OsThread.15 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 4s
    Line: 0
    Filename: ''
    Function: ''
    Module: ''
    Thread: 'Thread_0x00000000098CB340'
    ProgramName: 'Game'
    Message: '[SaveSystem]: Unmounting Settings'

00:00:04.734 |S| HLE.OsThread.9 ServiceNv InitializeEx: Stubbed.
00:00:04.766 |I| HLE.OsThread.9 ServiceNv Create: Created map 1 with size 0x00001000!
00:00:04.785 |I| HLE.OsThread.9 ServiceNv Create: Created map 2 with size 0x00010000!
00:00:04.787 |S| HLE.OsThread.9 ServiceNv GetActiveSlotMask: Stubbed.
00:00:04.788 |I| HLE.OsThread.9 ServiceNv Create: Created map 3 with size 0x10400000!
00:00:04.799 |I| HLE.OsThread.9 ServiceNv Create: Created map 4 with size 0x00a00000!
00:00:04.799 |I| HLE.OsThread.9 ServiceNv Create: Created map 5 with size 0x19000000!
00:00:04.801 |I| HLE.OsThread.9 ServiceNv Create: Created map 6 with size 0x00100000!
00:00:04.801 |I| HLE.OsThread.9 ServiceNv Create: Created map 7 with size 0x2c600000!
00:00:04.829 |I| HLE.OsThread.9 ServiceNv Create: Created map 8 with size 0x00200000!
00:00:04.830 |I| HLE.OsThread.9 ServiceNv Create: Created map 9 with size 0x02800000!
00:00:04.831 |I| HLE.OsThread.9 ServiceNv Create: Created map 10 with size 0x00001000!
00:00:04.916 |S| HLE.OsThread.9 ServiceNv SetNvMapFd: Stubbed.
00:00:04.916 |S| HLE.OsThread.9 ServiceNv AllocGpfifoEx2: Stubbed.
00:00:04.916 |S| HLE.OsThread.9 ServiceNv AllocObjCtx: Stubbed.
00:00:04.917 |S| HLE.OsThread.9 ServiceNv SetErrorNotifier: Stubbed.
00:00:04.917 |S| HLE.OsThread.9 ServiceNv SetUserData: Stubbed.
00:00:04.917 |S| HLE.OsThread.9 ServiceNv SetTimeout: Stubbed.
00:00:04.918 |S| HLE.OsThread.9 ServiceNv SetTimeslice: Stubbed.
00:00:04.918 |I| HLE.OsThread.9 ServiceNv Create: Created map 11 with size 0x00010000!
00:00:04.918 |I| HLE.OsThread.9 ServiceNv Create: Created map 12 with size 0x0004b000!
00:00:04.919 |S| HLE.OsThread.9 ServiceNv ZcullBind: Stubbed.
00:00:04.924 |I| HLE.OsThread.9 ServiceNv Create: Created map 13 with size 0x00001000!
00:00:04.927 |S| HLE.OsThread.9 ServiceNv SetNvMapFd: Stubbed.
00:00:04.927 |S| HLE.OsThread.9 ServiceNv AllocGpfifoEx2: Stubbed.
00:00:04.927 |S| HLE.OsThread.9 ServiceNv AllocObjCtx: Stubbed.
00:00:04.927 |S| HLE.OsThread.9 ServiceNv SetErrorNotifier: Stubbed.
00:00:04.927 |S| HLE.OsThread.9 ServiceNv SetUserData: Stubbed.
00:00:04.927 |S| HLE.OsThread.9 ServiceNv SetTimeout: Stubbed.
00:00:04.927 |S| HLE.OsThread.9 ServiceNv SetTimeslice: Stubbed.
00:00:04.927 |I| HLE.OsThread.9 ServiceNv Create: Created map 14 with size 0x00010000!
00:00:04.928 |I| HLE.OsThread.9 ServiceNv Create: Created map 15 with size 0x0004b000!
00:00:04.928 |S| HLE.OsThread.9 ServiceNv ZcullBind: Stubbed.
00:00:04.928 |I| HLE.OsThread.9 ServiceNv Create: Created map 16 with size 0x00001000!
00:00:04.933 |S| HLE.OsThread.9 ServiceNv SetNvMapFd: Stubbed.
00:00:04.933 |S| HLE.OsThread.9 ServiceNv AllocGpfifoEx2: Stubbed.
00:00:04.933 |S| HLE.OsThread.9 ServiceNv AllocObjCtx: Stubbed.
00:00:04.933 |S| HLE.OsThread.9 ServiceNv SetErrorNotifier: Stubbed.
00:00:04.933 |S| HLE.OsThread.9 ServiceNv SetUserData: Stubbed.
00:00:04.933 |S| HLE.OsThread.9 ServiceNv SetTimeout: Stubbed.
00:00:04.933 |S| HLE.OsThread.9 ServiceNv SetTimeslice: Stubbed.
00:00:04.933 |I| HLE.OsThread.9 ServiceNv Create: Created map 17 with size 0x00010000!
00:00:04.934 |I| HLE.OsThread.9 ServiceNv Create: Created map 18 with size 0x0004b000!
00:00:04.934 |S| HLE.OsThread.9 ServiceNv ZcullBind: Stubbed.
00:00:05.746 |W| HLE.OsThread.9 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:00:06.005 |S| HLE.OsThread.8 ServiceHid ActiveNpadImpl: Stubbed. {appletResourceUserId: 1 ; revision: 3}
00:00:06.006 |S| HLE.OsThread.8 ServiceHid SetSupportedNpadStyleSet: Stubbed. {appletResourceUserId: 4294967296 ; type: ProController, Handheld}
00:00:06.007 |S| HLE.OsThread.8 ServiceHid SetNpadHandheldActivationMode: Stubbed. {appletResourceUserId: 1 ; _npadHandheldActivationMode: Dual}
00:00:06.012 |S| HLE.OsThread.8 ServiceHid SetSupportedNpadIdType: Stubbed. 2 Player1,Handheld
00:00:06.035 |I| HLE.OsThread.7 AudioRenderer AcquireSessionId: Registered new output (0)
00:00:07.264 |G| HLE.OsThread.15 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 7s
    Line: 0
    Filename: ''
    Function: ''
    Module: ''
    Thread: 'Main'
    ProgramName: 'Game'
    Message: '[CommandDefinition]: Could not find ExecuteCommandCallback: Help'

00:00:07.279 |S| HLE.OsThread.15 ServiceAm GetPseudoDeviceId: Stubbed.
00:00:07.284 |S| HLE.OsThread.5 ServiceBsd Select: Stubbed.
00:00:07.286 |S| HLE.OsThread.5 ServiceBsd Select: Stubbed.
00:00:07.385 |S| HLE.OsThread.15 ServiceAm GetPseudoDeviceId: Stubbed.

**Comment by MetrosexualGarbodor** [comment]
Please come to Discord for help, this log is not enough to determine the problem. https://discord.com/channels/410208534861447168/411271165429022730/771741763375071252
