### ISSUE TITLE
Kirby and the Forgotten Lands - 01004D300C5AE000

### ISSUE THREAD

**Issue by ZeeCas** [Ryujinx/Ryujinx-Games-List#3865]
#### Build Version : *1.1.83*

*Game plays perfectly, with minimal stutters due to what i assume is shader caching.*

```
Last error returned.
00:19:31.850 |E| GPU.MainThread Gpu GetInfo: Invalid texture format 0x7FFFF (sRGB: False). 
```

#### Screenshots :

*https://postimg.cc/7b4MKCzg*

**Comment by CrusadingNinja** [comment]
Release date is March 25... leaked games aren't supported here.
