### ISSUE TITLE
Audio Renderer Issue: Unmapping pool failed

### ISSUE THREAD

**Issue by koalajaden** [Ryujinx/Ryujinx-Games-List#3874]
#### Current on `master` : 01000a10041ea000

*Describe the current game state here.*
crashing on start
```
Last error returned.
00:00:12.604 |E| HLE.OsThread.6 AudioRenderer Update: Unmap of memory pool (address: 0x1c63c3000, size 0xa000) failed!
```

##### RAM: 32GB

Log:
https://pastebin.com/dwHFxK1V

**Comment by MetrosexualGarbodor** [comment]
Please post this in #1536 or the main Ryujinx issue tracker.
