### ISSUE TITLE
Legend of Zelda Particles

### ISSUE THREAD

**Issue by WeekendGamez12** [Ryujinx/Ryujinx-Games-List#3883]
#### Current on `master` : Commit Id *or* Build Version : *(e.g. 0a41a3ff or 1.0.1952)*

*Describe the current game state here.*

```
Last error returned.
e.g.: Unhandled Exception: System.NotImplementedException: /dev/nvhost-nvdec 40044801
```

#### Pull requests needed :

*Add needed PR links here.*

*(Optional section, remove it if unneeded)*

#### Outstanding Issues:

*Add issue links here.*

*Example: https://github.com/Ryujinx/Ryujinx/issues/xxx (xxx = number issue)*

*(Optional section, remove it if unneeded)*

#### Screenshots :

*Add screenshots here if the game rendering something.*

*(Optional section, remove it if unneeded)*

#### Log file :

*Add a link to the log file here.*

*(Optional section, remove it if unneeded)*

Whenever I die, for about 20 minutes, I get this (see attachments) extremely supercharged particle effects.
![Screenshot 2022-04-22 161202](https://user-images.githubusercontent.com/92956689/164787084-d623780b-adbc-41a9-a3bc-dc8340a3195f.png)

**Comment by MetrosexualGarbodor** [comment]
Please open this in the main Ryujinx issues repository, and make it more detailed.
