### ISSUE TITLE
Graphics Issue

### ISSUE THREAD

**Issue by CLAndroidz** [Ryujinx/Ryujinx-Games-List#3894]
#### 1.1.121

I'm getting graphical issues while playing.  The screen goes almost all white.  It will fix itself for a little while when I transport.  I've got 18 hrs or so in the game so this just started randomly.  I don't know if it's a shader issue or what I can do to fix it.  I was really enjoying the game, so I'd love any help I can get.

```
####Last error returned:

No errors are showing up in the log.
```

#### Screenshots :
https://ibb.co/pvGwfmD
https://ibb.co/CV8qdyD
https://ibb.co/q9cx7Sp

*(Optional section, remove it if unneeded)*

#### Log file :
![ryujinx_capture_2022-05-14_12-26-56](https://user-images.githubusercontent.com/44037711/168442416-0f1047c9-8676-48f4-964e-63b4fd3d337e.png)
![ryujinx_capture_2022-05-14_12-27-22](https://user-images.githubusercontent.com/44037711/168442418-478dfcce-53c0-495d-9752-900a60cf1443.png)
![ryujinx_capture_2022-05-14_13-25-37](https://user-images.githubusercontent.com/44037711/168442419-101719a1-12b4-4f24-a5ed-3c7486eec08d.png)

**Comment by MetrosexualGarbodor** [comment]
Please don't open issues for support, ask in discord instead. https://discord.gg/ryujinx

**Comment by CLAndroidz** [comment]
Will do, thank you.
