### ISSUE TITLE
Stanley Parable Ultra Deluxe

### ISSUE THREAD

**Issue by Forzooo** [Ryujinx/Ryujinx-Games-List#3899]
Stanley Parable Ultra Deluxe isn't recognized by Ryujinx.
Application: unknown 0000000000000000
File Extension: NSP

**Comment by edisionnano** [comment]
you may wanna come to the discord server for help, this repo isn't the right one for this and neither is the issue format right here

**Comment by Eli0t77** [comment]
You probably have a bad dump. The game works fine for me (60fps) on 1.1.109 (the last full fat windows 7 version)
Played a few endings and the only bug I can see is the text is missing from the text boxes after the opening credits

Game version tested: v1 and v1.04
In keeping with the rest of the game list the title should be
The Stanley Parable: Ultra Deluxe - 010029300E5C4000

CPU i5 2500k @ 4.4ghz
GPU GTX 560 ti
OS Windows 7

![Stanley](https://user-images.githubusercontent.com/99099894/171068565-412cd60a-ee5b-44bc-ae52-b29c35e7458a.jpg)

Missing text in the text boxes after the opening credits
![StanleyTextbox](https://user-images.githubusercontent.com/99099894/171068650-64fb20e8-6283-4975-adef-3d5ec0e2680c.jpg)
