### ISSUE TITLE
二ノ国 白き聖灰の女王-010032400E700000

### ISSUE THREAD

**Issue by taiwan-king** [Ryujinx/Ryujinx-Games-List#3905]
二ノ国 白き聖灰の女王

Game Update Version : 1.0.2
Current on master : 1.1.142

game crash!

Hardware Specs :
CPU: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz
GPU:NVIDIA GeForce GTX 970
Operating System: Microsoft Windows 10.0.18363 (X64)
RAM : 16GB

Screenshots:
![1654661844782](https://user-images.githubusercontent.com/24381898/172530593-44512624-8742-4649-9726-c743d0e82a01.jpg)

Log:
[Ryujinx_1.1.142_2022-06-08_12-13-57.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/8858253/Ryujinx_1.1.142_2022-06-08_12-13-57.log)

**Comment by MetrosexualGarbodor** [comment]
Duplicate of #980.

**Comment by embraceyan** [comment]
looking forward to a fix

**Comment by taiwan-king** [comment]
Game Update Version : 1.0.2
Current on master : 1.1.159

same issue.

Hardware Specs :
CPU: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz
GPU:NVIDIA GeForce GTX 970
Operating System: Microsoft Windows 10.0.18363 (X64)
RAM : 16GB

**Comment by taiwan-king** [comment]
Game Update Version : 1.0.2
Current on master : 1.1.596

same status.

Hardware Specs :
CPU: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz
GPU:NVIDIA GeForce GTX 970
Operating System: Microsoft Windows 10.0.18363 (X64)
RAM : 16GB

**Comment by embraceyan** [comment]
还是玩不了呀，加油加油
&nbsp;


stone
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月27日(星期五) 中午1:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Ryujinx/Ryujinx-Games-List] 二ノ国 白き聖灰の女王 - 010032400E700000 (Issue #3905)






游戏更新版本：1.0.2
主机上的电流：1.1.596

一样的状态。

硬件规格：
中央处理器：英特尔至强（右）中央处理器E3-1231 ***@***.***
图形处理器：NVIDIA GeForce GTX 970
操作系统：微软视窗10.0.18363(X64)
内存：16GB

—
直接回复此邮件，在GitHub上查看或取消订阅.
***@***.***与&gt;.

**Comment by embraceyan** [comment]
感觉不应该是很大的问题导致的呀，目前玩不了的游戏不多的，奇怪
&nbsp;


stone
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月27日(星期五) 中午1:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Ryujinx/Ryujinx-Games-List] 二ノ国 白き聖灰の女王 - 010032400E700000 (Issue #3905)






游戏更新版本：1.0.2
主机上的电流：1.1.596

一样的状态。

硬件规格：
中央处理器：英特尔至强（右）中央处理器E3-1231 ***@***.***
图形处理器：NVIDIA GeForce GTX 970
操作系统：微软视窗10.0.18363(X64)
内存：16GB

—
直接回复此邮件，在GitHub上查看或取消订阅.
***@***.***与&gt;.

**Comment by superyxf2000** [comment]
我的也是，最新的ava-ryujinx-1.1.650-win_x64版本，还是玩不了 二之国的游戏，出现一样的问题，进入游戏后的3D场景不能正常显示（黑色状态），2D图形、声音等却都正常。
