### ISSUE TITLE
hbmenu: 0000000000000000

### ISSUE THREAD

**Issue by Saturn345** [Ryujinx/Ryujinx-Games-List#3921]
## Game Name
nx-hbmenu
#### Game Update Version : *(e.g. 1.0.0 or 1.1.3)*
3.5.1
#### Current on `master` : Commit Id *or* Build Version : *(e.g. 0a41a3ff or 1.0.1952)*
1.0.159
*Describe the current game state here.*
It just crashes on load.
```
Last error returned.
```
--> System.IO.IOException: Read-only file system : '/home/cog/Desktop/Nintendo Switch Games/Homebrew/hbmenu.nro'

##### CPU: *(e.g. i7-6700)*
CPU: i3-1005G1
##### GPU: *(e.g. NVIDIA RTX 2070)*
GPU: Mesa Intel® UHD Graphics (ICL GT1)
##### RAM: *(e.g. 16GB)*
RAM: 8GB

#### Log file :

*Add a link to the log file here.*
[Ryujinx_1.1.159_2022-06-26_08-40-58.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/8986631/Ryujinx_1.1.159_2022-06-26_08-40-58.log)

**Comment by MutantAura** [comment]
Closing in favour of #3925 as this error appears to be system specific and is missing some details.
