### ISSUE TITLE
Rabbids: Party of Legends - 01008970149B0000

### ISSUE THREAD

**Issue by rareshadow** [Ryujinx/Ryujinx-Games-List#3931]
#### Current on `master` : 1.1.161

characters freeze at random on any of the rolling based mini games (e.x.: "Hatched from Stone Eggs" or "The Bull Fight." Logs do not show any errors. Game is unable to be continued.

![image](https://user-images.githubusercontent.com/62297085/177025335-30e3a5fc-b228-4840-b3d0-fc447640f658.png)

**Comment by EmulationFanatic** [comment]
Without any details on the hardware used, nor a log file to extract such information, this submission is incomplete. Please resubmit this game test, following the template and providing all necessary information for a valid test.
