### ISSUE TITLE
Xenoblade Chronicles 3 - 010074F013262000

### ISSUE THREAD

**Issue by Renari** [Ryujinx/Ryujinx-Games-List#3949]
#### Current on `master` : 1.1.182

`status-menus`: Unplayable, crashes after intro cutscene.

```
Unhandled exception caught: System.ArgumentException: An item with the same key has already been added. Key: Ryujinx.Graphics.Shader.Decoders.Block
```

#### Log file :
[Ryujinx_1.1.182_2022-07-23_01-00-07.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9174667/Ryujinx_1.1.182_2022-07-23_01-00-07.log)

**Comment by gdkchan** [comment]
Hello, please do not open issues for leaked games. Also you're using an outdated build. Thanks for understanding.
