### ISSUE TITLE
What?

### ISSUE THREAD

**Issue by fancymelonub** [Ryujinx/Ryujinx-Games-List#4]
Unrelated but, it seems the box art here is the old one before the uhhhh..... "controversy".

**Comment by AcK77** [comment]
You speak about what game?

**Comment by zoltx23** [comment]
This is not exactly the place for this. If you wish you may take this over to our Discord server. 

Also, I don't see any of the _box art_ that is old or outdated. Nor do I know of any controversy over this topic.
