### ISSUE TITLE
Cardfight Vanguard Ex

### ISSUE THREAD

**Issue by kari19suzu** [Ryujinx/Ryujinx-Games-List#4020]
Works perfectly imo

**Comment by MetrosexualGarbodor** [comment]
Can you please follow the template?

**Comment by kari19suzu** [comment]
what template?

**Comment by MetrosexualGarbodor** [comment]
The template for game issues that shows when you try to open one.

**Comment by kari19suzu** [comment]
that was not here when i opened it it wa sjust as blank as i am currently typing so taking that as a note i'm a just not. do it. someone else will do it eventually.

**Comment by EmulationFanatic** [comment]
> that was not here when i opened it it wa sjust as blank as i am currently typing so taking that as a note i'm a just not. do it. someone else will do it eventually.

The template is present in every new issue. You would've had to delete all of it in order to get a blank post. But don't worry, we know you aren't going to do it.

**Comment by kari19suzu** [comment]
you guys can believe what you want. I'm telling you it wanst here. But alright. Fucks yall.
