### ISSUE TITLE
Mortal Kombat 11 Ultimate

### ISSUE THREAD

**Issue by momoids** [Ryujinx/Ryujinx-Games-List#4023]
Mortal Kombat 11 Ultimate

Game Update Version : (1.0.26)

Emulator Build Version : ryujinx-1.1.254-win_x64

#### Graphics Backend : Vulkan or OpenGL

when I play MK 11 with (update 1.0.26) the Scorpion spear does not appear, but in the base version (1.0.0) it appears normally! Another problem I noticed was that even using Upscale there is no resolution increase effectively! (I'm not native English!)

bugs not fixed to date: no upscale; Scorpion's spear disappears in ultimate version;
![image](https://user-images.githubusercontent.com/70231770/189358320-2f1d42ee-27d6-4560-81dc-85e61eefa021.png)
![image](https://user-images.githubusercontent.com/70231770/189358354-d87b5b44-abfd-4278-994b-d960bbc7c872.png)
![image](https://user-images.githubusercontent.com/70231770/189358379-33082610-64bd-42a6-9b7f-f23f18fa7fcb.png)
![image](https://user-images.githubusercontent.com/70231770/189358409-1c587a9d-1a7c-4bc6-bff8-36a36d3914c6.png)
![image](https://user-images.githubusercontent.com/70231770/189358460-48ca539f-cabc-40be-b0f5-de1713e1329d.png)
![image](https://user-images.githubusercontent.com/70231770/189358498-d4d297c2-c722-4bac-a82a-ee8014c644a8.png)

Ryujinx version: ryujinx-1.1.254-win_x64

Game version: update 1.0.26

System Specs:

OS: Windows10 x64
CPU: Ryzen 1600x
GPU: GTX 1060 6GB
RAM: 32 GB
Applied Mods : No

**Comment by EmulationFanatic** [comment]
Please post this as a reply on the original issue https://github.com/Ryujinx/Ryujinx-Games-List/issues/165
