### ISSUE TITLE
No 3D model any fixes?

### ISSUE THREAD

**Issue by CraftyArmy** [Ryujinx/Ryujinx-Games-List#4052]
Game Update Version : 1.0.2
Current on master : 1.1.282

No 3D model for Yo-kai and Bugs 

Hardware Specs :
CPU: I7 12700k
GPU: RTX 3060 TI
RAM: 16GB

Screenshots :
![image](https://user-images.githubusercontent.com/46542969/193181755-323a7a50-ab7b-49bd-b404-365634dbe8cc.png)

**Comment by MaTube** [comment]
Idk why this is closed, but unfortunately this problem still exists.

if there is any way to find the problem, i would love to help if you need any files for it to find the cause
