### ISSUE TITLE
Dragon Quest X: Mezameshi Itsustu no Shuzoku Offline - 0100E2E0152E4000

### ISSUE THREAD

**Issue by ekfacile** [Ryujinx/Ryujinx-Games-List#4055]
## Game Name

ドラゴンクエストⅩ 目覚めし五つの種族 オフライン

#### Graphics Backend : OpenGL

I played a total of 5 hours with the initial start and existing save data, but there are no particular problems.

Note: [A rare error that occurs during emulation termination doesn't seem to be fixed.](https://github.com/Ryujinx/Ryujinx/pull/3733)

```
00:19:11.608 |E| HLE.OsThread.13 SurfaceFlinger DequeueBuffer: No available buffer slots
00:19:11.609 |E| HLE.OsThread.13 SurfaceFlinger OnTransact: Error returned by transaction DequeueBuffer: Busy
```

#### Screenshots :

Initial start:

![01_q99](https://user-images.githubusercontent.com/62389564/194210835-e11aedf6-c53a-4c39-87e7-c5363830e5fe.jpg)

![02_q99](https://user-images.githubusercontent.com/62389564/194210846-40ea77eb-bddb-476e-88c8-ac7a7779430f.jpg)

![03_q99](https://user-images.githubusercontent.com/62389564/194210862-717f7bbd-6478-49b9-9afe-ad3955c39cd3.jpg)

![04_q99](https://user-images.githubusercontent.com/62389564/194210870-e3775dda-42da-4959-9c14-ef5d053e7952.jpg)

![05_q99](https://user-images.githubusercontent.com/62389564/194210885-5adb6d55-06de-4da3-94f6-8ab009b91614.jpg)

![06_q99](https://user-images.githubusercontent.com/62389564/194210894-7ef6de72-c27c-474f-93be-7b2f747298e0.jpg)

![07_q99](https://user-images.githubusercontent.com/62389564/194210904-fac40794-3095-4a3d-9f4d-cb3297aa61ba.jpg)

![08_q99](https://user-images.githubusercontent.com/62389564/194210913-44474024-0984-40f5-9e82-24d97b66877b.jpg)

![09_q99](https://user-images.githubusercontent.com/62389564/194210938-131c63a5-7d63-45c4-b5dd-1dcfeeb3d372.jpg)

![10_q99](https://user-images.githubusercontent.com/62389564/194210955-d0b5b730-31bb-4b0a-bf6b-cc16012fd4fc.jpg)

![11_q99](https://user-images.githubusercontent.com/62389564/194210968-a22d9ece-08ef-4336-a80a-f76c3b68e5fc.jpg)

![12_q99](https://user-images.githubusercontent.com/62389564/194210978-0452e98e-dddf-4458-a5ac-3ab28b04347b.jpg)

Existing save data:

![21_q99](https://user-images.githubusercontent.com/62389564/194211015-33a18255-6a6c-44ba-80d7-35a1ef67e868.jpg)

![22_q99](https://user-images.githubusercontent.com/62389564/194211029-31a08342-c453-4531-a057-cfb732ec5434.jpg)

![23_q99](https://user-images.githubusercontent.com/62389564/194211040-e747e952-5512-4ee4-9127-58db4758db9e.jpg)

![24_q99](https://user-images.githubusercontent.com/62389564/194211062-272412bd-436b-42ca-8f23-a9b48514ebe4.jpg)

![25_q99](https://user-images.githubusercontent.com/62389564/194211073-775ef201-2bd7-4284-bed4-4488cafa3551.jpg)

#### Log file :

- [Ryujinx_1.1.295_0100E2E0152E4000_InitialStart_OpenGL.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9721056/Ryujinx_1.1.295_0100E2E0152E4000_InitialStart_OpenGL.log)
- [Ryujinx_1.1.295_0100E2E0152E4000_ExistingSaveData_OpenGL.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9721066/Ryujinx_1.1.295_0100E2E0152E4000_ExistingSaveData_OpenGL.log)

**Comment by EmulationFanatic** [comment]
> Sorry, the crash on writing the file was caused by the anti-virus software. It doesn't crash now.
> 
> However, we do not guarantee that there will be no problems other than writing files. This time, only the improvement for the above crash is reported.

Thanks for the update. When you have time, can you fully re-test to see if the game is playable now?

**Comment by MetrosexualGarbodor** [comment]
Superseded by #4434
