### ISSUE TITLE
Bayonetta 3 Compatability

### ISSUE THREAD

**Issue by big-gay-lambchop** [Ryujinx/Ryujinx-Games-List#4124]
Perfectly compatible if you enable 'ignore missing services'; the game attempts to connect to a platinum server and upload / download play history from other players in the form of a leaderboard. 

Stutters when loading models into the game for the first time, expect some crashing in certain parts of the game. This can be remedied by pausing the emulation and letting the models load one at a time. Biggest offender is the Cairo level, it has to load a giant pyramid / windmill temple and loads of level geometry at once. pause emulation during the stutter and it wont crash.

Framerate runs at a mostly steady pace, dips heavily in kaiju segments.

**Comment by MutantAura** [comment]
Please follow the compatibility report template provided and re-open an issue with all the correct information.
