### ISSUE TITLE
Zelda BotW Crashes

### ISSUE THREAD

**Issue by EasyDIDit** [Ryujinx/Ryujinx-Games-List#4162]
Ive noticed that the game crashed every time i get close to a Lynel. idk if that is due to the amount of code they require but it happens consistently with different Lynels. not savvy enough to know how to fix it but it is defiantly what I've observed

**Comment by EmulationFanatic** [comment]
Please post comments like these on the existing game issue.

**Comment by EasyDIDit** [comment]
I'm sorry thought I did. I will try to fix it
