### ISSUE TITLE
Pokemon Scarlet - 0100A3D008C5C000

### ISSUE THREAD

**Issue by adrimax11** [Ryujinx/Ryujinx-Games-List#4178]
#### Graphics Backend : *(Vulkan)*

*Describe the current game state here.*

The game have a yellow filter.
The textures of 3d models such as pokemon or characters are bug.

#### Screenshots :
The yellow filter and the character model bug
![imagen](https://user-images.githubusercontent.com/86915360/201100094-f6077b72-977d-4cac-8bd6-1d83c2b8b9cf.png)
In battle
![imagen](https://user-images.githubusercontent.com/86915360/201100562-8fb668a7-ab32-4d11-8c9b-bce35b05412b.png)

#### Log file :
[Ryujinx_1.1.339_2022-11-10_13-59-50.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9980965/Ryujinx_1.1.339_2022-11-10_13-59-50.log)

**Comment by MetrosexualGarbodor** [comment]
Please do not open issues for unreleased games.
