### ISSUE TITLE
Pokèmon Scarlet - 0100A3D008C5C800

### ISSUE THREAD

**Issue by totallynotfbi** [Ryujinx/Ryujinx-Games-List#4181]
#### Graphics Backend : Vulkan

Enters ingame, but has a few graphical issues and minor stuttering in cutscenes (photos attached)

```
Last warning returned:
GUI.RenderLoop Gpu TryGetGraphicsPipeline: Background pipeline compile missed on draw - incorrect pipeline state?
```

#### Screenshots :

![Ryujinx_FZoqSuM1hp](https://user-images.githubusercontent.com/117980993/201311415-93f1380b-d62e-4317-926b-8fdf27a41494.png)
![Ryujinx_Bfvxn5VgLU](https://user-images.githubusercontent.com/117980993/201311423-5ef3546d-4011-4cec-9338-d45846049f5c.png)

**Comment by totallynotfbi** [comment]
Not sure how to add labels, sorry

**Comment by MetrosexualGarbodor** [comment]
Do not open issues for unreleased games.
