### ISSUE TITLE
Super Mario Odyssey - 0100000000010000

### ISSUE THREAD

**Issue by boazvdwansem** [Ryujinx/Ryujinx-Games-List#4213]
#### Graphics Backend : Vulkan

The game is perfectly playable with a stable 60 frames per second. The only problem is some graphical bugs, the most notable of which is the water as seen on the screenshots.

#### Screenshots :

![Screenshot 2022-11-16 175129](https://user-images.githubusercontent.com/55191679/202243557-eddb2ea2-3dd2-46ee-bf2f-7cd93a4c9998.png)

![Screenshot 2022-11-16 175241](https://user-images.githubusercontent.com/55191679/202243572-d2706867-7a01-438c-8a43-b733628f15a9.png)

![Screenshot 2022-11-16 175325](https://user-images.githubusercontent.com/55191679/202243582-5c4826d4-77bd-43ae-aeca-bfbb43888caf.png)

#### Log file :

[Ryujinx_1.1.344_2022-11-16_17-23-10.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10024004/Ryujinx_1.1.344_2022-11-16_17-23-10.log)

**Comment by MetrosexualGarbodor** [comment]
Please post this in #93. Closing as duplicate.
