### ISSUE TITLE
Pokemon Violet - 01008f6008c5e000

### ISSUE THREAD

**Issue by boazvdwansem** [Ryujinx/Ryujinx-Games-List#4214]
#### Graphics Backend : Vulkan

Game crashes after ~30 seconds. No graphical glitches so far.

```
Last error returned.

GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".

```

#### Log file :

[Ryujinx_1.1.344_2022-11-16_17-42-23.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10024101/Ryujinx_1.1.344_2022-11-16_17-42-23.log)
Ryzen 5600X

**Comment by MetrosexualGarbodor** [comment]
Do not open issues for unreleased games.
