### ISSUE TITLE
Pokemon Scarlet

### ISSUE THREAD

**Issue by PokeNic** [Ryujinx/Ryujinx-Games-List#4223]
#### Graphics Backend : Vulkan

Game seems to run well on native

- there some upscaling issues
- there major visual issues (Shader?)

#### Outstanding Issues:

- blinking black spots in the game (especially in the trees)
-> maybe a shader bug?

#### Screenshots :
![image](https://user-images.githubusercontent.com/118569086/202801416-e39f4178-96f5-4259-888c-344a11e7f6cd.png)

![image](https://user-images.githubusercontent.com/118569086/202801517-0ac86966-2d0b-4dd5-9874-d2e364733682.png)

#### Log file :
[Ryujinx_1.1.361_2022-11-18_20-55-49.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10044724/Ryujinx_1.1.361_2022-11-18_20-55-49.log)

**Comment by MetrosexualGarbodor** [comment]
Please post this in #4218. Closing as duplicate.
