### ISSUE TITLE
Pokemon Scarlet - 0100A3D008C5C000

### ISSUE THREAD

**Issue by Mr-Pike** [Ryujinx/Ryujinx-Games-List#4231]
#### Graphics Backend : *Vulkan or OpenGL*

There is bug with the mission "cache-cache".
The goal is to find the professor Ducoin with the magnifier.
When I find the professor (cf. screen), nothing is happening.
When I try Yuzu, no problem. (scaling problem?).

##### RAM: *32GB*
![bug-mission](https://user-images.githubusercontent.com/3603458/203659718-61749bb9-21c1-4a8c-98ce-2ffe4ef932ac.png)
*

**Comment by MetrosexualGarbodor** [comment]
Duplicate of #4218. This is also not an emulator issue. Increase your deadzone and press A while hovering him.
