### ISSUE TITLE
Glitched character's eyes textures and music is bugged.

### ISSUE THREAD

**Issue by RedKai26** [Ryujinx/Ryujinx-Games-List#4236]
##### RAM: 8GB

Ok my english is not perfect but i'll try.... The thing is the games has good performance but has this glitch of missing textures around the characters's eyes... well i know it can be fixed by switching to OpenGL but i wanted to adress it.
But the serious one is this glitch when sometimes you open or close a door (it seems that happens with any sound that can "interrumpt" the music) the music just goes silent, here's a video showing both issues: [https://youtu.be/Xia_c8QtMDQ](url)

```
Last error returned.
Add the last error in the log if there is any.
e.g.: Unhandled Exception: System.NotImplementedException: /dev/nvhost-nvdec 40044801
I dunno but i'll post the log


#### Screenshots:

*Add screenshots here (preferably on windowed mode) if the game is rendering
![image](https://user-images.githubusercontent.com/119143634/204116051-8da120e5-8222-4403-ac3b-cf8602500a79.png)
.*


#### Log file:

*Add a log file here. 
Can be found in the logs folder, in the same directory as the Ryujinx executable, or through File > Open logs folder.*

[Ryujinx_1.1.391_2022-11-26_19-42-54.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10097362/Ryujinx_1.1.391_2022-11-26_19-42-54.log)

**Comment by gdkchan** [comment]
This should be reported on the existing entry for this game #3657.
