### ISSUE TITLE
Games load poorly and the online system does not work.

### ISSUE THREAD

**Issue by Josemarirome20** [Ryujinx/Ryujinx-Games-List#4241]
As soon as I enter the emulator I have to hit reload several times until the games are loaded and the LDN information does not show anything. In the console I get this error, does anyone know how to fix it?

`.NET ThreadPool Worker Application LoadApplications: Failed to fetch the public games JSON from the API. Player and game count in the game list will be unavailable.`

**Comment by AcK77** [comment]
Check your firewall maybe... The API seems to be online https://ldn.ryujinx.org/api
I suggest your to come to our discord for support if needed and notice this repository is for game compatibility report ONLY. 
Thanks!

**Comment by gdkchan** [comment]
I think the list should load regardless of LDN working or not. If that's not the case today then I think this is a valid issue.
