### ISSUE TITLE
Splatoon 2 Cash Crash To Desktop macOS

### ISSUE THREAD

**Issue by chimp66** [Ryujinx/Ryujinx-Games-List#4243]
##### RAM: 32GB

Status- ingame

Describe the current game state here. 
the game is able to completely boot into the character creator and boot into the initial part of the tutorial. Once in the tutorial, there are hiccups but that's expected due to first-time shader compilation. The problem arises when you progress further into the tutorial where the game hard crashes to the desktop. This game was a fresh install with no shader cache and no prior saves. 

```
Last error returned.

No error message was returned as it Is hard to crash to the desktop other than the generic macOS error diagnostic text box

#### Log file:

[Splatoon 2 error log.txt](https://github.com/Ryujinx/Ryujinx-Games-List/files/10100173/Splatoon.2.error.log.txt)

[Ryujinx_ 1.1.0-macos1_2022-11-27_22-07-54.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10100179/Ryujinx_.1.1.0-macos1_2022-11-27_22-07-54.log)

**Comment by MetrosexualGarbodor** [comment]
Please post this in #703. Closing as duplicate.
