### ISSUE TITLE
pokemon switch

### ISSUE THREAD

**Issue by Sirbunny16** [Ryujinx/Ryujinx-Games-List#4245]
##### RAM: *(e.g. 16GB)*

*Describe the current game state here. 
List the issues you've noticed if there are any. 
Add links to related issues from the main repository if they exist.
Add links to pull requests that fix issues described if/when applicable. 
Add a zipped save file for easy access to any issues if needed, namely for situations that can only be accessed after several hours of gameplay.*

```
Last error returned.
Add the last error in the log if there is any.
e.g.: Unhandled Exception: System.NotImplementedException: /dev/nvhost-nvdec 40044801
```

#### Screenshots:

*Add screenshots here (preferably on windowed mode) if the game is rendering.*

#### Log file:

*Add a log file here. 
Can be found in the logs folder, in the same directory as the Ryujinx executable, or through File > Open logs folder.*

**Comment by gdkchan** [comment]
Please fill the issue template properly.
