### ISSUE TITLE
Animal Crossing 01006F8002326000 - random crashes

### ISSUE THREAD

**Issue by mbs0ft** [Ryujinx/Ryujinx-Games-List#4246]
##### RAM: *(8GB)*

Random crashed after launch, nothing in Ryujinx is changed
And in your camping tent background is just white

#### Log file:

[Ryujinx_ 1.1.0-macos1_2022-11-29_12-30-23.log](https://github.com/Ryujinx/Ryujinx/files/10112375/Ryujinx_.1.1.0-macos1_2022-11-29_12-30-23.log)
[Ryujinx_ 1.1.0-macos1_2022-11-29_12-47-58.log](https://github.com/Ryujinx/Ryujinx/files/10112376/Ryujinx_.1.1.0-macos1_2022-11-29_12-47-58.log)

**Comment by MetrosexualGarbodor** [comment]
Please post this on #250. Closing as duplicate.
