### ISSUE TITLE
Mario Odyssey crashing in the Ruined Kingdom on MacOS

### ISSUE THREAD

**Issue by Pedro-Beirao** [Ryujinx/Ryujinx-Games-List#4250]
##### RAM: 16GB

After about 10 seconds in the Ruined Kingdom, the game crashes. Other users are experiencing the same problem https://www.reddit.com/r/Ryujinx/comments/z77jsr/mario_odyssey_ruined_kingdom_crashing/

#### Log file:

[Ryujinx_ 1.1.0-macos1_2022-12-01_12-52-31.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10132530/Ryujinx_.1.1.0-macos1_2022-12-01_12-52-31.log)

**Comment by EmulationFanatic** [comment]
Please post this as a reply on the corresponding game issue https://github.com/Ryujinx/Ryujinx-Games-List/issues/93. Closing as duplicate.
