### ISSUE TITLE
Game crashes after installing 1.1.1 update

### ISSUE THREAD

**Issue by Alwon86** [Ryujinx/Ryujinx-Games-List#4253]
## Mario Party Superstars

Game Version: 1.0 (01006FE013472000)

Game Update Version: 1.1.1 (01006FE013472800)

Emulator Build Version: 1.1.410

Graphics Backend: Vulkan

Hardware Specs: CPU 13900k, 4090 RTX, 32 GB of Ram

the game works perfectly well on its own, however, when installing the 1.1.1 update...it crashes on both ryujinx and yuzu.
I tried installing the update from other sources as well and changing vulkan to opengl. I get the same result.

I noticed other people have no problems with the update, any tips on how to get it to work?

I've attached the log file

Regards

[Ryujinx_1.1.410_2022-12-02_11-42-48.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10139118/Ryujinx_1.1.410_2022-12-02_11-42-48.log)

**Comment by MetrosexualGarbodor** [comment]
Please join discord for help, this is not a support page.
