### ISSUE TITLE
Pokémon Violet 1.1.0 Crash on start

### ISSUE THREAD

**Issue by Vatsune** [Ryujinx/Ryujinx-Games-List#4254]
Pokémon Violet

Game Update Version: 1.1.0
Emulator Build Version: 1.1.415
Graphics Backend: OpenGL

Hardware Specs: 
CPU: i3 10100
GPU: NVIDIA GTX 1650 Super
RAM: 8 GB

After installing title update 1.1.0, the game crashes on startup, with both no save file or preexisting save file.
Previous version 1.0.1 works fine.
Firmware 15.0.1.
All cheats are disabled.

```
Last error returned:
Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
```

Edit: Replaced log with log without found cheats.

[Ryujinx_1.1.415_2022-12-02_21-06-18.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10144005/Ryujinx_1.1.415_2022-12-02_21-06-18.log)

**Comment by MetrosexualGarbodor** [comment]
Please join discord for help, this is not a support page.
