### ISSUE TITLE
FOOTBALL MANAGER 2023 TOUCH - Letters not loading on menus

### ISSUE THREAD

**Issue by caiocsl** [Ryujinx/Ryujinx-Games-List#4256]
##### RAM: *16GB*

*Past the intro, all menus and label got missing letters. Like 'r', 'f', 'i', etc.
Since the game is mostly menus and labels...*

#### Screenshots:

![image](https://user-images.githubusercontent.com/20684505/205448684-4c9acaae-e554-4336-acc4-7ba16c97a78e.png)

**Comment by MetrosexualGarbodor** [comment]
Please post this as a comment on #4210. Closing as duplicate.
