### ISSUE TITLE
[Snipperclips Cut it out together] :[PRINCESS POWER-UP 2]'s second scene the princess just flashed Infinitely repeted.

### ISSUE THREAD

**Issue by JimmyJamy** [Ryujinx/Ryujinx-Games-List#4264]
## Game Name
Snipperclips Cut it out together 

#### Game Update Version: 
Snipperclips Cut it out together [0100704000B3A000][v0].xci
Snipperclips Cut it out together [UPD][v1.1.0][0100704000B3A800][v65536]
Snipperclips Cut it out together [DLC][0100704000B3B001][v0]

#### Emulator Build Version: 
Ryujinx 1.1.0-macos1

#### Graphics Backend: 
Vulkan

##### RAM: *(e.g. 16GB)*:32GB

-> When Played to [Retro Reboot] Level's last game[PRINCESS POWER-UP 2]'s second scene the princess just flashed Infinitely repeted.
So Can not complete the scene. The girl should be not flashed Infinitely repeted.
The game doesn't crash, so there is no log.

#### Screenshots:
Step1
<img width="1278" alt="sc 2022-12-05 13 39 45" src="https://user-images.githubusercontent.com/98637971/205560383-27c1d468-c8a9-402b-abde-118fb6a27086.png">

Step2
<img width="1392" alt="sc 2022-12-05 13 42 55" src="https://user-images.githubusercontent.com/98637971/205560442-31675e3d-dc5b-4abb-b748-742f6de81afc.png">

Step3[[PRINCESS POWER-UP 2]'s second scene]
<img width="1392" alt="截屏2022-12-05 13 50 53" src="https://user-images.githubusercontent.com/98637971/205560460-f7632dc6-8d3f-4cd6-9302-7d923ae5038d.png">

**Comment by EmulationFanatic** [comment]
Please post this as a comment on the [existing game entry](https://github.com/Ryujinx/Ryujinx-Games-List/issues/1653).
