### ISSUE TITLE
Kamen Rider: Memory of Heroez – Premium Sound Edition macOS issue

### ISSUE THREAD

**Issue by TheSpeedster6** [Ryujinx/Ryujinx-Games-List#4271]
##### RAM: 16GB

The characters are not being rendered properly I think cause during their scenes all I see are the eyes for Zero-One or hair for Shotaro.

```
The last error returned.
00:03:46.079 |E| HLE.OsThread.13 SurfaceFlinger OnTransact: Error returned by transaction DequeueBuffer: Busy
```

#### Screenshots:
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/119910381/205799601-a1e50de4-dc90-4032-83aa-9e19a305355c.png">
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/119910381/205800166-c699db80-8fb2-4541-9c7a-f16b9baf5738.png">
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/119910381/205800289-595d070b-e455-44a5-8954-634016b0cad3.png">
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/119910381/205800475-f9305685-5c80-4ed7-861f-2c1889066ef1.png">

#### Log file:

[Ryujinx_ 1.1.0-macos1_2022-12-06_08-00-45.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10161848/Ryujinx_.1.1.0-macos1_2022-12-06_08-00-45.log)

**Comment by TheSpeedster6** [comment]
> Duplicate of #2829

he has sound issue but I have graphics issue so how can it be duplicate?

**Comment by MetrosexualGarbodor** [comment]
![image](https://user-images.githubusercontent.com/79612681/205802432-0f807681-317d-4344-9140-e6ede43f2f92.png)
