### ISSUE TITLE
Super Mario Odyssey 

### ISSUE THREAD

**Issue by Nawaites46** [Ryujinx/Ryujinx-Games-List#4299]
##### RAM: 16GB

Game can run until home screen, and crash

```
Last error returned.
Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> LibHac.Common.HorizonResultException: ResultFsNonRealDataVerificationFailed (2002-4604): Hash error!
```

#### Screenshots:

![IMG-20221221-WA0007.jpg](https://user-images.githubusercontent.com/121163347/208888395-4b8d1d7f-a231-4d68-82a1-1bf9f8f8051a.jpg)

#### Log file:

![IMG-20221221-WA0008.jpg](https://user-images.githubusercontent.com/121163347/208889027-052cae13-ad6b-427e-afad-7fbbf72d31aa.jpg)

**Comment by MetrosexualGarbodor** [comment]
Your game file is broken. And please don't open issues for help, we have discord for that.
