### ISSUE TITLE
Pokémon Scarlet & Violet black flickering on macOS Intel (AMD GPU)

### ISSUE THREAD

**Issue by Piipperi** [Ryujinx/Ryujinx-Games-List#4304]
#### Game Update Version: *(e.g. 1.0.0 or 1.1.3)*
1.0.1

#### Emulator Build Version: *(e.g. 1.1.373)*
1.1.0-macos1

#### Graphics Backend: *(e.g. Vulkan or OpenGL)*
Vulkan

##### CPU: *(e.g. i7-6700)*
i7-4960HQ

##### GPU: *(e.g. NVIDIA RTX 2070)*
AMD RX 5700 XT

##### RAM: *(e.g. 16GB)*
16 GB

*Describe the current game state here. 
Sound plays fine, FPS is steady 30 and CPU/GPU usage isn't particularly high. 
Issue is that I can't see any of the game. It flickers constantly, and changing the resolution has no effect.

```
Last error returned.
Add the last error in the log if there is any.
e.g.: Unhandled Exception: System.NotImplementedException: /dev/nvhost-nvdec 40044801
```
Couldn't find any notable errors from the log.

#### Screenshots:

*Add screenshots here (preferably on windowed mode) if the game is rendering.*
I can screen record it if required.

#### Log file:

*Add a log file here. 
Can be found in the logs folder, in the same directory as the Ryujinx executable, or through File > Open logs folder.*
[Ryujinx_ 1.1.0-macos1_2022-12-27_20-45-04.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10310387/Ryujinx_.1.1.0-macos1_2022-12-27_20-45-04.log)

**Comment by MetrosexualGarbodor** [comment]
Duplicate of #4218
