### ISSUE TITLE
POKEMON VIOLET CRASH AT LAUNCH

### ISSUE THREAD

**Issue by lapocha5** [Ryujinx/Ryujinx-Games-List#4318]
## Emulator Version: 1.1.502

Vulkan

##### RAM: 16GB

As soon as i launch the game it closes.

#### Log file:

*Add a log file here. 
00:00:00.035 |I| Configuration LogValueChange: ResScale set to: 2
00:00:00.039 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.039 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.040 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.040 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.041 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.041 |I| Configuration LogValueChange: PreferredGpu set to: 0x1002_0x73FF
00:00:00.043 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.050 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.050 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.050 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.050 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.050 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.050 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.050 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.050 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.051 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.051 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.051 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.051 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.051 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.054 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.502
00:00:00.057 |N| Application Print: Operating System: Microsoft Windows 10.0.22621 (X64)
00:00:00.057 |N| Application Print: CPU: AMD Ryzen 5 5600G with Radeon Graphics ; 12 logical
00:00:00.058 |N| Application Print: RAM: Total 15742 MiB ; Available 9978 MiB
00:00:00.060 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.061 |N| Application PrintSystemInfo: Launch Mode: UserProfile

**Comment by gdkchan** [comment]
Compatibility reports should be submitted at the existing issue #4217. This crash on AMD is due to resolution scale.
