### ISSUE TITLE
Animal Crossing: New Horizons

### ISSUE THREAD

**Issue by teszNU** [Ryujinx/Ryujinx-Games-List#432]
#### Current on `master` : 1.0.4047

This game not working, load crash. 
Note: the game musted firmware version 9.2.0

#### Log file : 
[Ryujinx_2020-03-27_13-23-32.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4391699/Ryujinx_2020-03-27_13-23-32.log)

**Comment by AcK77** [comment]
Closed because of https://github.com/Ryujinx/Ryujinx-Games-List/issues/250
