### ISSUE TITLE
Sifu - 01007B5017A12000

### ISSUE THREAD

**Issue by Browser1004** [Ryujinx/Ryujinx-Games-List#4354]
##### RAM: 16GB

I open the game up, the game seems fine and I progress through the menu of agreements.
When I end up with the difficulty selector the game does not register the 'A' button anymore that I put on my keyboard as 'o', instead I found out later it was enter which is weird.
Since I didn't know how to progress past the difficulty selector at that time, I closed the game and the app and went back into it.
Upon going back into it the game crashed and has keep on crashing since then, sometimes I would be able to get into the menu of the game again but when I restart the game it could load the boot screen and then crash again.

(This happens even when updating it).

#### Log file:

This is a log file when I tried loading the game, it didn't even load the game this time it just crashed.

[Ryujinx_ 1.1.0-macos1_2023-01-14_00-34-14.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10416207/Ryujinx_.1.1.0-macos1_2023-01-14_00-34-14.log)

**Comment by EmulationFanatic** [comment]
Game-specific issues should be posted on the [game compatibility list](https://github.com/Ryujinx/Ryujinx-Games-List/issues). Thanks!

**Comment by EmulationFanatic** [comment]
lmao oops

**Comment by EmulationFanatic** [comment]
Please provide screenshots of your test.

**Comment by Browser1004** [comment]
![Image 14-01-2023 at 00 59](https://user-images.githubusercontent.com/122634697/212442996-01de5fe5-1d0e-456d-8ec1-b7a963174f13.jpeg)

**Comment by MutantAura** [comment]
Superceded by #4373
