### ISSUE TITLE
Hollow Knight Black Screen

### ISSUE THREAD

**Issue by TigerFangGaming** [Ryujinx/Ryujinx-Games-List#4361]
### Is there an existing issue for the game?

- [X] I have searched the existing game issues

### Game Name

Hollow Knight

### Game Update Version

1.4.3.2

### Emulator Build Version

1.1.565

### Graphics Backend

OpenGL and Vulkan

### Hardware Specs

- CPU: 11th Gen Intel(R) Core(TM) i7 
- Graphics GPU: Intel(R) Iris(R) Xe 
- RAM: 12GB 

### Game State

The game screen is blacked out. The health bar is still shown and the menu can be opened. Other than that the game runs at a constant 60 fps even after the black screen.

### Screenshots

![image](https://user-images.githubusercontent.com/63767493/212709595-ce542aa0-82fc-4ddf-90df-ed29cb8c3d5c.png)

### Log File

[Ryujinx_1.1.565_2023-01-16_09-58-46.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10426958/Ryujinx_1.1.565_2023-01-16_09-58-46.log)

**Comment by EmulationFanatic** [comment]
You were linked to the original game issue by TSR Berry on Discord already. https://github.com/Ryujinx/Ryujinx-Games-List/issues/132

**Comment by TigerFangGaming** [comment]
> You were linked to the original game issue by TSR Berry on Discord already. #132

Yea, it turns out that it isn't the same issue though. That issue is about the cutscenes showing a black screen, for me it's the entire game after a certain point.

**Comment by EmulationFanatic** [comment]
![image](https://user-images.githubusercontent.com/62343878/212716287-4375a364-9a72-4185-b27e-b6441a7f824e.png)
Add a comment, don't create a new issue.
