### ISSUE TITLE
Death's Door is stuttering a lot on mac m1 pro 8gb

### ISSUE THREAD

**Issue by felipevc13** [Ryujinx/Ryujinx-Games-List#4366]
### Game Name

Death's Door

### Game Update Version

v1.1.5

### Emulator Build Version

1.1.0

### Graphics Backend

Vulkan

### Hardware Specs

Apple M1 pro
RAM: 8gb

### Game State

The game is stuttering a lot.

**Comment by MetrosexualGarbodor** [comment]
Please follow the issue template.

**Comment by Meistache** [comment]
Please reopen as game is now playable and running smooth.

Game Name
Death's Door

Game Update Version
v1.1.6

Emulator Build Version
1.1.737

Graphics Backend
Both OpenGL and  Vulkan

Hardware Specs
CPU: AMD Ryzen 5 3600
GPU: NVIDIA RTX 3080
RAM: 32gb

Game State
Running perfectly fine.

Screenshots

![Ryujinx Nvidia Profile Screenshot 2023 04 29 - 08 06 02 09](https://user-images.githubusercontent.com/5265507/235287071-cd46673a-2f31-4d83-8d6b-904e546d0b5c.png)

![Ryujinx Nvidia Profile Screenshot 2023 04 29 - 07 46 15 57](https://user-images.githubusercontent.com/5265507/235287079-f8338296-fde7-44a9-9e4e-95ec13930b8a.png)

![Ryujinx Nvidia Profile Screenshot 2023 04 29 - 07 49 20 71](https://user-images.githubusercontent.com/5265507/235287088-55602233-9849-46b8-a579-0f329b237e47.png)

![Ryujinx Nvidia Profile Screenshot 2023 04 29 - 07 52 10 53](https://user-images.githubusercontent.com/5265507/235287102-827a5f8c-90be-4ee1-8c97-4bac1f9717e6.png)

![Ryujinx Nvidia Profile Screenshot 2023 04 29 - 07 59 13 41](https://user-images.githubusercontent.com/5265507/235287109-11a4e0a8-86a9-4305-a42d-0097f1aa6e06.png)
