### ISSUE TITLE
BSOD on Animal Crossing: New Horizons

### ISSUE THREAD

**Issue by Ariikitty** [Ryujinx/Ryujinx-Games-List#4372]
### Game Name

Animal Crossing: New Horizons

### Game Update Version

2.0.6

### Emulator Build Version

15.0.1

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: Ryzen 7 3800X
- ##### GPU: GTX 1060 6GB 
- ##### RAM: 16GB

### Game State

The game will run fine for a good half an hour to an hour and then stuttering starts to happen. This is then followed by either heavy graphical glitches or into a BSOD with the stop code: VIDEO_MEMORY_MANAGEMENT_INTERNAL. I have had the BSOD happen twice now while playing AC:NH on Ryujinx and haven't experienced it on any other software outside of Ryujinx. I haven't tested a different game as AC:NH is the only game I have to emulate. 

### Log File

[Ryujinx_1.1.575_2023-01-20_18-08-15.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10469709/Ryujinx_1.1.575_2023-01-20_18-08-15.log)

**Comment by Ariikitty** [comment]
Currently switched the Graphics Backend to see if I get the same issue on OpenGL

**Comment by AcK77** [comment]
Please report that in #250.
Thanks
