### ISSUE TITLE
Hyrule Warriors: Age of Calamity - 01002B00111A2000

### ISSUE THREAD

**Issue by Tarvaln** [Ryujinx/Ryujinx-Games-List#4378]
### Game Name

Hyrule Warriors: Age of Calamity

### Game Update Version

1.3.0

### Emulator Build Version

1.1.587

### Graphics Backend

Vulkan

### Hardware Specs

CPU: *(Intel i9 13700k)*
GPU: *(AMD 7900 xtx)*
RAM: *(64 GB)*

### Game State

Black spots appear and flicker in the game menu and in the game itself. It is worse in some scenes than others. It it very noticeable on Chu's and when targeting an enemy. Tested in Docked, Handheld. Also with Native, x2, and x3 scaling. It seems like it's a particle effect that is not being rendered properly.

### Screenshots

![Screenshot (28)](https://user-images.githubusercontent.com/123280290/213897156-a3692ca1-63fc-4a30-9a69-92f0aa2b7988.jpg)
![Screenshot (30)](https://user-images.githubusercontent.com/123280290/213897160-8ff85b17-76be-4a85-bc89-84d959aa3669.jpg)

### Log File

[Ryujinx_1.1.587_2023-01-21_17-27-28.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10473551/Ryujinx_1.1.587_2023-01-21_17-27-28.log)

**Comment by MetrosexualGarbodor** [comment]
Please post this in the existing issue #2862
