### ISSUE TITLE
Game crashes after certain fight

### ISSUE THREAD

**Issue by theenderror** [Ryujinx/Ryujinx-Games-List#4394]
### Game Name

Pokemon Scarlet

### Game Update Version

1.1.0

### Emulator Build Version

1.1.599

### Graphics Backend

OpenGL

### Hardware Specs

i7-4790
NVIDIA GTX 1650
16,0 GB

### Game State

The game is slow and laggy, but thats not the thing bothering me. The game always crashes after the Sada AI fight

### Log File

[Ryujinx_1.1.599_2023-02-01_18-07-36.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10559783/Ryujinx_1.1.599_2023-02-01_18-07-36.log)

**Comment by MetrosexualGarbodor** [comment]
For support and technical issues, please come to our Discord server. https://discord.gg/ryujinx
