### ISSUE TITLE
Pokemon Scarlet keeps on crashing

### ISSUE THREAD

**Issue by HeyHooooo** [Ryujinx/Ryujinx-Games-List#4473]
### Game Name

Pokemon Scarlet

### Game Update Version

1.0.0

### Emulator Build Version

15.0.0

### Graphics Backend

Vulkan

### Hardware Specs

MacBook Pro 2019 with these specs:

- Processor: 2,6 GHz 6-Core Intel Core i7
- Graphics: AMD Radeon Pro 5300M 4 GB, Intel UHD Graphics 630 1536 MB
- Ram: 16 GB 2667 MHz DDR4

### Game State

So my problem is, as soon i leave the Intro (creating your own character) in Pokemon Scarlet i get into this short cut scene. During this cut scene the program always crashes... And i really cant tell why, since i close all of my other programs. Literally nothing else is opened.

I would be so thankful for some advice to fix this problem!

Thank you!

### Log File

[Ryujinx_ 1.1.0-macos1_2023-02-26_20-33-31.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10834598/Ryujinx_.1.1.0-macos1_2023-02-26_20-33-31.log)

**Comment by MetrosexualGarbodor** [comment]
For support and technical issues, please come to our Discord server. https://discord.gg/N2FmfVc
