### ISSUE TITLE
Hyrule Warriors AoC Vulkan slower FPS than opengl

### ISSUE THREAD

**Issue by FredericVincent0** [Ryujinx/Ryujinx-Games-List#4481]
### Game Name

Hyrule Warriors Age of Calamity

### Game Update Version

1.3.0

### Emulator Build Version

1.1.650

### Graphics Backend

Vulkan

### Hardware Specs

AMD Ryzen 5 5600X 6-Core Processor 3.70 GHz
Nvidia GeForce RTX 2060
RAM 16Go

### Game State

when I start a new game the cinematics are slow and when I'm in the game it's about 20 fps no more

**Comment by MetrosexualGarbodor** [comment]
This is known, closing as duplicate of #2862.
