### ISSUE TITLE
Bayonetta Origins: Cereza and the Lost Demon - 0100CF5010FEC000 #4503

### ISSUE THREAD

**Issue by RuriaH** [Ryujinx/Ryujinx-Games-List#4512]
### Game Name

Bayonetta Origins: Cereza and the Lost Demon

### Game Update Version

1.0.0

### Emulator Build Version

1.1.673

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: *Intel® Core™ i5-11400*
- ##### GPU: *Intel® UHD Graphics 730*
- ##### RAM: *16GB 3200mhz dual channel*

### Game State

The game works fine in global settings, changing it may crash. recommended all hacks disabled, and enable multithreading

![Captura de Tela (42)](https://user-images.githubusercontent.com/64432158/226724695-a42a978f-7c95-4091-bd45-39d33915f169.png)
![Captura de Tela (43)](https://user-images.githubusercontent.com/64432158/226724705-99b356f8-64fa-4670-a35c-898a02f22963.png)

### Screenshots

![Captura de Tela (44)](https://user-images.githubusercontent.com/64432158/226725939-547dd792-3232-4ddd-bfee-9b63d0188066.png)
![Captura de Tela (45)](https://user-images.githubusercontent.com/64432158/226725946-66c1a945-57b4-459e-b703-3fa97e2f468b.png)
![Captura de Tela (46)](https://user-images.githubusercontent.com/64432158/226725952-700046cf-b416-4fc2-9ee2-a17b27253d80.png)

### Log File

[Ryujinx_1.1.673_2023-03-21_16-25-45.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11033025/Ryujinx_1.1.673_2023-03-21_16-25-45.log)

**Comment by gdkchan** [comment]
You should post it on the existing issue: #4503 Closing as duplicate.
