### ISSUE TITLE
Bayonetta 3 - can't load gpu normally and crash

### ISSUE THREAD

**Issue by ducfap1202** [Ryujinx/Ryujinx-Games-List#4533]
### Game Name

bayonetta 3

### Game Update Version

1.2.0

### Emulator Build Version

1.1.692

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: *(e.g. i5-8300H)*
- ##### GPU: *(e.g. NVIDIA GTX 1050)*
- ##### RAM: *(e.g. 16GB)*

### Game State

game crash after choosing new map, and gpu not useful

### Screenshots

![image](https://user-images.githubusercontent.com/93399282/229292388-05790496-3ba6-4537-9eac-f2f6e0887c68.png)
![image](https://user-images.githubusercontent.com/93399282/229292437-9c58cdc6-cdc5-4773-b8f1-071259759925.png)
![image](https://user-images.githubusercontent.com/93399282/229292443-e97228f0-28af-43de-a8cf-92f8dd76d7f0.png)

### Log File

[Ryujinx_1.1.692_2023-04-01_20-30-59.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11129666/Ryujinx_1.1.692_2023-04-01_20-30-59.log)

**Comment by MutantAura** [comment]
You are running out of VRAM. In future, use our discord for support queries: https://discord.gg/ryujinx
Thanks.
