### ISSUE TITLE
Hyrule Warriors: Definitive Edition black screen after "continue" after first cutscene

### ISSUE THREAD

**Issue by highjeans** [Ryujinx/Ryujinx-Games-List#4541]
### Game Name

Hyrule Warriors: Definitive Edition

### Game Update Version

1.0.0 & 1.0.1 (tried both)

### Emulator Build Version

1.1.0-macos1

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: M1 Pro
- ##### GPU: M1 Pro
- ##### RAM: 16GB

### Game State

The game loads, but then after the first cutscene, hitting the plus button for continue makes the fps drop to 0 with a black screen. Logs show a timeout.

### Screenshots

<img width="1392" alt="Screenshot 2023-04-04 at 14 46 59" src="https://user-images.githubusercontent.com/77588045/229813042-2b665500-c2ad-41b6-b361-bad19d633da9.png">
<img width="1392" alt="Screenshot 2023-04-04 at 14 47 16" src="https://user-images.githubusercontent.com/77588045/229813117-d03eeb4c-b2fa-4a27-bac7-d8ce43893df8.png">
<img width="1392" alt="Screenshot 2023-04-04 at 14 47 29" src="https://user-images.githubusercontent.com/77588045/229813187-41aa3117-cac5-4aaf-8a0e-60c7f4a745cb.png">
<img width="1392" alt="Screenshot 2023-04-04 at 14 47 51" src="https://user-images.githubusercontent.com/77588045/229813294-bf90781a-2984-444b-921a-e06aab9a55d7.png">
<img width="1392" alt="Screenshot 2023-04-04 at 14 48 11" src="https://user-images.githubusercontent.com/77588045/229813396-b9a0ef11-3eba-473d-8f3b-f16a447398c3.png">
<img width="1392" alt="Screenshot 2023-04-04 at 14 48 24" src="https://user-images.githubusercontent.com/77588045/229813454-d6b09167-a901-41af-9d90-8c321760b1d3.png">

### Log File

[Ryujinx_ 1.1.0-macos1_2023-04-04_14-46-16.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11149231/Ryujinx_.1.1.0-macos1_2023-04-04_14-46-16.log)

**Comment by AcK77** [comment]
Please report this in #168, It's currently one issue per game. Thanks.
