### ISSUE TITLE
Dragon Marked For Death: Advanced Attackers

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#455]
#### Current on `master` : 1.0.4740

Game works great, with the only issues found being colors not being correctly rendered and the sound being messed up.

#### Screenshots :

![06_22_53-17:53:36](https://user-images.githubusercontent.com/62521228/85309430-e22d0100-b4b2-11ea-968d-ea137c0ba835.png)
![06_22_53-17:53:42](https://user-images.githubusercontent.com/62521228/85309436-e48f5b00-b4b2-11ea-9091-bbbd1e806c4c.png)
![06_22_54-17:54:08](https://user-images.githubusercontent.com/62521228/85309442-e5c08800-b4b2-11ea-86fb-8417f41fd583.png)
![06_22_55-17:55:35](https://user-images.githubusercontent.com/62521228/85309447-e6f1b500-b4b2-11ea-91ed-4dadaaa4af49.png)
![06_22_55-17:55:38](https://user-images.githubusercontent.com/62521228/85309451-e822e200-b4b2-11ea-81e2-70624700d7a8.png)
![06_22_55-17:55:41](https://user-images.githubusercontent.com/62521228/85309455-e8bb7880-b4b2-11ea-9630-7ba21bcdd9c3.png)
![06_22_56-17:56:52](https://user-images.githubusercontent.com/62521228/85309458-e9eca580-b4b2-11ea-9d92-3ac9fbde1d84.png)
![06_22_57-17:57:02](https://user-images.githubusercontent.com/62521228/85309460-ea853c00-b4b2-11ea-9521-45630fb636cf.png)
![06_22_57-17:57:11](https://user-images.githubusercontent.com/62521228/85309461-ebb66900-b4b2-11ea-9240-b903082abb75.png)
![06_22_58-17:58:11](https://user-images.githubusercontent.com/62521228/85309462-ece79600-b4b2-11ea-9583-924929b886be.png)
![06_22_59-17:59:29](https://user-images.githubusercontent.com/62521228/85309464-ed802c80-b4b2-11ea-865a-15c88f34e81b.png)

#### Log file :

[dmfd.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4814310/dmfd.zip)

**Comment by EmulationFanatic** [comment]
Needs update

**Comment by SeraUX** [comment]
## Dragon Marked For Death

#### Game Update Version : 1.0.0

#### Current on `master` : 1.0.4740

Game works great, with the only issues found being colors not being correctly rendered and the sound being messed up.

#### Hardware Specs :

##### CPU: i3 7300
##### GPU: NVIDIA Corporation GeForce GTX 1050 Ti
##### RAM: 8GB

#### Screenshots :

![06_22_53-17:53:36](https://user-images.githubusercontent.com/62521228/85309430-e22d0100-b4b2-11ea-968d-ea137c0ba835.png)
![06_22_53-17:53:42](https://user-images.githubusercontent.com/62521228/85309436-e48f5b00-b4b2-11ea-9091-bbbd1e806c4c.png)
![06_22_54-17:54:08](https://user-images.githubusercontent.com/62521228/85309442-e5c08800-b4b2-11ea-86fb-8417f41fd583.png)
![06_22_55-17:55:35](https://user-images.githubusercontent.com/62521228/85309447-e6f1b500-b4b2-11ea-91ed-4dadaaa4af49.png)
![06_22_55-17:55:38](https://user-images.githubusercontent.com/62521228/85309451-e822e200-b4b2-11ea-81e2-70624700d7a8.png)
![06_22_55-17:55:41](https://user-images.githubusercontent.com/62521228/85309455-e8bb7880-b4b2-11ea-9630-7ba21bcdd9c3.png)
![06_22_56-17:56:52](https://user-images.githubusercontent.com/62521228/85309458-e9eca580-b4b2-11ea-9d92-3ac9fbde1d84.png)
![06_22_57-17:57:02](https://user-images.githubusercontent.com/62521228/85309460-ea853c00-b4b2-11ea-9521-45630fb636cf.png)
![06_22_57-17:57:11](https://user-images.githubusercontent.com/62521228/85309461-ebb66900-b4b2-11ea-9240-b903082abb75.png)
![06_22_58-17:58:11](https://user-images.githubusercontent.com/62521228/85309462-ece79600-b4b2-11ea-9583-924929b886be.png)
![06_22_59-17:59:29](https://user-images.githubusercontent.com/62521228/85309464-ed802c80-b4b2-11ea-865a-15c88f34e81b.png)


#### Log file :

[dmfd.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4814310/dmfd.zip)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Closing in favor of #147
