### ISSUE TITLE
Xenoblade Chronicles 3 [Wave 4 DLC] - 010074F013262000

### ISSUE THREAD

**Issue by XordK** [Ryujinx/Ryujinx-Games-List#4578]
### Game Name

Xenoblade Chronicles 3

### Game Update Version

2.0.0

### Emulator Build Version

15.0.1

### Graphics Backend

OpenGL

### Hardware Specs

- ##### CPU: *AMD Ryzen 5 7600X 6-Core Processor*
- ##### GPU: *NVIDIA GTX 1080 TI*
- ##### RAM: *16GB DDR5*

### Game State

Game does not start on version 2.0.0 using DLC wave 4.
Error in console and Ryujinx crashes/closes.

### Log File

00:00:00.025 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.027 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.027 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.028 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.028 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.029 |I| Configuration LogValueChange: GraphicsBackend set to: OpenGl
00:00:00.029 |I| Configuration LogValueChange: PreferredGpu set to: 
00:00:00.029 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.029 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.030 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.031 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.035 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.035 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.035 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.035 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.035 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.035 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.035 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.035 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.036 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.036 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.036 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.036 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.036 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.036 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.038 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.733
00:00:00.040 |N| Application Print: Operating System: Microsoft Windows 10.0.22621 (X64)
00:00:00.040 |N| Application Print: CPU: AMD Ryzen 5 7600X 6-Core Processor ; 12 logical
00:00:00.040 |N| Application Print: RAM: Total 15510 MiB ; Available 9881 MiB
00:00:00.042 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.042 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.041 |I| Gpu : Backend Threading (Auto): True
00:00:00.201 |N| Application LoadApplication: Using Firmware Version: 15.0.1
00:00:00.202 |I| Application LoadApplication: Loading as NSP.
00:00:00.223 |I| Application AddAocItem: Found AddOnContent with TitleId 010074F013263004
00:00:00.224 |I| Application AddAocItem: Found AddOnContent with TitleId 010074F013263003
00:00:00.224 |I| Application AddAocItem: Found AddOnContent with TitleId 010074F013263002
00:00:00.224 |I| Application AddAocItem: Found AddOnContent with TitleId 010074F013263001
00:00:00.239 |I| ModLoader QueryContentsDir: Searching mods for Title 010074F013262000
00:00:00.240 |I| ModLoader QueryContentsDir: Searching mods for DLC 010074F013263001
00:00:00.240 |I| ModLoader QueryContentsDir: Searching mods for DLC 010074F013263002
00:00:00.240 |I| ModLoader QueryContentsDir: Searching mods for DLC 010074F013263003
00:00:00.240 |I| ModLoader QueryContentsDir: Searching mods for DLC 010074F013263004
00:00:00.241 |I| ModLoader QueryContentsDir: Searching mods for Title 010074F013262000
00:00:00.241 |I| ModLoader QueryContentsDir: Searching mods for DLC 010074F013263001
00:00:00.241 |I| ModLoader QueryContentsDir: Searching mods for DLC 010074F013263002
00:00:00.241 |I| ModLoader QueryContentsDir: Searching mods for DLC 010074F013263003
00:00:00.241 |I| ModLoader QueryContentsDir: Searching mods for DLC 010074F013263004
00:00:00.243 |I| Loader Load: Loading rtld...
00:00:00.248 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.248 |I| Loader Load: Loading main...
00:00:00.341 |I| Loader PrintRoSectionInfo: main:
    Module: C:\Monolithsoft\BF3\prog_dlc\application\BF3\NX64\Rom_Master\BF3.nss
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-12_3_9-Release
00:00:00.341 |I| Loader Load: Loading subsdk0...
00:00:00.359 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: multimedia
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-12_3_9-Release
00:00:00.359 |I| Loader Load: Loading sdk...
00:00:00.397 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 12.3.9
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-12_3_9-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-12_3_9-Release
                   SDK MW+Nintendo+NintendoSDK_NVN-12_3_9-Release
00:00:00.483 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:00.490 |I| Loader LoadNsos: Loading image 0 at 0x0000000008000000...
00:00:00.491 |I| Loader LoadNsos: Loading image 1 at 0x0000000008004000...
00:00:00.501 |I| Loader LoadNsos: Loading image 2 at 0x000000000a36e000...
00:00:00.503 |I| Loader LoadNsos: Loading image 3 at 0x000000000aa08000...
00:00:00.508 |I| ModLoader LoadCheats: Build ids found for title 010074F013262000:
    E79AB9AF2AB0517496B6C5630B5C7A69769806D4000000000000000000000000
    8E18600222CE90C22FCBA194453983B3E9AE19ED000000000000000000000000
    BE1EE79A9968A35A6B63FC8F1036A6D4447F4AC3000000000000000000000000
    E8CDCEB1E77A8465FE20F21928E8D296EEA3117E000000000000000000000000
00:00:00.510 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:00.551 |I| Loader Start: Application Loaded: Xenoblade Chronicles 3 v2.0.0 [010074f013262000] [64-bit]
00:00:00.554 |I| GUI.WindowThread Hid Configure: Configured Controller JoyconPair to Player1
00:00:00.643 |I| GUI.WindowThread Hid SetupNpad: Connected Controller JoyconPair to Player1
00:00:00.721 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA Corporation NVIDIA GeForce GTX 1080 Ti/PCIe/SSE2 (4.6.0 NVIDIA 531.29)
00:00:00.736 |I| GPU.MainThread Gpu LoadShaders: Loading 7 shaders from the cache...
00:00:00.765 |I| GPU.MainThread Gpu LoadShaders: Shader cache loaded.
00:00:01.095 |S| HLE.OsThread.20 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:01.154 |S| HLE.OsThread.20 ServiceAm AcquireForegroundRights: Stubbed. 
00:00:01.157 |S| HLE.OsThread.20 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:01.159 |S| HLE.OsThread.20 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:01.210 |S| HLE.OsThread.20 ServicePctl Initialize: Stubbed. 
00:00:01.348 |W| HLE.GuestThread.19 KernelSvc : MapPhysicalMemory() = LimitReached
00:00:03.019 |S| HLE.OsThread.20 ServiceNs PrepareAddOnContentImpl: Stubbed. {index: 1}
00:00:03.022 |I| HLE.OsThread.8 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=010074F013263001
00:00:03.023 |S| HLE.OsThread.20 ServiceNs PrepareAddOnContentImpl: Stubbed. {index: 1}
00:00:03.024 |I| HLE.OsThread.8 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=010074F013263001
00:00:03.025 |S| HLE.OsThread.20 ServiceNs PrepareAddOnContentImpl: Stubbed. {index: 2}
00:00:03.026 |I| HLE.OsThread.8 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=010074F013263002
00:00:03.026 |S| HLE.OsThread.20 ServiceNs PrepareAddOnContentImpl: Stubbed. {index: 2}
00:00:03.026 |I| HLE.OsThread.8 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=010074F013263002
00:00:03.027 |S| HLE.OsThread.20 ServiceNs PrepareAddOnContentImpl: Stubbed. {index: 3}
00:00:03.027 |I| HLE.OsThread.8 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=010074F013263003
00:00:03.027 |S| HLE.OsThread.20 ServiceNs PrepareAddOnContentImpl: Stubbed. {index: 3}
00:00:03.028 |I| HLE.OsThread.8 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=010074F013263003
00:00:03.028 |S| HLE.OsThread.20 ServiceNs PrepareAddOnContentImpl: Stubbed. {index: 4}
00:00:03.053 |E| HLE.OsThread.8 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> LibHac.Common.Keys.MissingKeyException: Unable to decrypt title key.
Key Type: Common
Key Name: titlekek_0f
   at LibHac.Tools.FsSystem.NcaUtils.Nca.GetDecryptedTitleKey()
   at LibHac.Tools.FsSystem.NcaUtils.Nca.GetContentKey(NcaKeyType type)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenAesCtrStorage(IStorage baseStorage, Int32 index, Int64 offset, UInt64 upperCounter)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenDecryptedStorage(IStorage baseStorage, Int32 index, Boolean decrypting)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenRawStorage(Int32 index, Boolean openEncrypted)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenRawStorage(Int32 index)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenStorage(Int32 index, IntegrityCheckLevel integrityCheckLevel, Boolean leaveCompressed)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenStorage(Int32 index, IntegrityCheckLevel integrityCheckLevel)
   at LibHac.Tools.FsSystem.NcaUtils.Nca.OpenStorage(NcaSectionType type, IntegrityCheckLevel integrityCheckLevel)
   at Ryujinx.HLE.FileSystem.ContentManager.GetAocDataStorage(UInt64 aocTitleId, IStorage& aocStorage, IntegrityCheckLevel integrityCheckLevel) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\FileSystem\ContentManager.cs:line 290
   at Ryujinx.HLE.HOS.Services.Fs.IFileSystemProxy.OpenDataStorageByDataId(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\Fs\IFileSystemProxy.cs:line 726
   at InvokeStub_IFileSystemProxy.OpenDataStorageByDataId(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object, IntPtr*, BindingFlags)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object, IntPtr*, BindingFlags)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Ryujinx.HLE.HOS.Services.IpcService.CallCmifMethod(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 124
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 258
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 196
   at Ryujinx.HLE.HOS.Services.ServerBase.Main() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 109
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1258
   at System.Threading.Thread.StartCallback()

**Comment by MutantAura** [comment]
Redump your keys. In future, please use the discord server for support.
