### ISSUE TITLE
Mario & Sonic at the Olympic Games Tokyo 2020

### ISSUE THREAD

**Issue by vicentantonn** [Ryujinx/Ryujinx-Games-List#4594]
### Game Name

Mario & Sonic at the Olympic Games Tokyo 2020

### Game Update Version

1.0.1

### Emulator Build Version

1.7.764

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: i7 8700
- ##### GPU: AMD RX 5500XT
- ##### RAM: 16 GB

### Game State

Its impossible to play *AT THE ONLINE MODE*. Menus are great, without any issues, but when you enter an *ONLINE* game the game starts lagging and dropping fps until crashes. At individual games, there are some moments with low fps but in general the experience is great.

**Comment by Eli0t77** [comment]
You can post your findings on the existing topic
https://github.com/Ryujinx/Ryujinx-Games-List/issues/223
