### ISSUE TITLE
Emulator Crash with game Zelda

### ISSUE THREAD

**Issue by Slashguns04** [Ryujinx/Ryujinx-Games-List#4599]
### Game Name

The Legend of Zelda breath of the wild

### Game Update Version

1.6.0

### Emulator Build Version

Ryujinx 1.1.777

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: i5-11600k
- ##### GPU: NVIDIA RTX 2060 super
- ##### RAM: 32GB

### Game State

with the latest emulator updates when launching the Legend of Zelda game, The
Breath of the Wild the crash emulator after the appearance of the writing PRESENTS. How can I solve the problem? Thank you

### Screenshots

![sshot-10](https://github.com/Ryujinx/Ryujinx-Games-List/assets/87429226/66b7aa76-66fb-4095-994f-587de5315bc6)

**Comment by MetrosexualGarbodor** [comment]
Please don't open issues for help, read the FAQ or join discord 
https://github.com/Ryujinx/Ryujinx/wiki/FAQ-and-Troubleshooting#-crashing-after-booting-a-game-or-crashing-after-applying-an-update-with-e-hleosthread8-application--unhandled-exception-caught-systemreflectiontargetinvocationexception-exception-has-been-thrown-by-the-target-of-an-invocation-----libhaccommonhorizonresultexception-resultfsnonrealdataverificationfailed-2002-4604-hash-error
