### ISSUE TITLE
Artifacting on AMD 7000 cards. 

### ISSUE THREAD

**Issue by NormieSlayer69** [Ryujinx/Ryujinx-Games-List#4600]
### Game Name

Tears of the kingdom 

### Game Update Version

1.1.0

### Emulator Build Version

YUZU EA 3583 

### Graphics Backend

Vulkan

### Hardware Specs

i7 12th gen
RX 7900xt
32 gb ram

### Game State

Rendering the game on vulkan with an rx 7900xt and 7900xtx cretes a lot of artifacting. This has been the case since the game was emulated. 

https://www.reddit.com/r/NewYuzuPiracy/comments/13ck0u0/pixels_flickering_fix_help/

**Comment by OldManKain** [comment]
Wrong Emulator.
