### ISSUE TITLE
El mapa del mundo subterráneo sale invisible 

### ISSUE THREAD

**Issue by OtizSensei** [Ryujinx/Ryujinx-Games-List#4601]
### Game Name

Zelda Tears Of The Kingdom

### Game Update Version

1.1.0

### Emulator Build Version

1.1.742

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: *(e.g. i5-9400f*
- ##### GPU: *(e.g. NVIDIA RTX 1650 super)*
- ##### RAM: *(e.g. 16GB)*

### Game State

Hay errores de carga en ciertas zonas del mapa desde que no carga la textura de las rocas u montañas al igual que el mapa del subsuelo no carga del todo se ve todo invisible que puedo hacer para solucionar este error?

### Screenshots

![Ryujinx 1 1 742 - The Legend of Zelda_ Tears of the Kingdom v1 1 0 (0100F2C0115B6000) (64-bit) 12_5_2023 05_58_58](https://github.com/Ryujinx/Ryujinx-Games-List/assets/133364263/f645f99c-e5b7-4cbc-9302-d1d1e33fcbcc)

**Comment by MetrosexualGarbodor** [comment]
Duplicate of #4598
