### ISSUE TITLE
El subsuelo es totalmente invisible

### ISSUE THREAD

**Issue by OtizSensei** [Ryujinx/Ryujinx-Games-List#4602]
### Game Name

Zelda Tears Of The Kingdom

### Game Update Version

1.1.0

### Emulator Build Version

1.1.742

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: *(e.g. i5-9400f)*
- ##### GPU: *(e.g. NVIDIA RTX 1650 SUPER)*
- ##### RAM: *(e.g. 16GB)*

### Game State

El pama del subsuelo es totalmente invisible, texturas de rocas tienen recuadros grises que tengo que hacer para solucionar este error?

### Screenshots

https://github.com/Ryujinx/Ryujinx-Games-List/assets/133364263/1fcba2bd-08ed-442e-b293-5102369b0ffb

### Log File

[Ryujinx_1.1.742_2023-05-12_06-29-37.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11464033/Ryujinx_1.1.742_2023-05-12_06-29-37.log)

**Comment by MetrosexualGarbodor** [comment]
Duplicate of #4598. Please stop opening duplicate issues.

**Comment by FoixM** [comment]
hasta el momento no hay una solución si alguien sabe escríbalo porfa
