### ISSUE TITLE
Sound Issues

### ISSUE THREAD

**Issue by Shrimplul** [Ryujinx/Ryujinx-Games-List#4605]
### Game Name

The Legend of Zelda: Tears of the Kingdom

### Game Update Version

1.1.0

### Emulator Build Version

1.1.796

### Graphics Backend

Vulkan

### Hardware Specs

- CPU: Ryzen 7-5700x
- GPU: NVIDIA RTX 3070 ti
- RAM: 20GB

### Game State

I don't know if im the only one but when I launch on Vulkan, the sounds don't exist. It's just silence.

**Comment by gdkchan** [comment]
The report is incomplete, and it should be posted on the existing issue for this game #4598.
