### ISSUE TITLE
Fire Emblem Engage

### ISSUE THREAD

**Issue by Jose3270** [Ryujinx/Ryujinx-Games-List#4613]
### Game Name

Fire Emblem Engage

### Game Update Version

1.0.0

### Emulator Build Version

1.1.800

### Graphics Backend

OpenGL and Vulkan

### Hardware Specs

System Model:	HP Pavilion x360 2-in-1 Laptop 14-ek0xxx
Processor: 12th Gen Intel(R) Core(TM) i5-1235U, 1300 Mhz, 10 Core(s), 12 Logical Processor(s)
RAM: 8gb

It is a bad laptop for gaming but it doesn't even display the opening of the game. It also shows its running at 0fps. Doesn't play sound

### Game State

-Black screen
-No sound

### Screenshots

![Screenshot (26)](https://github.com/Ryujinx/Ryujinx-Games-List/assets/133822618/66d44499-aa44-4cde-8d65-3c3d59f073ca)

### Log File

00:00:00.064 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.072 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.073 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.074 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.075 |I| Configuration LogValueChange: BackendThreading set to: On
00:00:00.076 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.077 |I| Configuration LogValueChange: PreferredGpu set to: 0x8086_0x46A8
00:00:00.077 |I| Configuration LogValueChange: AntiAliasing set to: Fxaa
00:00:00.079 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.079 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.081 |I| Configuration LogValueChange: EnableDockedMode set to: False
00:00:00.093 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.093 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.093 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.093 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.093 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.093 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.093 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.093 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.094 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.095 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.096 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.096 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.096 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.096 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.102 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.800
00:00:00.108 |N| Application Print: Operating System: Microsoft Windows 10.0.22621 (X64)
00:00:00.108 |N| Application Print: CPU: 12th Gen Intel(R) Core(TM) i5-1235U ; 12 logical
00:00:00.110 |N| Application Print: RAM: Total 5091 MiB ; Available 203 MiB
00:00:00.114 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.115 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.166 |I| Gpu : Backend Threading (On): True
00:00:00.669 |N| Application LoadApplication: Using Firmware Version: 16.0.2
00:00:00.669 |I| Application LoadApplication: Loading as NSP.
00:00:00.810 |I| ModLoader QueryContentsDir: Searching mods for Title 0100A6301214E000
00:00:00.812 |I| ModLoader AddModsFromDirectory: Found mod '<0100a6301214e000 RomFs>' [R]
00:00:00.813 |I| ModLoader QueryContentsDir: Searching mods for Title 0100A6301214E000
00:00:00.818 |I| Loader Load: Loading rtld...
00:00:00.833 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.833 |I| Loader Load: Loading main...
00:00:02.445 |I| Loader PrintRoSectionInfo: main:
    Module: D:\Iron19\trunk\Unity\Iron19\SwitchIL2CPPCache\il2cpp_cache\linkresult_238E5E808ED588903C83DE49ED68521A\SwitchPlayer.nss
    SDK Libraries: SDK MW+UnityTechnologies+Unity-2020_3_18_f1
                   SDK MW+Nintendo+NintendoSDK_libcurl-12_3_7-Release
                   SDK MW+Nintendo+NintendoSDK_libz-12_3_7-Release
                   SDK MW+Nintendo+NEX-4_6_6-
                   SDK MW+Nintendo+NEX_DS-4_6_6
                   SDK MW+Nintendo+NEX_RK-4_6_6
                   SDK MW+Nintendo+NEX_UT-4_6_6
                   SDK MW+Nintendo+NEX_R2-4_6_6
                   SDK MW+Nintendo+NEX_SC-4_6_6
                   SDK MW+Nintendo+NEX_SS-4_6_6
                   SDK MW+Nintendo+NEX_CO-4_6_6
00:00:02.447 |I| Loader Load: Loading subsdk0...
00:00:02.651 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: multimedia
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-12_3_7-Release
00:00:02.651 |I| Loader Load: Loading sdk...
00:00:02.830 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 12.3.7
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-12_3_7-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-12_3_7-Release
                   SDK MW+Nintendo+NintendoSDK_NVN-12_3_7-Release
00:00:03.080 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:04.771 |I| Ptc Load: Loaded Translation Cache (size: 21190879 bytes, translated functions: 18895).
00:00:04.897 |I| Ptc Load: Loaded Profiling Info (size: 63500 bytes, profiled functions: 18912).
00:00:05.023 |I| Loader LoadNsos: Loading image 0 at 0x0000000008000000...
00:00:05.026 |I| Loader LoadNsos: Loading image 1 at 0x0000000008004000...
00:00:05.232 |I| Loader LoadNsos: Loading image 2 at 0x000000000e662000...
00:00:05.237 |I| Loader LoadNsos: Loading image 3 at 0x000000000ecfc000...
00:00:05.251 |I| ModLoader LoadCheats: Build ids found for title 0100A6301214E000:
    E79AB9AF2AB0517496B6C5630B5C7A69769806D4000000000000000000000000
    E7E1382D5EB931B0D4BDA894B707AC9200000000000000000000000000000000
    BFFED55EA46C1B48DDEABCACDFBF81BF418125AC000000000000000000000000
    56EC24747EC9E7F19B3EFB062483A19D1DA091A8000000000000000000000000
00:00:05.260 |I| ModLoader ApplyRomFsMods: Applying RomFS mods for Title 0100A6301214E000
00:00:05.312 |I| ModLoader ApplyRomFsMods: Replaced 20 file(s) over 1 mod(s). Processing base storage...
00:00:12.426 |I| ModLoader ApplyRomFsMods: Building new RomFS...
00:00:12.703 |I| ModLoader ApplyRomFsMods: Using modded RomFS
00:00:12.729 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:13.397 |I| Loader Start: Application Loaded: Fire Emblem Engage v1.0.0 [0100a6301214e000] [64-bit]
00:00:13.481 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight' on 'Player1, Player2, Player3, Player4, Player5, Player6, Player7, Player8, Handheld'
00:00:14.428 |N| GUI.RenderLoop Gpu PrintGpuInformation: Intel Intel(R) Iris(R) Xe Graphics (Vulkan v1.3.237, Driver v0.404.4091)
00:00:16.061 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight' on 'Player1, Player2, Player3, Player4, Player5, Player6, Player7, Player8, Handheld'
00:00:16.133 |I| GPU.MainThread Gpu LoadShaders: Loading 1 shaders from the cache...
00:00:16.325 |I| GPU.MainThread Gpu LoadShaders: Shader cache loaded.
00:00:17.538 |I| HLE.GuestThread.21 Ptc LoadTranslations: 18887 translated functions loaded
00:00:17.564 |I| HLE.GuestThread.21 Ptc MakeAndSaveTranslations: 0 of 25 functions translated | Thread count: 11
00:00:17.941 |I| HLE.GuestThread.21 Ptc MakeAndSaveTranslations: 25 of 25 functions translated | Thread count: 11 in 0.3395723 s
00:00:18.063 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight' on 'Player1, Player2, Player3, Player4, Player5, Player6, Player7, Player8, Handheld'
00:00:18.553 |S| HLE.OsThread.22 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:18.650 |S| HLE.OsThread.22 ServiceAm AcquireForegroundRights: Stubbed. 
00:00:18.652 |S| HLE.OsThread.22 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:18.652 |S| HLE.OsThread.22 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:18.748 |S| HLE.OsThread.22 ServicePctl Initialize: Stubbed. 
00:00:18.864 |S| HLE.OsThread.10 ServiceNv FinishInitialize: Stubbed. 
00:00:18.878 |S| HLE.OsThread.22 ServiceAm SetRestartMessageEnabled: Stubbed. {restartMessageEnabled: True}
00:00:18.879 |S| HLE.OsThread.22 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:18.880 |S| HLE.OsThread.22 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:20.066 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight' on 'Player1, Player2, Player3, Player4, Player5, Player6, Player7, Player8, Handheld'
00:00:21.493 |I| Ptc Save: Saved Translation Cache (size: 21238302 bytes, translated functions: 18920).
00:00:22.068 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight' on 'Player1, Player2, Player3, Player4, Player5, Player6, Player7, Player8, Handheld'
00:00:24.070 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight' on 'Player1, Player2, Player3, Player4, Player5, Player6, Player7, Player8, Handheld'
00:00:26.072 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight' on 'Player1, Player2, Player3, Player4, Player5, Player6, Player7, Player8, Handheld'
00:00:26.102 |S| HLE.OsThread.5 ServiceBsd RegisterClient: Stubbed. 
00:00:26.103 |S| HLE.OsThread.5 ServiceBsd StartMonitoring: Stubbed. {unknown0: 0}
00:00:27.079 |S| HLE.OsThread.22 ServiceSsl SetInterfaceVersion: Stubbed. {interfaceVersion: 3}
00:00:27.115 |S| HLE.OsThread.9 ServiceHid ActiveNpadImpl: Stubbed. {appletResourceUserId: 1 ; revision: 3}
00:00:27.117 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 98 ; appletResourceUserId: 1 ; type: ProController}
00:00:27.126 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadIdType: Stubbed. 8 Players: Player1,Player2,Player3,Player4,Player5,Player6,Player7,Player8
00:00:27.166 |S| HLE.OsThread.10 ServiceNv InitializeEx: Stubbed. 
00:00:27.202 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:27.297 |S| HLE.OsThread.10 ServiceNv SetNvMapFd: Stubbed. 
00:00:27.298 |S| HLE.OsThread.10 ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:27.299 |S| HLE.OsThread.10 ServiceNv AllocObjCtx: Stubbed. 
00:00:27.301 |S| HLE.OsThread.10 ServiceNv SetErrorNotifier: Stubbed. 
00:00:27.301 |S| HLE.OsThread.10 ServiceNv SetUserData: Stubbed. 
00:00:27.302 |S| HLE.OsThread.10 ServiceNv SetTimeout: Stubbed. 
00:00:27.302 |S| HLE.OsThread.10 ServiceNv SetTimeslice: Stubbed. 
00:00:27.305 |S| HLE.OsThread.10 ServiceNv ZcullBind: Stubbed. 
00:00:27.313 |I| HLE.OsThread.22 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:27.318 |I| HLE.OsThread.22 SurfaceFlinger CreateLayerFromId: Creating layer 2
00:00:28.080 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController' on 'Player1, Player2, Player3, Player4, Player5, Player6, Player7, Player8'
00:00:28.640 |S| HLE.OsThread.10 ServiceNv ZbcSetTable: Stubbed. 
00:00:28.640 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:28.883 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:00:30.081 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController' on 'Player1, Player2, Player3, Player4, Player5, Player6, Player7, Player8'
00:00:32.083 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController' on 'Player1, Player2, Player3, Player4, Player5, Player6, Player7, Player8'
00:00:34.085 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController' on 'Player1, Player2, Player3, Player4, Player5, Player6, Player7, Player8'
00:00:36.086 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController' on 'Player1, Player2, Player3, Player4, Player5, Player6, Player7, Player8'
00:00:38.087 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController' on 'Player1, Player2, Player3, Player4, Player5, Player6, Player7, Player8'
00:00:40.088 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController' on 'Player1, Player2, Player3, Player4, Player5, Player6, Player7, Player8'
00:00:42.089 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController' on 'Player1, Player2, Player3, Player4, Player5, Player6, Player7, Player8'
00:00:44.092 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController' on 'Player1, Player2, Player3, Player4, Player5, Player6, Player7, Player8'
00:00:46.092 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController' on 'Player1, Player2, Player3, Player4, Player5, Player6, Player7, Player8'
00:00:47.475 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 98 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:47.477 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadIdType: Stubbed. 3 Players: Handheld,Player1,Player2
00:00:48.012 |I| .NET ThreadPool Worker Ptc Save: Saved Profiling Info (size: 63609 bytes, profiled functions: 18946).
00:00:48.094 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Player2, Handheld'
00:00:50.095 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Player2, Handheld'
00:00:52.096 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Player2, Handheld'
00:00:54.097 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Player2, Handheld'
00:00:56.099 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Player2, Handheld'
00:00:58.101 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Player2, Handheld'
00:01:00.103 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Player2, Handheld'
00:01:02.104 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Player2, Handheld'
00:01:04.106 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Player2, Handheld'
00:01:06.108 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Player2, Handheld'
00:01:08.111 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Player2, Handheld'
00:01:10.112 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Player2, Handheld'
00:01:12.114 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Player2, Handheld'
00:01:14.116 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Player2, Handheld'
00:01:16.117 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Player2, Handheld'
00:01:17.974 |I| .NET ThreadPool Worker Ptc Save: Saved Profiling Info (size: 63650 bytes, profiled functions: 18959).
00:01:18.118 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Player2, Handheld'
00:01:20.120 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Player2, Handheld'
00:01:22.122 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Player2, Handheld'
00:01:24.124 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Player2, Handheld'
00:01:26.126 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Player2, Handheld'
00:01:28.127 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Player2, Handheld'
00:01:30.130 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Player2, Handheld'
00:01:32.131 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Player2, Handheld'
00:01:34.133 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Player2, Handheld'
00:01:36.136 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Player2, Handheld'
00:01:38.138 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair' on 'Player1, Player2, Handheld'
00:01:38.627 |I| Hid Configure: Configured Controller ProController to Player1
00:01:38.697 |I| GUI.WindowThread Hid SetupNpad: Connected Controller ProController to Player1
00:02:56.525 |I| Configuration LogValueChange: EnableTextureRecompression set to: True
00:02:56.528 |I| Configuration LogValueChange: AntiAliasing set to: None
00:05:54.930 |W| HLE.GuestThread.23 KernelSvc : WaitSynchronization(handleIndex: 0xFFFFFFFF) = TerminationRequested
00:05:54.930 |W| HLE.GuestThread.24 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:05:54.930 |W| HLE.GuestThread.46 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:05:54.933 |W| HLE.GuestThread.25 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:05:54.933 |W| HLE.GuestThread.49 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:05:54.933 |W| HLE.GuestThread.48 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:05:54.933 |W| HLE.GuestThread.27 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:05:54.933 |W| HLE.GuestThread.39 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:05:54.933 |W| HLE.GuestThread.47 KernelSvc : WaitSynchronization(handleIndex: 0xFFFFFFFF) = TerminationRequested
00:05:54.934 |W| HLE.GuestThread.44 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:05:54.934 |W| HLE.GuestThread.26 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:05:54.934 |W| HLE.GuestThread.43 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:05:54.934 |W| HLE.GuestThread.42 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:05:54.934 |W| HLE.GuestThread.41 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:05:54.934 |W| HLE.GuestThread.28 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:05:54.934 |W| HLE.GuestThread.29 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:05:54.934 |W| HLE.GuestThread.40 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:05:54.934 |W| HLE.GuestThread.38 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:05:54.935 |W| HLE.GuestThread.30 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:05:54.935 |W| HLE.GuestThread.45 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:05:54.935 |W| HLE.GuestThread.31 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:05:54.935 |W| HLE.GuestThread.32 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:05:54.935 |W| HLE.GuestThread.33 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:05:54.935 |W| HLE.GuestThread.37 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:05:54.935 |W| HLE.GuestThread.34 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:05:54.935 |W| HLE.GuestThread.35 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:05:54.935 |W| HLE.GuestThread.36 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:05:55.062 |W| GUI.WindowThread ServiceNv Close: Closing channel

**Comment by AcK77** [comment]
Please report that in https://github.com/Ryujinx/Ryujinx-Games-List/issues/4370. Thanks!
