### ISSUE TITLE
Layton's Mystery Journey: Katrielle and the Millionaires' Conspiracy Steam Deck puzzles

### ISSUE THREAD

**Issue by klz-fc** [Ryujinx/Ryujinx-Games-List#4626]
### Game Name

Layton's Mystery Journey: Katrielle and the Millionaires' Conspiracy

### Game Update Version

1.0.0

### Emulator Build Version

1.1.819

### Graphics Backend

Vulkan

### Hardware Specs

Steam Deck (SteamOS mode)

### Game State

Unusual behavior - specifically on the Steam Deck and does not occur on previous puzzles - The puzzle window is zoomed in and is not usable (Puzzles 16 and 17 so far). Moving the save game files to Windows shows the puzzles are showing as normal and can be completed. Moving them back to the Steam Deck allowed getting past the puzzles with no other issues and prior puzzles are playable as normal. logs taken while re-playing the two puzzles and then quitting them.

### Screenshots

![puzzle 16 win](https://github.com/Ryujinx/Ryujinx-Games-List/assets/103147197/3d49ac37-d83f-46f2-a672-7ac7269af15a)
![puzzlke 16 SD](https://github.com/Ryujinx/Ryujinx-Games-List/assets/103147197/94b5068c-1a90-4e94-8d60-92c6d3fa5e6f)
![puzzle 17 win](https://github.com/Ryujinx/Ryujinx-Games-List/assets/103147197/6ec9047e-ac1f-4158-a313-ba1c663b357d)
![Puzzle 17 SD](https://github.com/Ryujinx/Ryujinx-Games-List/assets/103147197/041b42ad-5171-4ed1-a66d-e6cd5e3a76b7)

### Log File

[logs.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/11564861/logs.zip)

**Comment by klz-fc** [comment]
After some more testing, the odd behavior happens in handheld mode for some specific puzzles, but displays correctly (and is playable) in Docked mode.

**Comment by AcK77** [comment]
Duplicated of #249
