### ISSUE TITLE
TotK went dark after updating to 1.1.842

### ISSUE THREAD

**Issue by dabalingdibili** [Ryujinx/Ryujinx-Games-List#4629]
### Game Name

Zelda - Tears of the Kingdom

### Game Update Version

1.0.0

### Emulator Build Version

1.1.842

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: 11th Gen i7
- ##### GPU: *NVIDIA RTX 3050 Ti
- ##### RAM: 16 GB

### Game State

Right after I install the latest Ryujinx, Zelda -ToTk went completely dark, even in the title screen. There are no problems on the loading screen but the game itself is completely dark. Below one is from right before the boss fight on death mountain, which I had no problems before updating Ryujinx.

Did all the graphic adjustments from the strach and everything. There is also a screenshot of it as well.

### Screenshots

![WhatsApp Görsel 2023-05-30 saat 13 29 59](https://github.com/Ryujinx/Ryujinx-Games-List/assets/135027362/ad6831e0-d846-45d8-9f61-bc5c966ac3cd)
![Screenshot_1](https://github.com/Ryujinx/Ryujinx-Games-List/assets/135027362/d3294a73-e6e7-43d4-9eaa-112fce752971)
![Screenshot_2](https://github.com/Ryujinx/Ryujinx-Games-List/assets/135027362/a7665e7d-921c-4240-a448-7e6eb690c55f)
![Screenshot_3](https://github.com/Ryujinx/Ryujinx-Games-List/assets/135027362/14fb82f9-a68a-4bc8-9f80-eed1fd41dc84)

**Comment by OldManKain** [comment]
Does it happen without mods?

**Comment by OldManKain** [comment]
Could you post a log here, or join us in our discord https://discord.gg/ryujinx for trouble shooting.

**Comment by Yanqi-Jing** [comment]
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/83804369/2249ea9a-1e84-4ad0-b985-1e8979e297a9)
right click your game, then select Cache Management, then Queue PPTC Rebuild, and Purge Shader Cache, this worked for me. But the game will stutter just as when you first installed it.

**Comment by dabalingdibili** [comment]
thanks to you both, I just reverted back to 1.1.748 and playing the game.
