### ISSUE TITLE
Monster Hunter Rise

### ISSUE THREAD

**Issue by C00kie-M0de** [Ryujinx/Ryujinx-Games-List#4633]
### Game Name

MHR

### Game Update Version

3.1.0

### Emulator Build Version

1.1.862

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: *(e.g. i7-6700)*
- ##### GPU: *(e.g. NVIDIA RTX 2070)*
- ##### RAM: *(e.g. 16GB)*
AMD Ryzen 7 5800X3D
AMD Radeon RX 6900 XT
32683 MiB

### Game State

Continue game, eat at the cantina and take the hub urgent quest. Move towards the monster, climb the wines upwards to the monster and mine the first node that you see on the left and the game stop responding after that.
[0000000000000003.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/11646524/0000000000000003.zip)

### Log File

[Ryujinx_1.1.862_2023-06-04_20-35-23.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11646528/Ryujinx_1.1.862_2023-06-04_20-35-23.log)

**Comment by MetrosexualGarbodor** [comment]
Please post this on the existing issue #3465. Closing as duplicate.
