### ISSUE TITLE
Luigi's Mansion 3 - 10th Floor Crash AMD Radeon Graphics

### ISSUE THREAD

**Issue by liquidnitro90** [Ryujinx/Ryujinx-Games-List#4639]
### Game Name

Luigi's Mansion 3

### Game Update Version

1.4.0

### Emulator Build Version

1.1.881

### Graphics Backend

Vulkan

### Hardware Specs

CPU: AMD Ryzen 5 5500U
GPU: AMD Radeon(TM) Graphics
RAM: 16GB

### Game State

If I go right from here, the game crashes. The AMD Graphics will flag a driver crash

### Screenshots

![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/20409594/578c5c8b-67b9-4266-a63d-67ac9910b5cb)

### Log File

[Ryujinx_1.1.881_2023-06-10_22-02-05.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11712572/Ryujinx_1.1.881_2023-06-10_22-02-05.log)

**Comment by liquidnitro90** [comment]
The game did not crash if using OpenGL

**Comment by MutantAura** [comment]
Report compatibility on the game page, do not open new issues. https://github.com/Ryujinx/Ryujinx-Games-List/issues/207
