### ISSUE TITLE
black screen in metroid dread

### ISSUE THREAD

**Issue by sebasom2** [Ryujinx/Ryujinx-Games-List#4646]
### Game Name

Metroid Dread

### Game Update Version

1.0.0

### Emulator Build Version

1.1.890

### Graphics Backend

OpenGL and Vulkan

### Hardware Specs

- ##### CPU: intel core i5 3570
- ##### GPU: Graphics Chipset
AMD Radeon HD 7000 series DDR3
- ##### RAM: 16GB

### Game State

el juego inicia solo con audio, no imagen (pantalla negra),
se puede escuchar que el juego va perfecto
----------
the game starts with only audio, no image (black screen),
you can hear that the game is perfect

### Screenshots

![Screenshot 2023-06-13 173334](https://github.com/Ryujinx/Ryujinx-Games-List/assets/78280617/a14ae10e-9888-4e56-9cf0-c491d877cbea)
![Screenshot 2023-06-13 173438](https://github.com/Ryujinx/Ryujinx-Games-List/assets/78280617/c5e30466-85f3-4e4a-9382-38614b41a4a0)

### Log File

[Ryujinx_1.1.890_2023-06-13_17-24-47.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11740187/Ryujinx_1.1.890_2023-06-13_17-24-47.log)
[Ryujinx_1.1.890_2023-06-13_17-21-14.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11740188/Ryujinx_1.1.890_2023-06-13_17-21-14.log)

**Comment by sebasom2** [comment]
olvide mensionar que sucede el mismo problema en zelda totk y mario maker 2
-------------------
forgot to mention that the same problem happens in zelda totk and mario maker 2

**Comment by MetrosexualGarbodor** [comment]
Your GPU is too old and has been out of driver support for several years. As a result, it doesn't meet the minimum requirements to run games on Ryujinx.

You may try Linux with Mesa drivers, but other than that, all you can do is buy a new PC. Sorry.
