### ISSUE TITLE
Xenoblade Chronicles 2 Graphical Issues during cutscenes 

### ISSUE THREAD

**Issue by Lemonade-Sky** [Ryujinx/Ryujinx-Games-List#4667]
### Game Name

Xenoblade Chronicles 2

### Game Update Version

1.0.0

### Emulator Build Version

1.1.945

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: M1 Max
- ##### GPU: M1 Max integrated
- ##### RAM: 32GB

### Game State

Basically the game runs really well until one encounters a cutscene. During a cutscene serious graphical glitches begin to occur, resembling flashing squares. I have included a picture to highlight the issue.

I've tried every single combination of graphic, system and CPU setting that is possible, and nothing fixes it. I'd appreciate some advice from someone with more experience. For example, does a mod exist to fix this? Are there optimal graphics settings that i'm missing? V-Synch is off as it has to be otherwise the in-game menus crash.

My feeling is that this may just be something unfixable but would greatly appreciate any help.

### Screenshots

<img width="1352" alt="Screenshot 2023-07-01 at 07 52 01" src="https://github.com/Ryujinx/Ryujinx-Games-List/assets/138281577/92331f01-bf69-4ced-b086-a6a871aba212">

**Comment by AcK77** [comment]
Please send the report in https://github.com/Ryujinx/Ryujinx-Games-List/issues/159, thanks

**Comment by Lemonade-Sky** [comment]
Sorry i didn't realise i had to reply to the thread. I think i've reposted it again as a new thread
