### ISSUE TITLE
eBaseball Power Pro Baseball 2022

### ISSUE THREAD

**Issue by fofo456120** [Ryujinx/Ryujinx-Games-List#4670]
### Game Name

eBaseball Power Pro Baseball 2022

### Game Update Version

1.9.0

### Emulator Build Version

1.1.951

### Graphics Backend

Vulkan

### Game State

Crashes right after loading, shows nothing.

### Log File

[Ryujinx_1.1.951_2023-07-04_12-39-30.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11944078/Ryujinx_1.1.951_2023-07-04_12-39-30.log)

**Comment by MetrosexualGarbodor** [comment]
Can you at least add a log file?

**Comment by fofo456120** [comment]
Log File added.

**Comment by MetrosexualGarbodor** [comment]
This is a duplicate of #4010, but please post your report and the log there, as it seems it's missing services that were never reported. Thank you.
