### ISSUE TITLE
pikmin3 deluxe resolution issue

### ISSUE THREAD

**Issue by gariiiudo** [Ryujinx/Ryujinx-Games-List#4706]
### Game Name

pikmin3 deluxe

### Game Update Version

1.1.0

### Emulator Build Version

16.0.3

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: *(e.g. i7-6700)*
- ##### GPU: *(e.g. NVIDIA RTX 1060)*
- ##### RAM: *(e.g. 16GB)*

### Game State

When i start emulating the game the resolution get blocky.
not only in the menu screen but in the gameplay as well.
its in docked mode

### Screenshots

![スクリーンショット (27)](https://github.com/Ryujinx/Ryujinx-Games-List/assets/141473798/8376b1df-3874-477b-a527-d0e564e17254)
![スクリーンショット (26)](https://github.com/Ryujinx/Ryujinx-Games-List/assets/141473798/b6678804-4b67-43d6-8f2a-314ca28a236d)
![スクリーンショット (29)](https://github.com/Ryujinx/Ryujinx-Games-List/assets/141473798/51d34ed4-280a-4d4c-b1f7-68502efc440c)

### Log File

[Ryujinx_1.1.974_2023-08-05_13-13-21.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/12266203/Ryujinx_1.1.974_2023-08-05_13-13-21.log)

**Comment by GamerzHell9137** [comment]
Its because you're not using the default options of the emulator.
Dont change stuff that you dont know what to do.
Change Upscale from Nearest back to Bilinear.
