### ISSUE TITLE
Sea of Stars

### ISSUE THREAD

**Issue by antoniodanieldaten** [Ryujinx/Ryujinx-Games-List#4734]
### Game Name

Sea of Stars

### Game Update Version

1.0.0

### Emulator Build Version

13.2.0

### Graphics Backend

OpenGL

### Hardware Specs

- ##### CPU: *(e.g. i7-6700)*
- ##### GPU: *(e.g. NVIDIA RTX 2070)*
- ##### RAM: *(e.g. 16GB)*

### Game State

Not even recognized

**Comment by MetrosexualGarbodor** [comment]
Please join Discord for help.
