### ISSUE TITLE
Mortal Kombat 11 - 0100F2200C984800

### ISSUE THREAD

**Issue by zemzema** [Ryujinx/Ryujinx-Games-List#4741]
### Game Name

Mortal Kombat 11

### Game Update Version

1703936

### Emulator Build Version

1.1.1014

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: *(e.g. i7-6700)*
- ##### GPU: *(e.g. NVIDIA RTX 2070)*
- ##### RAM: *(e.g. 16GB)*

### Game State

Not showing in emulator list.

**Comment by gdkchan** [comment]
This is the update, not the base game.
