### ISSUE TITLE
Borderlands 3 Crashing

### ISSUE THREAD

**Issue by diegitozt** [Ryujinx/Ryujinx-Games-List#4759]
### Game Name

Borderlands 3 Ultimate Edition

### Game Update Version

1.0.1

### Emulator Build Version

1.1.1047

### Graphics Backend

Vulkan

### Hardware Specs

- M1 SILICON CPU (8 cores)
- M1 SILICON GPU (10 cores)
- 8GB RAM

### Game State

Game boots, plays 2K logo animation for 2~ seconds before crashing the emulator. Can not load into game or main menu.

### Screenshots

<img width="1440" alt="Screenshot 2023-10-06 at 11 44 27 PM" src="https://github.com/Ryujinx/Ryujinx-Games-List/assets/142644204/907fa89c-429d-4fc6-aaff-165c8e574535">
<img width="260" alt="Screenshot 2023-10-06 at 11 44 57 PM" src="https://github.com/Ryujinx/Ryujinx-Games-List/assets/142644204/db5c698e-f9b3-4e7f-bbf2-725ec2cc8f35">

### Log File

[Ryujinx_1.1.0+47929a2_2023-10-06_23-43-43.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/12837011/Ryujinx_1.1.0%2B47929a2_2023-10-06_23-43-43.log)

**Comment by gdkchan** [comment]
I don't know which version you are using, but you should be testing with the latest version of the emulator.

**Comment by diegitozt** [comment]
> I don't know which version you are using, but you should be testing with the latest version of the emulator.

I don't know if you have basic reading comprehension skills, but my post clearly states the build version I am using. It also happens to be the "latest version".

**Comment by GabCoolDude** [comment]
Your log is not from the latest version of the emulator, i think that was what they were referring to.
