### ISSUE TITLE
Please help. Game is Crashing on my macbook pro M2. Game seems to crash in specific areas

### ISSUE THREAD

**Issue by BungaBoy** [Ryujinx/Ryujinx-Games-List#4760]
### Game Name

TOTK

### Game Update Version

1.0.0-1.2.0

### Emulator Build Version

Ryujinx 1.1.1048 Firmware 16.0.3-16.1.0

### Graphics Backend

Vulkan

### Hardware Specs

Apple silicon M2

### Game State

the game seems to freeze out of nowhere. When I reload the save file it crashes in the same areas. I haven't experienced any crashes until up to this point. When I started exploring this area. I tried switching to older versions of the emulator, turning vsync on/off, I tried different firmware and keys, and I took off all mods but nothing seemed to work. Help would be appreciated. I'm new to GitHub so let me know if I gave enough information.

### Screenshots

![Screenshot 2023-10-07 at 10 52 37 AM](https://github.com/Ryujinx/Ryujinx-Games-List/assets/147272034/c7de8d7c-961f-4345-8379-797eda20e664)
![Screenshot 2023-10-07 at 10 52 51 AM](https://github.com/Ryujinx/Ryujinx-Games-List/assets/147272034/971f911b-802a-4e74-b4fd-5715d0dea276)
![Screenshot 2023-10-07 at 10 53 04 AM](https://github.com/Ryujinx/Ryujinx-Games-List/assets/147272034/ebb33f9c-b393-43d4-9cd3-1b3b0e8f4c1b)
![Screenshot 2023-10-07 at 10 53 18 AM](https://github.com/Ryujinx/Ryujinx-Games-List/assets/147272034/325610ac-52d2-463d-9097-c8b06c01040b)

### Log File

[Ryujinx_1.1.1048_2023-10-07_10-02-50.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/12838416/Ryujinx_1.1.1048_2023-10-07_10-02-50.log)

[Ryujinx_1.1.1048_2023-10-07_10-18-03.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/12838417/Ryujinx_1.1.1048_2023-10-07_10-18-03.log)

[Ryujinx_1.1.1048_2023-10-07_10-25-49.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/12838418/Ryujinx_1.1.1048_2023-10-07_10-25-49.log)

**Comment by gdkchan** [comment]
That error indicates that your ROM file is corrupted.

**Comment by BungaBoy** [comment]
so would i have to get a new rom and also delete the save file?

**Comment by gdkchan** [comment]
You don't need to delete the save file, just to re-dump the ROM.

**Comment by OmDharme** [comment]
What is re-dump the ROM? Can the steps be explained?

**Comment by MelonSpeedruns** [comment]
https://nh-server.github.io/switch-guide/
