### ISSUE TITLE
DeepOne

### ISSUE THREAD

**Issue by dantezero0403** [Ryujinx/Ryujinx-Games-List#4761]
### Game Name

Deep One

### Game Update Version

1.0.0

### Emulator Build Version

1.1.1048

### Graphics Backend

Vulkan

### Hardware Specs

AMD Ryzen™ 9 6900HX
AMD Radeon™ 680M
Windows 11

### Game State

Does not start due to error

### Log File

[Ryujinx_1.1.1048_2023-10-08_10-36-53.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/12839557/Ryujinx_1.1.1048_2023-10-08_10-36-53.log)

**Comment by AcK77** [comment]
Duplicated of #446

**Comment by gdkchan** [comment]
@AcK77 It's not the same game (DeepOne vs. Deep Ones), this one was released recently.

**Comment by gdkchan** [comment]
Needs an update.

**Comment by luojunyuan** [comment]
Opened with 0100961011BE6800 game 1.0.1 update without anything wrong.

Emulator Build Version: 1.1.1112
Graphics Backend: Apple
Hardware Specs: mbp m3 pro
