### ISSUE TITLE
CRASHES

### ISSUE THREAD

**Issue by WinHack9702GitHub** [Ryujinx/Ryujinx-Games-List#4762]
### Game Name

super mario odyssey

### Game Update Version

i.d.k

### Emulator Build Version

1.1.1049

### Graphics Backend

OpenGL

### Hardware Specs

processor - Intel(R) Xeon(R) CPU X3440  @ 2.53GHz   2.53 GHz
ram - 4,00 gb
gpu - idk

### Game State

game crashes

**Comment by GabCoolDude** [comment]
You can't run ryujinx on this computer.

**Comment by WinHack9702GitHub** [comment]
UPD: it work on vulkan

**Comment by WinHack9702GitHub** [comment]
Some games work on opengl. Sooo, update minimals for ruyjinx, it works on my PC
