### ISSUE TITLE
Sonic Superstars - 01008F701C074000 - a modern Amy costume graphical issue

### ISSUE THREAD

**Issue by scju** [Ryujinx/Ryujinx-Games-List#4775]
### Game Name

Sonic Superstars

### Game Update Version

1.0.5A

### Emulator Build Version

1.1.1053

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: i9-9900k
- ##### GPU: NVIDIA RTX 3060ti
- ##### RAM: 32GB

### Game State

There is a graphical issue when Amy runs with the modern costume.

### Screenshots

![2023-10-19_095011](https://github.com/Ryujinx/Ryujinx-Games-List/assets/31085634/caa7732e-e376-4b2f-954f-e10169b0cc30)
![2023-10-19_102931](https://github.com/Ryujinx/Ryujinx-Games-List/assets/31085634/addb8e3a-112f-4980-b968-ba167663d636)
![2023-10-19_102932](https://github.com/Ryujinx/Ryujinx-Games-List/assets/31085634/b97795ca-6032-45a4-af19-d0acdf909df9)

### Log File

[Ryujinx_1.1.1053_2023-10-19_09-40-59.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/13036163/Ryujinx_1.1.1053_2023-10-19_09-40-59.log)

**Comment by OldManKain** [comment]
Please post the issues on the original post #4773
