### ISSUE TITLE
Emulator Freezing then crashing

### ISSUE THREAD

**Issue by Simerjeetkaur8440** [Ryujinx/Ryujinx-Games-List#4777]
### Game Name

Picross s8

### Game Update Version

1.0.0

### Emulator Build Version

1.1.1050

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: Apple M2
- ##### GPU: integreated
- ##### RAM: 8gb

### Game State

Game start and run good at 60 fps constant but suddenly it freezes and crashes the emulator also happening with other games

### Log File

[Ryujinx_1.1.1050_2023-10-20_18-20-59.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/13055040/Ryujinx_1.1.1050_2023-10-20_18-20-59.log)

**Comment by MutantAura** [comment]
Please use our discord for generic support: https://discord.gg/ryujinx
