### ISSUE TITLE
Super Mario Bros. Wonder Compatibility

### ISSUE THREAD

**Issue by Kr0nos214** [Ryujinx/Ryujinx-Games-List#4779]
### Game Name

Super Mario Bros. Wonder

### Game Update Version

1.0.0

### Emulator Build Version

1.1.1057

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: *(e.g. i7-6700)*
- ##### GPU: *(e.g. NVIDIA RTX 2070)*
- ##### RAM: *(e.g. 16GB)*

### Game State

The game is playable, but every 3 or so loading screens, the game freezes and crashes. Big graphical glitches appear every once in a while, which makes the game glitch out and make it unplayable. Apart from that the game has good performance.

**Comment by DrWillz** [comment]
Please can you post this on the other mario wonder page #4776 
Thanks
