### ISSUE TITLE
sonic superstars

### ISSUE THREAD

**Issue by DVG112** [Ryujinx/Ryujinx-Games-List#4782]
### Game Name

sonic superstars

### Game Update Version

sonic superstars

### Emulator Build Version

soni superstars

### Graphics Backend

OpenGL

### Hardware Specs

- ##### CPU: *(e.g. i7-6700)*
- ##### GPU: *(e.g. NVIDIA RTX 2070)*
- ##### RAM: *(e.g. 16GB)*

### Game State

bom

### Screenshots

p

### Log File

#

**Comment by DVG112** [comment]
q

**Comment by elpepefake** [comment]
s

**Comment by elpepefake** [comment]
s

**Comment by elpepefake** [comment]
s

**Comment by elpepefake** [comment]
s

**Comment by elpepefake** [comment]
35435 43634644565546

**Comment by elpepefake** [comment]
4565465464545

**Comment by elpepefake** [comment]
45

**Comment by elpepefake** [comment]
6

**Comment by elpepefake** [comment]
45

**Comment by elpepefake** [comment]
654
