### ISSUE TITLE
2k23 Boots and then Crashes

### ISSUE THREAD

**Issue by kplace27** [Ryujinx/Ryujinx-Games-List#4783]
### Game Name

NBA 2k24 Kobe Bryant Edition 

### Game Update Version

1.01

### Emulator Build Version

16.1.0

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: *(e.g. i7-12700k)*
- ##### GPU: *(e.g. NVIDIA RTX 3070)*
- ##### RAM: *(e.g. 32GB)*

### Game State

The game boots and starts to load and then ryujinx crashes.

**Comment by OldManKain** [comment]
Please post on the original post for this game #4726
