### ISSUE TITLE
Kirby Star Allies problems with graphics in Goal Stage and text appearing at the wrong time

### ISSUE THREAD

**Issue by Lucas-Zxc** [Ryujinx/Ryujinx-Games-List#4810]
### Game Name

Kirby star allies

### Game Update Version

4.0.0

### Emulator Build Version

1.1.1083

### Graphics Backend

Vulkan

### Hardware Specs

I5 12400f
Rtx 3060 12gb
16 gb ram
SSD M2 NVME 1tb

### Game State

then, as in the image, in the Goal Stage, sometimes the graphics of the characters look like this and also in addition, I noticed that the texts when you enter a world, they don't appear at that moment, but rather when you enter a stage, but it wasn't supposed to be like this

### Screenshots

![ryujinx_capture_2023-11-14_20-57-19](https://github.com/Ryujinx/Ryujinx-Games-List/assets/145923354/97760887-5e69-4e93-a152-e90ea1d20417)

**Comment by Ivan951236** [comment]
Ok but go to Kirby Star Allies's game issue page not made by you by searching this in main Ryujinx game list's Issues Tab's Search bar:
is:issue is:open in:title Kirby 

Note that for me this game's list appeared as last for me by searching using this above
