### ISSUE TITLE
Pokemon Sword :drop fps because of MultiPlayer

### ISSUE THREAD

**Issue by CelerSan** [Ryujinx/Ryujinx-Games-List#4831]
### Game Name

Pokemon Sword 

### Game Update Version

1.0.0

### Emulator Build Version

1.1.1065

### Graphics Backend

Vulkan

### Hardware Specs

CPU: Intel Core i5 7300U
GPU: Intel HD Graphics 630
GPU: unknow
RAM: 16GB

### Game State

(Sorry for my rusty english)Hello guys, I recently installed Ryujinx on my PC, I installed and configured everything correctly (Firmware and prod Key in 1.17) to play Pokemon Sword (the first version without any mods) it works well between 25~30FPS (normally) but when I start the game at the beginning there are drops of FPS like for one second the game is at 30FPS and the next second at 9FPS and those continually, repeatedly . However, I am not connected to the internet and I have disabled Multiplayer. Even if I connect to the internet and activate multiplayer, but to no avail. I would like to point out that my problem is only with Pokemon Sword for me, games like Mario Bros. Wonder works without problem.

### Screenshots

![Capture](https://github.com/Ryujinx/Ryujinx-Games-List/assets/144831071/27a2a43b-e2ef-4e32-a013-644d4d03b79d)

**Comment by OldManKain** [comment]
Update your game, also please post any issues on the already created report #232 .
