### ISSUE TITLE
FIFA 21 Legacy Edition Jagged Lines, No Icons above players

### ISSUE THREAD

**Issue by matiashuarta** [Ryujinx/Ryujinx-Games-List#4832]
### Game Name

FIFA 21 Legacy Edition

### Game Update Version

1.0.2

### Emulator Build Version

1.1.1098

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: i5 9400f
- ##### GPU: RTX 4060Ti
- ##### GPU Driver version: Latest
- ##### RAM: 32GB

### Game State

The game is playable, but there are no icons above players, the crowd is in some parts glowy white and field lines look jagged.

See screenshots for reference:

### Screenshots

![1](https://github.com/Ryujinx/Ryujinx-Games-List/assets/107086769/a77e702d-465d-4d8a-8815-6828658ddf2e)
![2](https://github.com/Ryujinx/Ryujinx-Games-List/assets/107086769/7fdcec5c-1177-4513-a083-6da1e5975f5c)
![3](https://github.com/Ryujinx/Ryujinx-Games-List/assets/107086769/a75ab455-1e94-4d79-809f-7df3f2e0df74)

### Log File

[Ryujinx_1.1.1098_2023-12-11_16-51-04.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/13640539/Ryujinx_1.1.1098_2023-12-11_16-51-04.log)
[Ryujinx_1.1.1098_2023-12-11_17-12-47.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/13640541/Ryujinx_1.1.1098_2023-12-11_17-12-47.log)
[Ryujinx_1.1.1098_2023-12-11_17-08-22.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/13640542/Ryujinx_1.1.1098_2023-12-11_17-08-22.log)

**Comment by OldManKain** [comment]
Known issue, #2647 closing as duplicate.
