### ISSUE TITLE
Mario Tennis Aces Incomplete/Flickering Crowd

### ISSUE THREAD

**Issue by matiashuarta** [Ryujinx/Ryujinx-Games-List#4833]
### Game Name

Mario Tennis Aces

### Game Update Version

3.1.0

### Emulator Build Version

1.1.1098

### Graphics Backend

OpenGL and Vulkan

### Hardware Specs

- ##### CPU: i5 9400F
- ##### GPU: RTX 4060Ti
- ##### GPU Driver version: Latest
- ##### RAM: 32GB

### Game State

Playable.
Crowd is incomplete/glitchy and flickers during intro to matches and also when the ball is not on game as part of the crowd still visible at that point.

### Screenshots

![Screenshot 2023-12-11 172327](https://github.com/Ryujinx/Ryujinx-Games-List/assets/107086769/2a1bc9b3-4fb5-495a-b3a2-20122d7ab03b)

### Log File

[Ryujinx_1.1.1098_2023-12-11_17-32-14.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/13640747/Ryujinx_1.1.1098_2023-12-11_17-32-14.log)
[Ryujinx_1.1.1098_2023-12-11_17-31-50.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/13640748/Ryujinx_1.1.1098_2023-12-11_17-31-50.log)
[Ryujinx_1.1.1098_2023-12-11_17-39-30.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/13640749/Ryujinx_1.1.1098_2023-12-11_17-39-30.log)

**Comment by mrTerryBogard** [comment]
> ### Game Name
> Mario Tennis Aces
> 
> ### Game Update Version
> 3.1.0
> 
> ### Emulator Build Version
> 1.1.1098
> 
> ### Graphics Backend
> OpenGL and Vulkan

I tested it on some version of Ryujinx and the graphics were really buggy.

Now I checked on 1.1.1214 and OpenGL was fixed.
