### ISSUE TITLE
Castle Crashers Remastered - 0100A3E00CDD4000

### ISSUE THREAD

**Issue by LIIIhao** [Ryujinx/Ryujinx-Games-List#4844]
### Game Name

Castle Crashers Remastered

### Game Update Version

v1.01.0

### Emulator Build Version

1.1.1100

### Graphics Backend

Vulkan

### Hardware Specs

Mac M1 16G

### Game State

Castle Crashers Remastered screen black, unable to start

### Log File

[Uploading Ryujinx_1.1.1100_2023-12-19_10-50-07.log…]()

**Comment by AcK77** [comment]
Duplicated of https://github.com/Ryujinx/Ryujinx-Games-List/issues/2984
