### ISSUE TITLE
忍者神龟：Shredder's Reveng-[0100FE701475A000]屏幕白色，无法启动

### ISSUE THREAD

**Issue by LIIIhao** [Ryujinx/Ryujinx-Games-List#4845]
### Game Name

Teenage Mutant Ninja Turtles: Shredder's Revenge

### Game Update Version

v1.0

### Emulator Build Version

1.1.1100

### Graphics Backend

Vulkan

### Hardware Specs

Mac M1 16G

### Game State

Teenage Mutant Ninja Turtles: Shredder's Reveng screen white, unable to start

### Log File

[Ryujinx_1.1.1100_2023-12-19_10-50-07.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/13710644/Ryujinx_1.1.1100_2023-12-19_10-50-07.log)

**Comment by AcK77** [comment]
Duplicated of https://github.com/Ryujinx/Ryujinx-Games-List/issues/3912
