### ISSUE TITLE
Unepic - 01008F80049C6000

### ISSUE THREAD

**Issue by SPUAP** [Ryujinx/Ryujinx-Games-List#4858]
### Game Name

Unepic

### Game Update Version

1.0

### Emulator Build Version

1.1.1110

### Graphics Backend

OpenGL and Vulkan

### Hardware Specs

- ##### CPU: Ryzen 5 5600X
- ##### GPU: RTX 3060 Ti
- ##### GPU Driver version: auto
- ##### RAM: 16GB

### Game State

Incorrect graphic glitch. reverse UI screen.
Top UI screen's correct location is bottom.
Bottom UI screen's correct location is top.
So top UI screen(correct location is bottom) hide detailed inventory screen. can't view detailed inventory screen. 
Asia version(010036400DFF0000) is also the same.

### Screenshots

#414

**Comment by MetrosexualGarbodor** [comment]
Please post your report on the existing issue for this game that you linked. Closing as duplicate.
