### ISSUE TITLE
Warhammer 40,000 Boltgun [01005FD017E60000] Audio Latency

### ISSUE THREAD

**Issue by Armory9756** [Ryujinx/Ryujinx-Games-List#4864]
### Game Name

Warhammer 40,000 Boltgun

### Game Update Version

1.0.0.3

### Emulator Build Version

1.1.1141

### Graphics Backend

Vulkan

### Hardware Specs

- CPU: AMD Ryzen 5 5600G
- GPU: AMD RX 7600
- GPU Driver version: Mesa 23.3.3
- RAM: 16 GB DDR4 3200 MHz
- System: Ubuntu 22.03.3 LTS, Linux Kernel 6.5

### Game State

There is a ~ 1 s delay between any visible action and the subsequent sound, e.g. jumping, firing a weapon, etc. I've updated to the latest available game version to no avail.

**Comment by Armory9756** [comment]
I solved the issue by switching the audio backend from SDL to OpenAL. This solution was found in [Issue 5099 (Ryujinx issues)](https://github.com/Ryujinx/Ryujinx/issues/5099).

**Comment by Ammar-Sadaoui** [comment]
are you using waylnad ?
