### ISSUE TITLE
Sea of Stars 

### ISSUE THREAD

**Issue by k78k** [Ryujinx/Ryujinx-Games-List#4895]
### Game Name

Sea of Stars 

### Game Update Version

1.0.47140

### Emulator Build Version

1.1.1231

### Graphics Backend

OpenGL and Vulkan

### Hardware Specs

- ##### CPU: *AMD Ryzen 7 5800H with Radeon Graphics*
- ##### GPU: *AMD Radeon(TM) Graphics*
- ##### GPU Driver version: *24.1.1*
- ##### RAM: *16GB(15.4 GB usable)*

### Game State

The emulator crashes and closes completely when trying to open the game

### Log File

[Ryujinx_1.1.1231_2024-03-15_23-52-55.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/14621052/Ryujinx_1.1.1231_2024-03-15_23-52-55.log)

**Comment by MetrosexualGarbodor** [comment]
[Your game files are corrupted](https://github.com/Ryujinx/Ryujinx/wiki/FAQ-and-Troubleshooting#-crashing-after-booting-a-game-or-crashing-after-applying-an-update-with-e-hleosthread8-application--unhandled-exception-caught-systemreflectiontargetinvocationexception-exception-has-been-thrown-by-the-target-of-an-invocation-----libhaccommonhorizonresultexception-resultfsnonrealdataverificationfailed-2002-4604-hash-error), dump them again from your Switch.

In the future, please use discord for help.
