### ISSUE TITLE
Splatoon3 high verison error

### ISSUE THREAD

**Issue by 155hahhajiubai** [Ryujinx/Ryujinx-Games-List#4898]
### Game Name

Splatoon3

### Game Update Version

v7.0.0

### Emulator Build Version

1.1.1237

### Graphics Backend

OpenGL and Vulkan

### Hardware Specs

- ##### CPU: i5-13490f
- ##### GPU: NVIDIA RTX 4060ti
- ##### GPU Driver version: 551.61
- ##### RAM: 32GB

### Game State

unable enter the game, just crash

### Log File

[Ryujinx_1.1.1237_2024-03-17_09-22-12.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/14625817/Ryujinx_1.1.1237_2024-03-17_09-22-12.log)

**Comment by MetrosexualGarbodor** [comment]
[Your game files are corrupted](https://github.com/Ryujinx/Ryujinx/wiki/FAQ-and-Troubleshooting#-crashing-after-booting-a-game-or-crashing-after-applying-an-update-with-e-hleosthread8-application--unhandled-exception-caught-systemreflectiontargetinvocationexception-exception-has-been-thrown-by-the-target-of-an-invocation-----libhaccommonhorizonresultexception-resultfsnonrealdataverificationfailed-2002-4604-hash-error), dump them again from your Switch.

In the future, please use discord for help.
