### ISSUE TITLE
Splatoon 2 Squid bug/issue

### ISSUE THREAD

**Issue by gudsir** [Ryujinx/Ryujinx-Games-List#4931]
### Game Name

Splatoon 2

### Game Update Version

v5.5.1

### Emulator Build Version

Ryujinx 1.1.1279

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: Apple M1
- ##### GPU: Apple Apple M1
- ##### GPU Driver version: Vulkan v1.2.231, Driver v0.2.2008
- ##### RAM: 5018/8192 MiB (8GB)

### Game State

Splatoon 2 runs well at a solid 57-60 fps, no problems with the framerate or anything. But there's a bug affecting gameplay a lot. There's a problem with the squid/octopus form, the squid/octopus form doesn't sink into the ink well at all, it keeps popping up then sinking back down again. It's a big problem for story mode levels where you have to climb up walls. Another problem is that the game thinks that I'm in enemy ink when I'm clearly standing in my own ink or when I'm literally on no ink at all. You can notice this when shooting ink with your weapon. It's also possible for a squid/octopus to swim on walls without ink at all. Another random bug I've noticed is that a special immediately gets charged up when just inking once at the ground. This applies to all weapons, not sure if this is intended or not though. 

### Screenshots

https://github.com/Ryujinx/Ryujinx-Games-List/assets/166998995/0c7e81f5-af0d-419c-a93b-bbc9e3ed6433

https://github.com/Ryujinx/Ryujinx-Games-List/assets/166998995/1ab67188-e666-43e6-853a-28a8525a758a

### Log File

[Ryujinx_1.1.1279_2024-04-14_12-38-42.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/14970692/Ryujinx_1.1.1279_2024-04-14_12-38-42.log)

**Comment by MetrosexualGarbodor** [comment]
Please post this as a comment on the existing issue #703. Closing as duplicate.
