### ISSUE TITLE
duplicate of #136

### ISSUE THREAD

**Issue by mrTerryBogard** [Ryujinx/Ryujinx-Games-List#4949]
duplicate of #136

_Originally posted by @piplup55 in https://github.com/Ryujinx/Ryujinx-Games-List/issues/4948#issuecomment-2088324809_
            I understand that there are stupid people, but I AM NOT WRITING ABOUT THE PROBLEM WITH THE GAME EMULATION! WHERE did you even see the REPEAT? I CLEARLY WRITTEN THAT IN THE ARCropolis GAME MODS ARE NOT SEEN AS A GAME. MO QUESTION IS NOT CLOSED!

**Comment by piplup55** [comment]
please stop
