### ISSUE TITLE
EARTH DEFENSE FORCE: WORLD BROTHERS 2 - 010083A01D456000

### ISSUE THREAD

**Issue by MysteryScruff** [Ryujinx/Ryujinx-Games-List#4982]
### Game Name

EARTH DEFENSE FORCE: WORLD BROTHERS 2

### Game Update Version

1.0.3

### Emulator Build Version

1.1.1330

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: AMD Ryzen 5 2600
- ##### GPU: NVIDIA GeForce GTX 1070
- ##### GPU Driver version: 555.99
- ##### RAM: 16GB

### Game State

Game is playable but has several audio and graphical issues. Menus and gameplay feature scratchy audio and hitches. Menus have no graphical issues, but in gameplay enemy and building models flicker constantly at all distances. Player models and weapon effects are mostly unaffected.

### Screenshots

https://github.com/Ryujinx/Ryujinx-Games-List/assets/86570283/2a1f47b0-83e9-4291-9007-962c9e1637b8

https://github.com/Ryujinx/Ryujinx-Games-List/assets/86570283/943c426b-6242-4114-9f1c-ade9d9394bef

### Log File

[Ryujinx_1.1.1330_2024-06-04_09-14-55.log](https://github.com/user-attachments/files/15552092/Ryujinx_1.1.1330_2024-06-04_09-14-55.log)

**Comment by Cronos-0** [comment]
@MysteryScruff Please close and report new issues here. It's a duplicate > https://github.com/Ryujinx/Ryujinx-Games-List/issues/4977

**Comment by piplup55** [comment]
right i was meant to merge these, i forgot
