### ISSUE TITLE
App crashes when opening game

### ISSUE THREAD

**Issue by tteokkii** [Ryujinx/Ryujinx-Games-List#4984]
### Game Name

Dave the Diver

### Game Update Version

v1.0.2.651

### Emulator Build Version

18.0.0

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: i7-8650U
- ##### GPU: Intel UHD 620 GPU
- ##### GPU Driver version: 32H2
- ##### RAM: 8GB

### Game State

When i try to load the game, it goes to downloading then crash. The game does not even open

### Log File

[Ryujinx_1.1.1330_2024-06-09_21-39-41.log](https://github.com/user-attachments/files/15755620/Ryujinx_1.1.1330_2024-06-09_21-39-41.log)
[Ryujinx_1.1.1330_2024-06-09_21-37-54.log](https://github.com/user-attachments/files/15755621/Ryujinx_1.1.1330_2024-06-09_21-37-54.log)
[Ryujinx_1.1.1330_2024-06-09_21-36-08.log](https://github.com/user-attachments/files/15755622/Ryujinx_1.1.1330_2024-06-09_21-36-08.log)

**Comment by Cronos-0** [comment]
@tteokkii Please close and report new issues here. It's a duplicate > https://github.com/Ryujinx/Ryujinx-Games-List/issues/4961

**Comment by tteokkii** [comment]
> @tteokkii Please close and report new issues here. It's a duplicate > #4961

how?
