### ISSUE TITLE
It Takes Two flickering screen on MacOS M1/M2

### ISSUE THREAD

**Issue by ziqizh** [Ryujinx/Ryujinx-Games-List#4986]
### Game Name

It Takes Two

### Game Update Version

1.0.2

### Emulator Build Version

1.1.1330

### Graphics Backend

Vulkan

### Hardware Specs

MacBook Air
- ##### CPU: Apple M2
- ##### GPU: Apple M2
- ##### GPU Driver version: N/A
- ##### RAM: 8GB
OS: 13.4.1 

### Game State

Right screen flickers. 

### Screenshots

https://github.com/Ryujinx/Ryujinx-Games-List/assets/30583106/8981d9fc-5ea5-4c5a-a273-2f8bae932761

### Log File

[Ryujinx_1.1.1330_2024-06-10_11-13-20.log](https://github.com/user-attachments/files/15777697/Ryujinx_1.1.1330_2024-06-10_11-13-20.log)
[Ryujinx_1.1.1330_2024-06-10_11-31-39.log](https://github.com/user-attachments/files/15777698/Ryujinx_1.1.1330_2024-06-10_11-31-39.log)

**Comment by GamerzHell9137** [comment]
https://github.com/Ryujinx/Ryujinx-Games-List/issues/4861
