### ISSUE TITLE
鬼滅之刃:火之神血風譚 / Demon Slayer -Kimetsu no Yaiba- The Hinokami Chronicles - 0100309016E7A000 #3911

### ISSUE THREAD

**Issue by ryuryujin** [Ryujinx/Ryujinx-Games-List#5022]
### Game Name

Demon Slayer -Kimetsu no Yaiba- The Hinokami Chronicles

### Game Update Version

v1.51

### Emulator Build Version

1.1.807

### Graphics Backend

Vulkan

### Hardware Specs

CPU: Ryzen 3600
GPU: NVIDIA RTX 3060 TI
RAM: 16GB

### Game State

Game runs and plays as intended.

Upscaling adds a dithered blocks around particle effects of snow,water etc.). There might be an issue where the resolution scaler is resetting itself (other UE games have that issue too)

### Screenshots

![239592678-4a5fd514-1303-4de4-8f4d-f6162089891e](https://github.com/user-attachments/assets/d5b8a843-8335-4867-8580-64da13d8e9ed)
![239592288-3e633fd5-0b00-42c1-889b-c8d1e5e00db5](https://github.com/user-attachments/assets/b4eae882-2da3-4495-a6e7-ee13be58ae73)
![239593165-8d108fe6-c238-4da7-8b33-2cb5ce26d6b0](https://github.com/user-attachments/assets/a402e48e-a161-4c90-aafc-a361f4a19808)

### Log File

No response

**Comment by GamerzHell9137** [comment]
Duplicate https://github.com/Ryujinx/Ryujinx-Games-List/issues/3911
