### ISSUE TITLE
Crash -Thank Goodness You're Here

### ISSUE THREAD

**Issue by Ionstrom00** [Ryujinx/Ryujinx-Games-List#5023]
### Game Name

Thank Goodness You're Here

### Game Update Version

1.4.1 and 1.0 

### Emulator Build Version

1.1.1371

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: *(M3)*
- ##### GPU: *(M3)*
- ##### GPU Driver version: *(macOS 14.6 (23G80))*
- ##### RAM: *(8GB)*

### Game State

Crashes ryujinx as soon as you try to launch it.  Doesn't even pop up loading screen for a second.

### Log File

[Ryujinx_1.1.1371_2024-08-05_21-17-31.log](https://github.com/user-attachments/files/16501876/Ryujinx_1.1.1371_2024-08-05_21-17-31.log)

**Comment by cddude** [comment]
I also have it crash on launch

**Comment by cddude** [comment]
[Ryujinx_1.1.1372_2024-08-05_22-16-49.log](https://github.com/user-attachments/files/16504427/Ryujinx_1.1.1372_2024-08-05_22-16-49.log)

**Comment by Ionstrom00** [comment]
Fresh dump.  Issue on my end and resolved.
