### ISSUE TITLE
Plants vs zombies bfn won't work

### ISSUE THREAD

**Issue by Wokwokwok3000** [Ryujinx/Ryujinx-Games-List#5031]
### Game Name

Plants vs zombies battle for neighborville 

### Game Update Version

1.0

### Emulator Build Version

Newest

### Graphics Backend

OpenGL and Vulkan

### Hardware Specs

- ##### CPU: *(e.g. i7-6700)*
- ##### GPU: *(e.g. NVIDIA RTX 2050)*
- ##### GPU Driver version: *(idk)*
- ##### RAM: *(e.g. 32GB)*

### Game State

It opens up but crashes just after load screen

### Log File

Default

**Comment by GamerzHell9137** [comment]
Duplicate https://github.com/Ryujinx/Ryujinx-Games-List/issues/3437

**Comment by Wokwokwok3000** [comment]
Oh I didn't notice my bad
