### ISSUE TITLE
Triangle Strategy - 0100CC80140F8800

### ISSUE THREAD

**Issue by eatingsmartfood** [Ryujinx/Ryujinx-Games-List#5033]
### Game Name

Triangle Strategy

### Game Update Version

1.1.0

### Emulator Build Version

1.1.1350

### Graphics Backend

Vulkan

### Hardware Specs

CPU: Apple M1 Pro 
GPU: Apple Apple M1 Pro 
GPU Driver Version:(Vulkan v1.2.231, Driver v0.2.2008)
RAM: 16 GB
OS: macOS 14.5.0 (23F79) (Arm64)

### Game State

Game is able to load and continue playing, occasional stuttering but that was to be expected. Non-combat sections of the game run without issue, however crashes during battles when units use skills. Tested multiple Ryujinx versions 1.1.1375, 1.1.1350, 1.1.1300, 1.1.1000

### Log File

[Ryujinx_1.1.1350_2024-08-14_12-14-07.log](https://github.com/user-attachments/files/16616397/Ryujinx_1.1.1350_2024-08-14_12-14-07.log)

**Comment by MetrosexualGarbodor** [comment]
Please post compatibility reports on the existing game entry #3853, and add a zipped save file right before the issue occurs with instructions for easy reproduction. Closing as duplicate.
