### ISSUE TITLE
Skyward Sword Crash Midgame 

### ISSUE THREAD

**Issue by Cubicsphinx801** [Ryujinx/Ryujinx-Games-List#5038]
### Game Name

The Legend Of Zelda: Skyward Sword

### Game Update Version

Base- I didn't install any updates 

### Emulator Build Version

1.1.1376 

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: i5-9500)
- ##### GPU: AMD Radon Rx 6400
- ##### GPU Driver version: 24.7.1
- ##### RAM: 32GB

### Game State

So im playing and the game, just freezes i check the console and ive seen the same error twice (slight coincidence but i remember saving somewhat before the crashes). The times i crashed was talking to Goose and going into a building. Ive looked online and it says they get this crash when starting the game so i assume this is similar and it said somthing about a bad dump of my game, if this is the case how to i transfer the save file?  

### Screenshots

Not much to see just freezes 
![Screenshot 2024-08-19 145914](https://github.com/user-attachments/assets/1d08f488-f133-4e59-9a7e-cc9e6ac87b8c)

### Log File

[Ryujinx Console 1.1.1376.txt](https://github.com/user-attachments/files/16661112/Ryujinx.Console.1.1.1376.txt)

**Comment by MetrosexualGarbodor** [comment]
We do not support piracy.
