### ISSUE TITLE
Neverwinter Nights EE - 010013700DA4A000

### ISSUE THREAD

**Issue by maximumxp** [Ryujinx/Ryujinx-Games-List#5048]
### Game Name

Neverwinter Nights Enhanced Edition 

### Game Update Version

1.0.2

### Emulator Build Version

1.1.1380

### Graphics Backend

Vulkan

### Hardware Specs

CPU: i9-13900k
GPU: NVIDIA RTX 3070ti
GPU Driver version: 560.94
RAM: 32GB

### Game State

A little while ago, it had issues with the main menu which became unreadable because everything was scrambled. 
That was fixed recently only on Vulkan, and now when creating a character and starting the game, it crashes after the intro movie plays and the loading bar fills. (screenshot attached)

### Screenshots

![image](https://github.com/user-attachments/assets/133dd975-b31a-4b5d-ae6e-7126b4630341)

### Log File

[Ryujinx_1.1.1380_2024-08-30_18-39-53.log](https://github.com/user-attachments/files/16822322/Ryujinx_1.1.1380_2024-08-30_18-39-53.log)

**Comment by MetrosexualGarbodor** [comment]
Please post this on the existing compatibility entry #2189. Closing as duplicate.
