### ISSUE TITLE
Hanging on ServiceHid

### ISSUE THREAD

**Issue by Franseven** [Ryujinx/Ryujinx-Games-List#505]
#### Current on `1.0.0-acnh2`

*Playable*

```
Last error returned.
ServiceHid SetSupportedNpadStyleSet: Stubbed. appletResourceUserId: 0 - _npadStyleSet: FullKey, Handheld, Dual
ServiceHid SetSupportedNpadIdType: Stubbed. appletResourceUserId: 0 - npadIdType: ControllerPlayer1
```

#### Outstanding Issues:

The emulator stops and becomes unresponsive indefinitely without crashing

#### Log file :

*https://drive.google.com/open?id=1D4JJTjCR98cvCtooOOFS1aFvYU2zOAbO*

**Comment by AcK77** [comment]
Closed in favor of #250
