### ISSUE TITLE
Still buggy

### ISSUE THREAD

**Issue by Otakunuts2024** [Ryujinx/Ryujinx-Games-List#5050]
### Game Name

F1 24 Manager

### Game Update Version

1.6

### Emulator Build Version

1.1.1385

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: *(e.g. i7-6700)*
- ##### GPU: *(e.g. NVIDIA RTX 2070)*
- ##### GPU Driver version: *(e.g. 545.84)*
- ##### RAM: *(e.g. 16GB)*

### Game State

Games loads up if V-Sync is turned off but gameplay is still buggy(alot of graphics flicker in and out)and sometimes driver profiles don't show the photos,parts of the car on track disappear then re appear 

### Log File

gfdgfdfdgdf

**Comment by MetrosexualGarbodor** [comment]
Please follow the template when opening new issues.
