### ISSUE TITLE
Selfloss Crashes on start

### ISSUE THREAD

**Issue by RazorBackRoar** [Ryujinx/Ryujinx-Games-List#5060]
### Game Name

Selfloss

### Game Update Version

1.03

### Emulator Build Version

1.1.1386

### Graphics Backend

Vulkan

### Hardware Specs

CPU: (Apple M1)
GPU: (Integrated Apple M1 GPU)
GPU Driver version:(Not user-accessible)
RAM: (16GB)

### Game State

Game flashes many colors and frame rate drops drastically. unplayable because of the flashing lights which is an epilepsy concern. 

### Log File

could not find log on macOS

**Comment by GamerzHell9137** [comment]
You should probably not post if you can't find the log.

**Comment by RazorBackRoar** [comment]
> You should probably not post if you can't find the log.

you should probably shut up & mind your own business & don't comment unless you have something to help. you didn't think to guide me step by step? you should probably keep your mouth shut going forward & don't ever commit on anything I post again. I did the best that I could do.

**Comment by GreemDev** [comment]
> > You should probably not post if you can't find the log.
> 
> you should probably shut up & mind your own business & don't comment unless you have something to help. you didn't think to guide me step by step? you should probably keep your mouth shut going forward & don't ever commit on anything I post again. I did the best that I could do.

Is this how you reply to valid, warranted criticism?

**Comment by riperiperi** [comment]
We can't really do anything without a log.

**Comment by IsaacMarovitz** [comment]
@RazorBackRoar That type of language is absolutely unacceptable on GitHub. Please refrain from talking to other users like that in the future or you will be banned.

**Comment by MetrosexualGarbodor** [comment]
Please follow the issue template when opening new compatibility entries. The screenshots are required if the game is rendering, and the template explains that logs can be found where the Ryujinx executable is.
