### ISSUE TITLE
Animal Crossing New horizon crash

### ISSUE THREAD

**Issue by ElChapo421** [Ryujinx/Ryujinx-Games-List#530]
#### Current on `master` : Commit Id *or* Build Version : Firmeware 9.2.0

I dobbleclick the game it loads i still have a blackscreen then it crashes

#### Log file :

[Ryujinx_2020-03-31_22-41-23.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4411529/Ryujinx_2020-03-31_22-41-23.log)

**Comment by AcK77** [comment]
Closed in favor of #250
