### ISSUE TITLE
Wild Guns Reloaded - 0100CFC00A1D8000

### ISSUE THREAD

**Issue by r3ntonboy** [Ryujinx/Ryujinx-Games-List#534]
### **Wild Guns Reloaded**

**Current on master**: 1.0.4114

Game runs pretty nice. It has some graphical problems. See screenshot 4.

**Screenshots:**:

![1](https://user-images.githubusercontent.com/35672114/78095604-bf0c1d00-73ad-11ea-9bce-87978664610b.jpg)
![2](https://user-images.githubusercontent.com/35672114/78095605-c03d4a00-73ad-11ea-8646-6b1f5b252575.jpg)
![3](https://user-images.githubusercontent.com/35672114/78095606-c0d5e080-73ad-11ea-8963-4da88e208c8f.jpg)
![4](https://user-images.githubusercontent.com/35672114/78095607-c16e7700-73ad-11ea-9d56-3deed5e335c0.jpg)

**Log File:**

[Wild Guns Reloaded.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4412594/Wild.Guns.Reloaded.zip)

**Comment by benderscruffy** [comment]
using 1.0.6020
no graphic glitches so far
have got up to the second stage

**Comment by EmulationFanatic** [comment]
Closing as duplicate
