### ISSUE TITLE
Animal Crossing: New Horizons

### ISSUE THREAD

**Issue by GameKittenowO** [Ryujinx/Ryujinx-Games-List#577]
Game Name:
Animal Crossing New Horizons

BuildVersion: 1.1.0-acnh3

When trying to do local multiplayer the game crashes.

Log file:
[Ryujinx_2020-04-03_12-42-44.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4430008/Ryujinx_2020-04-03_12-42-44.log)

**Comment by B3astTech** [comment]
Closing in favor of https://github.com/Ryujinx/Ryujinx-Games-List/issues/250
