### ISSUE TITLE
Graphics & Audio issues MK8 Deluxe build 1.0.4189

### ISSUE THREAD

**Issue by JackBlaze132** [Ryujinx/Ryujinx-Games-List#721]
#### Build Version : *1.0.4189*

*Playable, but there are some issues, Toad Harbor seems completely black just like animal crossing track used to seem, also there are some glitchy trees on Animal crossing track, at last but not least, Musical notes are not moving in the first and second lap, but they jump on the third lap but when you touch the ground they stop, sometimes it works correctly but the game doesn´t regonize that the ZL botton is pressed, also this track has very awful audio glitches*

#### Screenshots :

![image](https://user-images.githubusercontent.com/63567815/79084810-77fe2000-7cfb-11ea-95e6-843ca64a83ed.png)

![image](https://user-images.githubusercontent.com/63567815/79085129-f0b1ac00-7cfc-11ea-8f24-a17de4897a9b.png)

**Comment by AcK77** [comment]
Closed in favor of #244
