### ISSUE TITLE
Pokemon: Let's Go, Pikachu!

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#877]
#### Current on `master` : 1.0.4298

After selecting controls, an unskippable black screen/choppy audio intro cutscene takes place (due to nvdec). 
After this is done, menus and in-game graphics are rendered correctly.
Speed fluctuates, but even with severe slowdowns, the game can be played through.

#### Screenshots :
![2020-04-22 17_17_30-Ryujinx 1 0 4298 - Pokémon_ Let's Go, Pikachu! v1 0 0 (010003F003A34000) (64-bit](https://user-images.githubusercontent.com/62343878/80043831-ff981b80-84bf-11ea-8d3e-ad1085de78ce.png)
![2020-04-22 17_18_18-Ryujinx 1 0 4298 - Pokémon_ Let's Go, Pikachu! v1 0 0 (010003F003A34000) (64-bit](https://user-images.githubusercontent.com/62343878/80043838-03c43900-84c0-11ea-93c5-3b3195917088.png)
![2020-04-22 17_20_49-Ryujinx 1 0 4298 - Pokémon_ Let's Go, Pikachu! v1 0 0 (010003F003A34000) (64-bit](https://user-images.githubusercontent.com/62343878/80043840-03c43900-84c0-11ea-9bdf-2b27fe1f482c.png)
![2020-04-22 17_21_30-Ryujinx 1 0 4298 - Pokémon_ Let's Go, Pikachu! v1 0 0 (010003F003A34000) (64-bit](https://user-images.githubusercontent.com/62343878/80043841-058dfc80-84c0-11ea-99be-734074e4b032.png)
![2020-04-22 17_23_16-Ryujinx 1 0 4298 - Pokémon_ Let's Go, Pikachu! v1 0 0 (010003F003A34000) (64-bit](https://user-images.githubusercontent.com/62343878/80043851-0b83dd80-84c0-11ea-9c4f-398bd40df874.png)
![2020-04-22 17_24_31-Ryujinx 1 0 4298 - Pokémon_ Let's Go, Pikachu! v1 0 0 (010003F003A34000) (64-bit](https://user-images.githubusercontent.com/62343878/80043854-10489180-84c0-11ea-82c1-46c06af291eb.png)
![2020-04-22 17_25_03-Ryujinx 1 0 4298 - Pokémon_ Let's Go, Pikachu! v1 0 0 (010003F003A34000) (64-bit](https://user-images.githubusercontent.com/62343878/80043865-18a0cc80-84c0-11ea-9ec4-e06777be7c65.png)
![2020-04-22 17_25_38-Ryujinx 1 0 4298 - Pokémon_ Let's Go, Pikachu! v1 0 0 (010003F003A34000) (64-bit](https://user-images.githubusercontent.com/62343878/80043875-1fc7da80-84c0-11ea-8219-4aead3277cd4.png)
![2020-04-22 17_26_15-Ryujinx 1 0 4298 - Pokémon_ Let's Go, Pikachu! v1 0 0 (010003F003A34000) (64-bit](https://user-images.githubusercontent.com/62343878/80043883-23f3f800-84c0-11ea-98a1-9c121aaa9b27.png)
![2020-04-22 17_28_33-Ryujinx 1 0 4298 - Pokémon_ Let's Go, Pikachu! v1 0 0 (010003F003A34000) (64-bit](https://user-images.githubusercontent.com/62343878/80043901-2c4c3300-84c0-11ea-97f2-38b0bf12975a.png)
![2020-04-22 17_33_05-Ryujinx 1 0 4298 - Pokémon_ Let's Go, Pikachu! v1 0 0 (010003F003A34000) (64-bit](https://user-images.githubusercontent.com/62343878/80043912-340bd780-84c0-11ea-9c16-348f2c39a2d9.png)
![2020-04-22 17_34_11-Ryujinx 1 0 4298 - Pokémon_ Let's Go, Pikachu! v1 0 0 (010003F003A34000) (64-bit](https://user-images.githubusercontent.com/62343878/80043921-3d953f80-84c0-11ea-9185-5a5b61c30076.png)
![2020-04-22 17_34_40-Ryujinx 1 0 4298 - Pokémon_ Let's Go, Pikachu! v1 0 0 (010003F003A34000) (64-bit](https://user-images.githubusercontent.com/62343878/80043930-45ed7a80-84c0-11ea-805c-30f42f3ecfec.png)
![2020-04-22 17_35_24-Ryujinx 1 0 4298 - Pokémon_ Let's Go, Pikachu! v1 0 0 (010003F003A34000) (64-bit](https://user-images.githubusercontent.com/62343878/80043934-49810180-84c0-11ea-89ba-bf87b3873a33.png)
![2020-04-22 17_36_01-Ryujinx 1 0 4298 - Pokémon_ Let's Go, Pikachu! v1 0 0 (010003F003A34000) (64-bit](https://user-images.githubusercontent.com/62343878/80043944-543b9680-84c0-11ea-89a6-4420d4f15768.png)
![2020-04-22 17_37_20-Ryujinx 1 0 4298 - Pokémon_ Let's Go, Pikachu! v1 0 0 (010003F003A34000) (64-bit](https://user-images.githubusercontent.com/62343878/80043947-57cf1d80-84c0-11ea-9a39-3152755311a8.png)

#### Log file :

[PLGP.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4519450/PLGP.zip)

**Comment by B3astTech** [comment]
Closing in favor of https://github.com/Ryujinx/Ryujinx-Games-List/issues/327
