### ISSUE TITLE
Panzer Dragoon: Remake

### ISSUE THREAD

**Issue by Tenome** [Ryujinx/Ryujinx-Games-List#879]
## Game Name
Panzer Dragoon: Remake v1.0
#### Current on `master` : Commit Id *or* Build Version : *(e.g. 0a41a3ff or 1.0.1952)*
1.0.4298, firmware 8.1.1

*Describe the current game state here.*
I'm on old hardware, so this isn't really indicative of the state of emulation. Just putting this here for posterity. This is getting a PC port (Unity) soon anyway so no one in their right mind would emulate this.

i5 2500k 3.3GHz
AMD Radeon HD 7950 (4GB)
Windows 7 64-bit
16GB RAM

Status: Somewhat playable, cutscenes lag and have to be skipped. Gameplay hovers around 25 FPS, dipping down into the low teens. No audio lag, just the rendering.

```

#### Log file :

https://z.zz.ht/hsLov.log

**Comment by B3astTech** [comment]
Your missing the #### Current on `master` : Commit Id *or* Build Version : *(e.g. 0a41a3ff or 1.0.1952)* info and the formatting is incorrect I am closing unless these are done. Don't worry to much on the formatting but the info is necessary
