### ISSUE TITLE
The Ninja Saviors - Return of the Warriors (Ninja Warrior Once Again)

### ISSUE THREAD

**Issue by Tenome** [Ryujinx/Ryujinx-Games-List#881]
## Game Name
The Ninja Saviors - Return of the Warriors (Ninja Warrior Once Again)
#### 
*Describe the current game state here.*
Ryujinx 1.0.4298 Firmware 8.1.1

I'm on old hardware, so this isn't really indicative of the state of emulation. Just putting this here for posterity. 

i5 2500k 3.3GHz
AMD Radeon HD 7950 (4GB)
Windows 7 64-bit
16GB RAM

Status: Lags a lot, frame drops frequently. Hovers at around 25 FPS in slow motion and plummets during explosions, etc. No graphical glitches. Audio lags a bit.
```
Last error returned.
CPU.BackgroundTranslatorThread.0 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.ArgumentException: Invalid source operand kind "LocalVariable".```

#### Log file :

https://pastebin.com/NHpS7Xtb

**Comment by B3astTech** [comment]
Your missing the ```#### Current on `master` : Commit Id *or* Build Version : *(e.g. 0a41a3ff or 1.0.1952)*``` info and how the game is. including the fact the formatting is incorrect I am closing unless these are done. Don't worry to much on the formatting but the info is necessary
