### ISSUE TITLE
Our World Is Ended.

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#967]
#### Current on `master` : 1.0.4362

Game loaded and played properly for 13 minutes before crashing without a specific error in the log.

#### Screenshots :
![2020-04-28 18_18_36-Ryujinx 1 0 4362 - Our World Is Ended  v1 0 0 (0100D5D00C6BE000) (64-bit)](https://user-images.githubusercontent.com/62343878/80550765-5dc07500-897e-11ea-87d1-c420d9c0ad34.png)
![2020-04-28 18_19_08-Ryujinx 1 0 4362 - Our World Is Ended  v1 0 0 (0100D5D00C6BE000) (64-bit)](https://user-images.githubusercontent.com/62343878/80550773-62852900-897e-11ea-85a3-f13e923edf86.png)
![2020-04-28 18_21_51-Ryujinx 1 0 4362 - Our World Is Ended  v1 0 0 (0100D5D00C6BE000) (64-bit)](https://user-images.githubusercontent.com/62343878/80550777-644eec80-897e-11ea-9a7e-4d6ba434e420.png)
![2020-04-28 18_22_45-Ryujinx 1 0 4362 - Our World Is Ended  v1 0 0 (0100D5D00C6BE000) (64-bit)](https://user-images.githubusercontent.com/62343878/80550784-6add6400-897e-11ea-8ed0-b6e8d049fb56.png)
![2020-04-28 18_23_48-Ryujinx 1 0 4362 - Our World Is Ended  v1 0 0 (0100D5D00C6BE000) (64-bit)](https://user-images.githubusercontent.com/62343878/80550806-82b4e800-897e-11ea-8c80-76f4041b6fb8.png)

#### Log file :

[OurWorldIsEnded.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4549222/OurWorldIsEnded.zip)

**Comment by HorrorTroll** [comment]
erm, can u update on #164 ?

Since this one is duplicate now. Thanks!
